# Auto-generated by t2c v3.2-flash — DO NOT EDIT
from t2c.ontology import Claim, Entity, Event, Relation

Entity(
    id='hongloumeng_ent_0001',
    name='女娲氏',
    kind='person',
    aliases=['娲皇氏'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007', 'hongloumeng_seg_0008']
)

Entity(
    id='hongloumeng_ent_0002',
    name='大荒山无稽崖',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007', 'hongloumeng_seg_0028']
)

Entity(
    id='hongloumeng_ent_0003',
    name='青埂峰',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0028']
)

Entity(
    id='hongloumeng_ent_0004',
    name='顽石',
    kind='artifact',
    aliases=['石头', '石兄', '蠢物', '美玉'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007', 'hongloumeng_seg_0009', 'hongloumeng_seg_0011', 'hongloumeng_seg_0021', 'hongloumeng_seg_0034', 'hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0005',
    name='一僧一道',
    kind='person',
    aliases=['二仙师', '茫茫大士', '渺渺真人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010', 'hongloumeng_seg_0012', 'hongloumeng_seg_0029']
)

Entity(
    id='hongloumeng_ent_0006',
    name='红尘',
    kind='concept',
    aliases=['人世间'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010', 'hongloumeng_seg_0011', 'hongloumeng_seg_0013', 'hongloumeng_seg_0029']
)

Entity(
    id='hongloumeng_ent_0007',
    name='空空道人',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0028']
)

Entity(
    id='hongloumeng_ent_0008',
    name='朝代年纪',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033', 'hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0009',
    name='异样女子',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Event(
    id='hongloumeng_evt_0001',
    name='女娲氏炼石补天',
    kind='action',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0004'],
    time='女娲氏炼石补天之时',
    location='大荒山无稽崖',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007']
)

Event(
    id='hongloumeng_evt_0002',
    name='顽石被弃于青埂峰下',
    kind='state_change',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0004'],
    time='',
    location='青埂峰下',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008']
)

Event(
    id='hongloumeng_evt_0003',
    name='顽石灵性已通',
    kind='state_change',
    participants=['hongloumeng_ent_0004'],
    time='自经煅炼之后',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0009']
)

Event(
    id='hongloumeng_evt_0004',
    name='一僧一道来至峰下高谈快论',
    kind='action',
    participants=['hongloumeng_ent_0005'],
    time='一日',
    location='青埂峰下',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010']
)

Event(
    id='hongloumeng_evt_0005',
    name='顽石苦求一僧一道携带入红尘',
    kind='action',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0005'],
    time='',
    location='青埂峰下',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0011', 'hongloumeng_seg_0014']
)

Event(
    id='hongloumeng_evt_0006',
    name='僧人施幻术将大石变成美玉',
    kind='state_change',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0004'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0021']
)

Event(
    id='hongloumeng_evt_0007',
    name='僧人袖了石头同道人飘然而去',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0004'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0027']
)

Event(
    id='hongloumeng_evt_0008',
    name='空空道人访道求仙经过青埂峰见石上字迹',
    kind='occurrence',
    participants=['hongloumeng_ent_0007', 'hongloumeng_ent_0004'],
    time='不知过了几世几劫',
    location='大荒山无稽崖青埂峰下',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0028']
)

Event(
    id='hongloumeng_evt_0009',
    name='空空道人向石头提出故事无朝代年纪无善政的质疑',
    kind='action',
    participants=['hongloumeng_ent_0007', 'hongloumeng_ent_0004'],
    time='',
    location='大荒山无稽崖青埂峰下',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Claim(
    id='hongloumeng_clm_0001',
    subject='hongloumeng_ent_0004',
    predicate='is_abandoned_by',
    object='hongloumeng_ent_0001',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008']
)

Claim(
    id='hongloumeng_clm_0002',
    subject='hongloumeng_ent_0004',
    predicate='lacks_ability',
    object='hongloumeng_ent_0008',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0009']
)

Claim(
    id='hongloumeng_clm_0003',
    subject='hongloumeng_ent_0005',
    predicate='said',
    object='hongloumeng_ent_0006',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0013']
)

Claim(
    id='hongloumeng_clm_0004',
    subject='hongloumeng_ent_0005',
    predicate='agrees_to_carry',
    object='hongloumeng_ent_0004',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0015']
)

Claim(
    id='hongloumeng_clm_0005',
    subject='hongloumeng_ent_0005',
    predicate='will_assist_with_magic',
    object='hongloumeng_ent_0004',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0019']
)

Claim(
    id='hongloumeng_clm_0006',
    subject='hongloumeng_ent_0004',
    predicate='transformed_into',
    object='hongloumeng_ent_0009',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0021']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0004',
    predicate='carried_into',
    object='hongloumeng_ent_0006',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0029']
)

Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0004',
    predicate='lacks',
    object='hongloumeng_ent_0008',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033', 'hongloumeng_seg_0035']
)

Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0004',
    predicate='contains',
    object='hongloumeng_ent_0010',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Relation(
    id='hongloumeng_rel_0001',
    subject='hongloumeng_ent_0004',
    predicate='is_abandoned_by',
    object='hongloumeng_ent_0001',
    claim_id='hongloumeng_clm_0001',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0002',
    subject='hongloumeng_ent_0004',
    predicate='lacks_ability',
    object='hongloumeng_ent_0008',
    claim_id='hongloumeng_clm_0002',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0003',
    subject='hongloumeng_ent_0005',
    predicate='agrees_to_carry',
    object='hongloumeng_ent_0004',
    claim_id='hongloumeng_clm_0004',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0004',
    subject='hongloumeng_ent_0005',
    predicate='will_assist_with_magic',
    object='hongloumeng_ent_0004',
    claim_id='hongloumeng_clm_0005',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0005',
    subject='hongloumeng_ent_0004',
    predicate='transformed_into',
    object='hongloumeng_ent_0009',
    claim_id='hongloumeng_clm_0006',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0006',
    subject='hongloumeng_ent_0004',
    predicate='carried_into',
    object='hongloumeng_ent_0006',
    claim_id='hongloumeng_clm_0007',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0007',
    subject='hongloumeng_ent_0004',
    predicate='lacks',
    object='hongloumeng_ent_0008',
    claim_id='hongloumeng_clm_0008',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0008',
    subject='hongloumeng_ent_0004',
    predicate='contains',
    object='hongloumeng_ent_0010',
    claim_id='hongloumeng_clm_0009',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0010',
    name='《石头记》',
    kind='artifact',
    aliases=['《情僧录》', '《红楼梦》', '《风月宝鉴》'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038', 'hongloumeng_seg_0041', 'hongloumeng_seg_0043', 'hongloumeng_seg_0044']
)

Entity(
    id='hongloumeng_ent_0011',
    name='情僧',
    kind='person',
    aliases=['空空道人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038', 'hongloumeng_seg_0041']
)

Entity(
    id='hongloumeng_ent_0012',
    name='吴玉峰',
    kind='person',
    aliases=['玉峰'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0043']
)

Entity(
    id='hongloumeng_ent_0013',
    name='孔梅溪',
    kind='person',
    aliases=['东鲁孔梅溪'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0044']
)

Entity(
    id='hongloumeng_ent_0014',
    name='脂砚斋',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0047']
)

Entity(
    id='hongloumeng_ent_0015',
    name='姑苏',
    kind='location',
    aliases=['东南一隅'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0049']
)

Entity(
    id='hongloumeng_ent_0016',
    name='阊门',
    kind='location',
    aliases=['城'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0049']
)

Entity(
    id='hongloumeng_ent_0017',
    name='十里街',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Entity(
    id='hongloumeng_ent_0018',
    name='仁清巷',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Entity(
    id='hongloumeng_ent_0019',
    name='葫芦庙',
    kind='location',
    aliases=['古庙'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Entity(
    id='hongloumeng_ent_0020',
    name='甄士隐',
    kind='person',
    aliases=['士隐'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0051', 'hongloumeng_seg_0054', 'hongloumeng_seg_0056']
)

Entity(
    id='hongloumeng_ent_0021',
    name='甄家',
    kind='org',
    aliases=['一家乡宦'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0051', 'hongloumeng_seg_0053']
)

Entity(
    id='hongloumeng_ent_0022',
    name='封氏',
    kind='person',
    aliases=['嫡妻'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0052']
)

Entity(
    id='hongloumeng_ent_0023',
    name='英莲',
    kind='person',
    aliases=['一女'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0055']
)

Entity(
    id='hongloumeng_ent_0024',
    name='风流冤家',
    kind='concept',
    aliases=['风流冤孽'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0061', 'hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0010',
    name='空空道人检阅抄录《石头记》',
    kind='action',
    participants=['hongloumeng_ent_0007', 'hongloumeng_ent_0010'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038', 'hongloumeng_seg_0040']
)

Event(
    id='hongloumeng_evt_0011',
    name='空空道人易名情僧并改书名',
    kind='state_change',
    participants=['hongloumeng_ent_0007', 'hongloumeng_ent_0011', 'hongloumeng_ent_0010'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0041']
)

Event(
    id='hongloumeng_evt_0012',
    name='吴玉峰题名《红楼梦》',
    kind='action',
    participants=['hongloumeng_ent_0012', 'hongloumeng_ent_0010'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0043']
)

Event(
    id='hongloumeng_evt_0013',
    name='孔梅溪题名《风月宝鉴》',
    kind='action',
    participants=['hongloumeng_ent_0013', 'hongloumeng_ent_0010'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0044']
)

Event(
    id='hongloumeng_evt_0014',
    name='脂砚斋抄阅再评仍用《石头记》',
    kind='action',
    participants=['hongloumeng_ent_0014', 'hongloumeng_ent_0010'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0047']
)

Event(
    id='hongloumeng_evt_0015',
    name='甄士隐梦幻遇僧道',
    kind='occurrence',
    participants=['hongloumeng_ent_0019', 'hongloumeng_ent_0005'],
    time='一日，炎夏永昼',
    location='书房，梦至一处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0056', 'hongloumeng_seg_0057', 'hongloumeng_seg_0058']
)

Event(
    id='hongloumeng_evt_0016',
    name='僧道谈论风流公案',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0004', 'hongloumeng_ent_0025'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0059', 'hongloumeng_seg_0061', 'hongloumeng_seg_0063']
)

Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0007',
    predicate='said',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0037']
)

Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0010',
    predicate='has_attribute',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038', 'hongloumeng_seg_0039']
)

Claim(
    id='hongloumeng_clm_0012',
    subject='hongloumeng_ent_0019',
    predicate='lives_in',
    object='hongloumeng_ent_0018',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0051']
)

Claim(
    id='hongloumeng_clm_0013',
    subject='hongloumeng_ent_0019',
    predicate='is_spouse_of',
    object='hongloumeng_ent_0022',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0052']
)

Claim(
    id='hongloumeng_clm_0014',
    subject='hongloumeng_ent_0021',
    predicate='is_located_in',
    object='hongloumeng_ent_0020',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Claim(
    id='hongloumeng_clm_0015',
    subject='hongloumeng_ent_0018',
    predicate='is_located_in',
    object='hongloumeng_ent_0017',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Claim(
    id='hongloumeng_clm_0016',
    subject='hongloumeng_ent_0019',
    predicate='is_father_of',
    object='hongloumeng_ent_0024',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0055']
)

Claim(
    id='hongloumeng_clm_0017',
    subject='hongloumeng_ent_0005',
    predicate='carries',
    object='hongloumeng_ent_0004',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0059']
)

Claim(
    id='hongloumeng_clm_0018',
    subject='hongloumeng_ent_0025',
    predicate='will_experience',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0061', 'hongloumeng_seg_0063']
)

Relation(
    id='hongloumeng_rel_0009',
    subject='hongloumeng_ent_0019',
    predicate='lives_in',
    object='hongloumeng_ent_0018',
    claim_id='hongloumeng_clm_0012',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0010',
    subject='hongloumeng_ent_0019',
    predicate='is_spouse_of',
    object='hongloumeng_ent_0022',
    claim_id='hongloumeng_clm_0013',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0011',
    subject='hongloumeng_ent_0021',
    predicate='is_located_in',
    object='hongloumeng_ent_0020',
    claim_id='hongloumeng_clm_0014',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0012',
    subject='hongloumeng_ent_0018',
    predicate='is_located_in',
    object='hongloumeng_ent_0017',
    claim_id='hongloumeng_clm_0015',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0013',
    subject='hongloumeng_ent_0019',
    predicate='is_father_of',
    object='hongloumeng_ent_0024',
    claim_id='hongloumeng_clm_0016',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0014',
    subject='hongloumeng_ent_0005',
    predicate='carries',
    object='hongloumeng_ent_0004',
    claim_id='hongloumeng_clm_0017',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0025',
    name='西方灵河岸上',
    kind='location',
    aliases=['灵河岸上'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0026',
    name='三生石畔',
    kind='location',
    aliases=['三生石'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0027',
    name='绛珠草',
    kind='artifact',
    aliases=['绛珠仙子'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0028',
    name='赤瑕宫',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0029',
    name='神瑛侍者',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0030',
    name='离恨天外',
    kind='location',
    aliases=['离恨天'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0031',
    name='蜜青果',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0032',
    name='灌愁海水',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0033',
    name='警幻仙子',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Entity(
    id='hongloumeng_ent_0034',
    name='太虚幻境',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0092', 'hongloumeng_seg_0093']
)

Entity(
    id='hongloumeng_ent_0035',
    name='通灵宝玉',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0089']
)

Entity(
    id='hongloumeng_ent_0036',
    name='北邙山',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0109']
)

Entity(
    id='hongloumeng_ent_0037',
    name='贾雨村',
    kind='person',
    aliases=['时飞', '雨村'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0114', 'hongloumeng_seg_0115']
)

Entity(
    id='hongloumeng_ent_0038',
    name='胡州',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0115']
)

Event(
    id='hongloumeng_evt_0017',
    name='神瑛侍者灌溉绛珠草',
    kind='action',
    participants=['hongloumeng_ent_0029', 'hongloumeng_ent_0027'],
    time='',
    location='西方灵河岸上三生石畔',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Event(
    id='hongloumeng_evt_0018',
    name='绛珠草脱却草胎木质修成女体',
    kind='state_change',
    participants=['hongloumeng_ent_0027'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Event(
    id='hongloumeng_evt_0019',
    name='神瑛侍者凡心偶炽下凡造历幻缘',
    kind='action',
    participants=['hongloumeng_ent_0029'],
    time='昌明太平朝世',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Event(
    id='hongloumeng_evt_0020',
    name='绛珠仙子下世为人还泪',
    kind='action',
    participants=['hongloumeng_ent_0027'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Event(
    id='hongloumeng_evt_0021',
    name='一僧一道决定下世度脱几个',
    kind='action',
    participants=['hongloumeng_ent_0005'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0071', 'hongloumeng_seg_0072']
)

Event(
    id='hongloumeng_evt_0022',
    name='甄士隐梦听二仙师谈论因果',
    kind='occurrence',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0005'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0076']
)

Event(
    id='hongloumeng_evt_0023',
    name='甄士隐向二仙师询问蠢物',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0005'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0079', 'hongloumeng_seg_0085']
)

Event(
    id='hongloumeng_evt_0024',
    name='僧人将通灵宝玉递与甄士隐',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0020', 'hongloumeng_ent_0032'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0088']
)

Event(
    id='hongloumeng_evt_0025',
    name='僧人夺回通灵宝玉与道人走入太虚幻境',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0032', 'hongloumeng_ent_0031'],
    time='',
    location='太虚幻境',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0091', 'hongloumeng_seg_0092']
)

Event(
    id='hongloumeng_evt_0026',
    name='甄士隐梦醒',
    kind='occurrence',
    participants=['hongloumeng_ent_0020'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0096', 'hongloumeng_seg_0097']
)

Event(
    id='hongloumeng_evt_0027',
    name='癞僧跛道向甄士隐化英莲',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0020', 'hongloumeng_ent_0023'],
    time='',
    location='街前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0100', 'hongloumeng_seg_0102', 'hongloumeng_seg_0104']
)

Event(
    id='hongloumeng_evt_0028',
    name='一僧一道分手约定北邙山会齐',
    kind='occurrence',
    participants=['hongloumeng_ent_0005'],
    time='三劫后',
    location='北邙山',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0109']
)

Event(
    id='hongloumeng_evt_0029',
    name='贾雨村从葫芦庙走出来',
    kind='occurrence',
    participants=['hongloumeng_ent_0034'],
    time='',
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0114']
)

Claim(
    id='hongloumeng_clm_0019',
    subject='hongloumeng_ent_0029',
    predicate='irrigates',
    object='hongloumeng_ent_0027',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Claim(
    id='hongloumeng_clm_0020',
    subject='hongloumeng_ent_0027',
    predicate='owes_debt_to',
    object='hongloumeng_ent_0029',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Claim(
    id='hongloumeng_clm_0021',
    subject='hongloumeng_ent_0027',
    predicate='will_repay_with',
    object='hongloumeng_ent_0027',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Claim(
    id='hongloumeng_clm_0022',
    subject='hongloumeng_ent_0029',
    predicate='registered_at',
    object='hongloumeng_ent_0030',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0065']
)

Claim(
    id='hongloumeng_clm_0023',
    subject='hongloumeng_ent_0023',
    predicate='is_described_as',
    object='',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0102']
)

Claim(
    id='hongloumeng_clm_0024',
    subject='hongloumeng_ent_0034',
    predicate='is_from',
    object='hongloumeng_ent_0035',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0115']
)

Claim(
    id='hongloumeng_clm_0025',
    subject='hongloumeng_ent_0034',
    predicate='lives_in',
    object='hongloumeng_ent_0019',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0114', 'hongloumeng_seg_0116']
)

Claim(
    id='hongloumeng_clm_0026',
    subject='hongloumeng_ent_0034',
    predicate='is_acquainted_with',
    object='hongloumeng_ent_0020',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0116']
)

Relation(
    id='hongloumeng_rel_0015',
    subject='hongloumeng_ent_0029',
    predicate='irrigates',
    object='hongloumeng_ent_0027',
    claim_id='hongloumeng_clm_0019',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0016',
    subject='hongloumeng_ent_0027',
    predicate='owes_debt_to',
    object='hongloumeng_ent_0029',
    claim_id='hongloumeng_clm_0020',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0017',
    subject='hongloumeng_ent_0029',
    predicate='registered_at',
    object='hongloumeng_ent_0030',
    claim_id='hongloumeng_clm_0022',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0018',
    subject='hongloumeng_ent_0034',
    predicate='is_from',
    object='hongloumeng_ent_0035',
    claim_id='hongloumeng_clm_0024',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0019',
    subject='hongloumeng_ent_0034',
    predicate='lives_in',
    object='hongloumeng_ent_0019',
    claim_id='hongloumeng_clm_0025',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0020',
    subject='hongloumeng_ent_0034',
    predicate='is_acquainted_with',
    object='hongloumeng_ent_0020',
    claim_id='hongloumeng_clm_0026',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0039',
    name='小女',
    kind='person',
    aliases=['女儿'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0119', 'hongloumeng_seg_0120']
)

Entity(
    id='hongloumeng_ent_0040',
    name='严老爷',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0122']
)

Entity(
    id='hongloumeng_ent_0041',
    name='小童',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0121', 'hongloumeng_seg_0138', 'hongloumeng_seg_0172']
)

Entity(
    id='hongloumeng_ent_0042',
    name='甄家丫鬟',
    kind='person',
    aliases=['丫鬟', '这女子', '玉人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0129', 'hongloumeng_seg_0130', 'hongloumeng_seg_0132', 'hongloumeng_seg_0133', 'hongloumeng_seg_0137', 'hongloumeng_seg_0142', 'hongloumeng_seg_0146']
)

Entity(
    id='hongloumeng_ent_0043',
    name='书房',
    kind='location',
    aliases=['小斋', '书院', '敝斋'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0119', 'hongloumeng_seg_0120', 'hongloumeng_seg_0141', 'hongloumeng_seg_0156', 'hongloumeng_seg_0159']
)

Entity(
    id='hongloumeng_ent_0044',
    name='前厅',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0127']
)

Entity(
    id='hongloumeng_ent_0045',
    name='神京',
    kind='location',
    aliases=['神都'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0169', 'hongloumeng_seg_0177']
)

Entity(
    id='hongloumeng_ent_0046',
    name='五十两白银',
    kind='artifact',
    aliases=['银'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0172', 'hongloumeng_seg_0174']
)

Entity(
    id='hongloumeng_ent_0047',
    name='冬衣',
    kind='artifact',
    aliases=['衣'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0172', 'hongloumeng_seg_0174']
)

Entity(
    id='hongloumeng_ent_0048',
    name='荐书',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0177']
)

Entity(
    id='hongloumeng_ent_0049',
    name='中秋佳节',
    kind='concept',
    aliases=['中秋', '团圆之节'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0140', 'hongloumeng_seg_0156']
)

Entity(
    id='hongloumeng_ent_0050',
    name='元霄佳节',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0180']
)

Event(
    id='hongloumeng_evt_0030',
    name='甄士隐邀贾雨村入书房交谈',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0037'],
    time='永昼',
    location='书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0119', 'hongloumeng_seg_0120']
)

Event(
    id='hongloumeng_evt_0031',
    name='严老爷来拜',
    kind='occurrence',
    participants=['hongloumeng_ent_0041'],
    time='',
    location='前厅',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0122', 'hongloumeng_seg_0127']
)

Event(
    id='hongloumeng_evt_0032',
    name='贾雨村偶遇甄家丫鬟撷花',
    kind='occurrence',
    participants=['hongloumeng_ent_0037', 'hongloumeng_ent_0043'],
    time='',
    location='窗外',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0129', 'hongloumeng_seg_0130', 'hongloumeng_seg_0132']
)

Event(
    id='hongloumeng_evt_0033',
    name='甄家丫鬟回头两次看贾雨村',
    kind='action',
    participants=['hongloumeng_ent_0043', 'hongloumeng_ent_0037'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0133', 'hongloumeng_seg_0134', 'hongloumeng_seg_0135', 'hongloumeng_seg_0136']
)

Event(
    id='hongloumeng_evt_0034',
    name='贾雨村自便出门',
    kind='action',
    participants=['hongloumeng_ent_0037'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0138']
)

Event(
    id='hongloumeng_evt_0035',
    name='甄士隐步月至庙中邀贾雨村',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0037'],
    time='中秋佳节',
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0140', 'hongloumeng_seg_0141']
)

Event(
    id='hongloumeng_evt_0036',
    name='贾雨村吟诗抒怀',
    kind='action',
    participants=['hongloumeng_ent_0037'],
    time='中秋佳节',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0143', 'hongloumeng_seg_0144', 'hongloumeng_seg_0145', 'hongloumeng_seg_0146', 'hongloumeng_seg_0147', 'hongloumeng_seg_0148']
)

Event(
    id='hongloumeng_evt_0037',
    name='甄士隐与贾雨村饮酒谈笑',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0037'],
    time='中秋佳节',
    location='书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0159', 'hongloumeng_seg_0160', 'hongloumeng_seg_0161', 'hongloumeng_seg_0162', 'hongloumeng_seg_0163']
)

Event(
    id='hongloumeng_evt_0038',
    name='甄士隐赠银衣资助贾雨村',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0037'],
    time='中秋佳节',
    location='书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0171', 'hongloumeng_seg_0172', 'hongloumeng_seg_0173', 'hongloumeng_seg_0174']
)

Event(
    id='hongloumeng_evt_0039',
    name='贾雨村连夜进京',
    kind='action',
    participants=['hongloumeng_ent_0037'],
    time='十九日五鼓',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0178']
)

Claim(
    id='hongloumeng_clm_0027',
    subject='hongloumeng_ent_0043',
    predicate='thinks',
    object='hongloumeng_ent_0037',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0133', 'hongloumeng_seg_0134']
)

Claim(
    id='hongloumeng_clm_0028',
    subject='hongloumeng_ent_0043',
    predicate='thinks',
    object='hongloumeng_ent_0037',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0135']
)

Claim(
    id='hongloumeng_clm_0029',
    subject='hongloumeng_ent_0037',
    predicate='thinks',
    object='hongloumeng_ent_0043',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0137']
)

Claim(
    id='hongloumeng_clm_0030',
    subject='hongloumeng_ent_0037',
    predicate='thinks',
    object='hongloumeng_ent_0043',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0137']
)

Claim(
    id='hongloumeng_clm_0031',
    subject='hongloumeng_ent_0020',
    predicate='said',
    object='hongloumeng_ent_0037',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0167']
)

Claim(
    id='hongloumeng_clm_0032',
    subject='hongloumeng_ent_0037',
    predicate='said',
    object='hongloumeng_ent_0020',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0169']
)

Claim(
    id='hongloumeng_clm_0033',
    subject='hongloumeng_ent_0020',
    predicate='gives',
    object='hongloumeng_ent_0037',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0172']
)

Claim(
    id='hongloumeng_clm_0034',
    subject='hongloumeng_ent_0037',
    predicate='said',
    object='hongloumeng_ent_0020',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0178']
)

Relation(
    id='hongloumeng_rel_0021',
    subject='hongloumeng_ent_0043',
    predicate='is_member_of',
    object='hongloumeng_ent_0021',
    claim_id='hongloumeng_clm_0027',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0022',
    subject='hongloumeng_ent_0037',
    predicate='lives_in',
    object='hongloumeng_ent_0019',
    claim_id='hongloumeng_clm_0027',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0023',
    subject='hongloumeng_ent_0037',
    predicate='is_acquaintance_of',
    object='hongloumeng_ent_0043',
    claim_id='hongloumeng_clm_0029',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0024',
    subject='hongloumeng_ent_0020',
    predicate='patronizes',
    object='hongloumeng_ent_0037',
    claim_id='hongloumeng_clm_0031',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0025',
    subject='hongloumeng_ent_0037',
    predicate='owns',
    object='hongloumeng_ent_0046',
    claim_id='hongloumeng_clm_0032',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0026',
    subject='hongloumeng_ent_0037',
    predicate='owns',
    object='hongloumeng_ent_0047',
    claim_id='hongloumeng_clm_0032',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0051',
    name='霍启',
    kind='person',
    aliases=['家人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0181']
)

Entity(
    id='hongloumeng_ent_0052',
    name='社火花灯',
    kind='artifact',
    aliases=['花灯'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0181']
)

Entity(
    id='hongloumeng_ent_0053',
    name='他乡',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0184']
)

Entity(
    id='hongloumeng_ent_0054',
    name='封氏孺人',
    kind='person',
    aliases=['封氏', '妻子', '孺人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0189', 'hongloumeng_seg_0196']
)

Entity(
    id='hongloumeng_ent_0055',
    name='葫芦庙',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0190']
)

Entity(
    id='hongloumeng_ent_0056',
    name='和尚',
    kind='org',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0190']
)

Entity(
    id='hongloumeng_ent_0057',
    name='一条街',
    kind='location',
    aliases=['街'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0191']
)

Entity(
    id='hongloumeng_ent_0058',
    name='军民',
    kind='org',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0192']
)

Entity(
    id='hongloumeng_ent_0059',
    name='田庄',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0196']
)

Entity(
    id='hongloumeng_ent_0060',
    name='官兵',
    kind='org',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Entity(
    id='hongloumeng_ent_0061',
    name='封肃',
    kind='person',
    aliases=['岳丈', '岳丈家'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0198', 'hongloumeng_seg_0199']
)

Entity(
    id='hongloumeng_ent_0062',
    name='大如州',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0199']
)

Entity(
    id='hongloumeng_ent_0063',
    name='银子',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0201']
)

Entity(
    id='hongloumeng_ent_0064',
    name='房地',
    kind='artifact',
    aliases=['薄田朽屋'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0201', 'hongloumeng_seg_0202']
)

Entity(
    id='hongloumeng_ent_0065',
    name='跛足道人',
    kind='person',
    aliases=['道人', '疯道人', '疯跛道人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0206', 'hongloumeng_seg_0243', 'hongloumeng_seg_0239']
)

Entity(
    id='hongloumeng_ent_0066',
    name='《好了歌》',
    kind='artifact',
    aliases=['歌儿'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0221']
)

Entity(
    id='hongloumeng_ent_0067',
    name='褡裢',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0243']
)

Entity(
    id='hongloumeng_ent_0068',
    name='街坊',
    kind='org',
    aliases=['众人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0244']
)

Entity(
    id='hongloumeng_ent_0069',
    name='新太爷',
    kind='person',
    aliases=['太爷'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0249']
)

Entity(
    id='hongloumeng_ent_0070',
    name='军牢快手',
    kind='org',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0250']
)

Event(
    id='hongloumeng_evt_0040',
    name='霍启抱英莲看灯',
    kind='action',
    participants=['hongloumeng_ent_0051', 'hongloumeng_ent_0023'],
    time='半夜中',
    location='社火花灯',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0181']
)

Event(
    id='hongloumeng_evt_0041',
    name='英莲丢失',
    kind='occurrence',
    participants=['hongloumeng_ent_0023', 'hongloumeng_ent_0051'],
    time='半夜',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0182']
)

Event(
    id='hongloumeng_evt_0042',
    name='霍启寻找英莲',
    kind='action',
    participants=['hongloumeng_ent_0051', 'hongloumeng_ent_0023'],
    time='半夜至天明',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0183']
)

Event(
    id='hongloumeng_evt_0043',
    name='霍启逃往他乡',
    kind='action',
    participants=['hongloumeng_ent_0051'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0184']
)

Event(
    id='hongloumeng_evt_0044',
    name='士隐夫妇寻找女儿',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0054'],
    time='一夜',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0185']
)

Event(
    id='hongloumeng_evt_0045',
    name='士隐夫妇思女成疾',
    kind='state_change',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0054'],
    time='看看一月',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0188', 'hongloumeng_seg_0189']
)

Event(
    id='hongloumeng_evt_0046',
    name='葫芦庙失火',
    kind='occurrence',
    participants=['hongloumeng_ent_0055', 'hongloumeng_ent_0056'],
    time='三月十五',
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0190']
)

Event(
    id='hongloumeng_evt_0047',
    name='火烧一条街',
    kind='occurrence',
    participants=['hongloumeng_ent_0057'],
    time='直烧了一夜',
    location='一条街',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0191', 'hongloumeng_seg_0193']
)

Event(
    id='hongloumeng_evt_0048',
    name='军民救火',
    kind='action',
    participants=['hongloumeng_ent_0058'],
    location='一条街',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0192']
)

Event(
    id='hongloumeng_evt_0049',
    name='甄家被烧毁',
    kind='state_change',
    participants=['hongloumeng_ent_0021'],
    location='甄家',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0194']
)

Event(
    id='hongloumeng_evt_0050',
    name='士隐投奔岳丈',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0061'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0198']
)

Event(
    id='hongloumeng_evt_0051',
    name='封肃哄骗士隐',
    kind='action',
    participants=['hongloumeng_ent_0061', 'hongloumeng_ent_0020'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0202']
)

Event(
    id='hongloumeng_evt_0052',
    name='士隐暮年穷困潦倒',
    kind='occurrence',
    participants=['hongloumeng_ent_0020'],
    time='一二年',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0203', 'hongloumeng_seg_0205']
)

Event(
    id='hongloumeng_evt_0053',
    name='士隐注解《好了歌》',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0065'],
    location='街前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0224', 'hongloumeng_seg_0227']
)

Event(
    id='hongloumeng_evt_0054',
    name='士隐随道人出家',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0065'],
    location='街前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0243']
)

Event(
    id='hongloumeng_evt_0055',
    name='封氏访寻士隐',
    kind='action',
    participants=['hongloumeng_ent_0054', 'hongloumeng_ent_0061'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0245']
)

Event(
    id='hongloumeng_evt_0056',
    name='新太爷到任',
    kind='occurrence',
    participants=['hongloumeng_ent_0069'],
    location='街上',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0249']
)

Claim(
    id='hongloumeng_clm_0035',
    subject='hongloumeng_ent_0051',
    predicate='is_servant_of',
    object='hongloumeng_ent_0020',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0181']
)

Claim(
    id='hongloumeng_clm_0036',
    subject='hongloumeng_ent_0020',
    predicate='is_father_of',
    object='hongloumeng_ent_0023',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0186']
)

Claim(
    id='hongloumeng_clm_0037',
    subject='hongloumeng_ent_0054',
    predicate='is_mother_of',
    object='hongloumeng_ent_0023',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0186']
)

Claim(
    id='hongloumeng_clm_0038',
    subject='hongloumeng_ent_0020',
    predicate='is_husband_of',
    object='hongloumeng_ent_0054',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0185']
)

Claim(
    id='hongloumeng_clm_0039',
    subject='hongloumeng_ent_0061',
    predicate='is_father_of',
    object='hongloumeng_ent_0054',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0198']
)

Claim(
    id='hongloumeng_clm_0040',
    subject='hongloumeng_ent_0061',
    predicate='lives_in',
    object='hongloumeng_ent_0062',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0199']
)

Claim(
    id='hongloumeng_clm_0041',
    subject='hongloumeng_ent_0021',
    predicate='located_next_to',
    object='hongloumeng_ent_0055',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0194']
)

Claim(
    id='hongloumeng_clm_0042',
    subject='hongloumeng_ent_0020',
    predicate='owns',
    object='hongloumeng_ent_0059',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0196']
)

Claim(
    id='hongloumeng_clm_0043',
    subject='hongloumeng_ent_0065',
    predicate='sings',
    object='hongloumeng_ent_0066',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0206']
)

Claim(
    id='hongloumeng_clm_0044',
    subject='hongloumeng_ent_0020',
    predicate='interprets',
    object='hongloumeng_ent_0066',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0224']
)

Relation(
    id='hongloumeng_rel_0027',
    subject='hongloumeng_ent_0051',
    predicate='is_servant_of',
    object='hongloumeng_ent_0020',
    claim_id='hongloumeng_clm_0035',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0028',
    subject='hongloumeng_ent_0020',
    predicate='is_father_of',
    object='hongloumeng_ent_0023',
    claim_id='hongloumeng_clm_0036',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0029',
    subject='hongloumeng_ent_0054',
    predicate='is_mother_of',
    object='hongloumeng_ent_0023',
    claim_id='hongloumeng_clm_0037',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0030',
    subject='hongloumeng_ent_0020',
    predicate='is_husband_of',
    object='hongloumeng_ent_0054',
    claim_id='hongloumeng_clm_0038',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0031',
    subject='hongloumeng_ent_0061',
    predicate='is_father_of',
    object='hongloumeng_ent_0054',
    claim_id='hongloumeng_clm_0039',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0032',
    subject='hongloumeng_ent_0061',
    predicate='lives_in',
    object='hongloumeng_ent_0062',
    claim_id='hongloumeng_clm_0040',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0033',
    subject='hongloumeng_ent_0021',
    predicate='located_next_to',
    object='hongloumeng_ent_0055',
    claim_id='hongloumeng_clm_0041',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0034',
    subject='hongloumeng_ent_0020',
    predicate='owns',
    object='hongloumeng_ent_0059',
    claim_id='hongloumeng_clm_0042',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0071',
    name='官府',
    kind='person',
    aliases=['官', '乌帽猩袍的官府'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0251', 'hongloumeng_seg_0252']
)

Entity(
    id='hongloumeng_ent_0072',
    name='大轿',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0251']
)

Entity(
    id='hongloumeng_ent_0073',
    name='差人',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0254']
)

Entity(
    id='hongloumeng_ent_0074',
    name='房中',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0253']
)

Event(
    id='hongloumeng_evt_0057',
    name='大轿抬着官府过去',
    kind='occurrence',
    participants=['hongloumeng_ent_0072', 'hongloumeng_ent_0071'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0251']
)

Event(
    id='hongloumeng_evt_0058',
    name='甄士隐觉得官面善',
    kind='action',
    participants=['hongloumeng_ent_0020', 'hongloumeng_ent_0071'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0252']
)

Event(
    id='hongloumeng_evt_0059',
    name='甄士隐进入房中丢过不提',
    kind='action',
    participants=['hongloumeng_ent_0020'],
    location='hongloumeng_ent_0074',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0253']
)

Event(
    id='hongloumeng_evt_0060',
    name='差人传人问话',
    kind='action',
    participants=['hongloumeng_ent_0073'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0254']
)

Event(
    id='hongloumeng_evt_0061',
    name='封肃听闻传唤惊吓',
    kind='state_change',
    participants=['hongloumeng_ent_0061'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0255']
)

Claim(
    id='hongloumeng_clm_0045',
    subject='hongloumeng_ent_0020',
    predicate='said',
    object='hongloumeng_ent_0071',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0252']
)

Claim(
    id='hongloumeng_clm_0046',
    subject='hongloumeng_ent_0073',
    predicate='said',
    object='hongloumeng_ent_0061',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0254']
)

Claim(
    id='hongloumeng_clm_0047',
    subject='hongloumeng_ent_0073',
    predicate='represents',
    object='hongloumeng_ent_0069',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0254']
)

Relation(
    id='hongloumeng_rel_0035',
    subject='hongloumeng_ent_0020',
    predicate='said',
    object='hongloumeng_ent_0071',
    claim_id='hongloumeng_clm_0045',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0036',
    subject='hongloumeng_ent_0073',
    predicate='said',
    object='hongloumeng_ent_0061',
    claim_id='hongloumeng_clm_0046',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0037',
    subject='hongloumeng_ent_0073',
    predicate='represents',
    object='hongloumeng_ent_0069',
    claim_id='hongloumeng_clm_0047',
    evidence_refs=[]
)

