# Auto-generated by t2c v3.2-flash — DO NOT EDIT
from t2c.ontology import Claim, Entity, Event, Relation

Entity(
    id='hongloumeng_ent_0139',
    name='张如圭',
    kind='person',
    aliases=['如圭', '张如圭者'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0447']
)

Entity(
    id='hongloumeng_ent_0140',
    name='起复旧员之信',
    kind='concept',
    aliases=['此信'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0448', 'hongloumeng_seg_0449']
)

Entity(
    id='hongloumeng_ent_0141',
    name='邸报',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0451']
)

Entity(
    id='hongloumeng_ent_0142',
    name='荐书',
    kind='artifact',
    aliases=['荐书一封'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0453']
)

Entity(
    id='hongloumeng_ent_0143',
    name='大内兄',
    kind='person',
    aliases=['赦', '恩侯'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Entity(
    id='hongloumeng_ent_0144',
    name='二内兄',
    kind='person',
    aliases=['政', '存周'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Entity(
    id='hongloumeng_ent_0145',
    name='宗侄的名帖',
    kind='artifact',
    aliases=['名帖'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0465']
)

Entity(
    id='hongloumeng_ent_0146',
    name='复职候缺',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0468']
)

Entity(
    id='hongloumeng_ent_0147',
    name='金陵应天府',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0469']
)

Entity(
    id='hongloumeng_ent_0148',
    name='轿子',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0471']
)

Entity(
    id='hongloumeng_ent_0149',
    name='敕造宁国府',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0478']
)

Entity(
    id='hongloumeng_ent_0150',
    name='大石狮子',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0476']
)

Entity(
    id='hongloumeng_ent_0151',
    name='垂花门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0485']
)

Entity(
    id='hongloumeng_ent_0152',
    name='紫檀架子大理石的大插屏',
    kind='artifact',
    aliases=['插屏'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0487']
)

Event(
    id='hongloumeng_evt_0095',
    name='张如圭遇贾雨村道喜',
    kind='occurrence',
    participants=['hongloumeng_ent_0139', 'hongloumeng_ent_0037'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0447', 'hongloumeng_seg_0448']
)

Event(
    id='hongloumeng_evt_0096',
    name='冷子兴献计令雨村央烦林如海',
    kind='action',
    participants=['hongloumeng_ent_0089', 'hongloumeng_ent_0037', 'hongloumeng_ent_0079'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0450']
)

Event(
    id='hongloumeng_evt_0097',
    name='雨村面谋林如海',
    kind='action',
    participants=['hongloumeng_ent_0037', 'hongloumeng_ent_0079'],
    time='次日',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0452']
)

Event(
    id='hongloumeng_evt_0098',
    name='黛玉登舟赴都',
    kind='action',
    participants=['hongloumeng_ent_0081'],
    time='出月初二日',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0459', 'hongloumeng_seg_0463']
)

Event(
    id='hongloumeng_evt_0099',
    name='贾政请入相会雨村并协助谋职',
    kind='action',
    participants=['hongloumeng_ent_0104', 'hongloumeng_ent_0037'],
    time='',
    location='荣府',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0466', 'hongloumeng_seg_0467', 'hongloumeng_seg_0468']
)

Event(
    id='hongloumeng_evt_0100',
    name='雨村谋补金陵应天府缺上任',
    kind='state_change',
    participants=['hongloumeng_ent_0037'],
    time='不上两个月',
    location='金陵应天府',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0469']
)

Event(
    id='hongloumeng_evt_0101',
    name='黛玉弃舟登岸乘轿入荣府',
    kind='occurrence',
    participants=['hongloumeng_ent_0081'],
    time='',
    location='荣国府',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0471', 'hongloumeng_seg_0482']
)

Claim(
    id='hongloumeng_clm_0118',
    subject='hongloumeng_ent_0079',
    predicate='said',
    object='hongloumeng_ent_0142',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0453']
)

Claim(
    id='hongloumeng_clm_0119',
    subject='hongloumeng_ent_0143',
    predicate='is',
    object='hongloumeng_ent_0103',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Claim(
    id='hongloumeng_clm_0120',
    subject='hongloumeng_ent_0144',
    predicate='is',
    object='hongloumeng_ent_0104',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Claim(
    id='hongloumeng_clm_0121',
    subject='hongloumeng_ent_0143',
    predicate='is_member_of',
    object='hongloumeng_ent_0090',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Claim(
    id='hongloumeng_clm_0122',
    subject='hongloumeng_ent_0144',
    predicate='is_member_of',
    object='hongloumeng_ent_0090',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Claim(
    id='hongloumeng_clm_0123',
    subject='hongloumeng_ent_0079',
    predicate='is_child_of',
    object='hongloumeng_ent_0096',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0457']
)

Claim(
    id='hongloumeng_clm_0124',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0090',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0462']
)

Claim(
    id='hongloumeng_clm_0125',
    subject='hongloumeng_ent_0104',
    predicate='is_child_of',
    object='hongloumeng_ent_0096',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0467']
)

Relation(
    id='hongloumeng_rel_0076',
    subject='hongloumeng_ent_0143',
    predicate='is',
    object='hongloumeng_ent_0103',
    claim_id='hongloumeng_clm_0119',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0077',
    subject='hongloumeng_ent_0144',
    predicate='is',
    object='hongloumeng_ent_0104',
    claim_id='hongloumeng_clm_0120',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0078',
    subject='hongloumeng_ent_0143',
    predicate='is_member_of',
    object='hongloumeng_ent_0090',
    claim_id='hongloumeng_clm_0121',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0079',
    subject='hongloumeng_ent_0144',
    predicate='is_member_of',
    object='hongloumeng_ent_0090',
    claim_id='hongloumeng_clm_0122',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0080',
    subject='hongloumeng_ent_0079',
    predicate='is_child_of',
    object='hongloumeng_ent_0096',
    claim_id='hongloumeng_clm_0123',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0081',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0090',
    claim_id='hongloumeng_clm_0124',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0082',
    subject='hongloumeng_ent_0104',
    predicate='is_child_of',
    object='hongloumeng_ent_0096',
    claim_id='hongloumeng_clm_0125',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0153',
    name='贾母',
    kind='person',
    aliases=['老母', '外祖母', '史太君', '老祖宗'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0494', 'hongloumeng_seg_0499', 'hongloumeng_seg_0512', 'hongloumeng_seg_0535']
)

Entity(
    id='hongloumeng_ent_0154',
    name='大舅母',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Entity(
    id='hongloumeng_ent_0155',
    name='二舅母',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Entity(
    id='hongloumeng_ent_0156',
    name='珠大嫂子',
    kind='person',
    aliases=['先珠大哥的媳妇'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Entity(
    id='hongloumeng_ent_0157',
    name='贾迎春',
    kind='person',
    aliases=['第一个'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0505']
)

Entity(
    id='hongloumeng_ent_0158',
    name='贾探春',
    kind='person',
    aliases=['第二个'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0506']
)

Entity(
    id='hongloumeng_ent_0159',
    name='贾惜春',
    kind='person',
    aliases=['第三个'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0507']
)

Entity(
    id='hongloumeng_ent_0160',
    name='不足之症',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0515']
)

Entity(
    id='hongloumeng_ent_0161',
    name='癞头和尚',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0518']
)

Entity(
    id='hongloumeng_ent_0162',
    name='人参养荣丸',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0518']
)

Entity(
    id='hongloumeng_ent_0163',
    name='金丝八宝攒珠髻',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0164',
    name='朝阳五凤挂珠钗',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0165',
    name='赤金盘螭璎珞圈',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0166',
    name='双衡比目玫瑰佩',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0167',
    name='缕金百蝶穿花大红洋缎窄褙袄',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0168',
    name='五彩刻丝石青银鼠褂',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Entity(
    id='hongloumeng_ent_0169',
    name='翡翠撒花洋绉裙',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0526']
)

Event(
    id='hongloumeng_evt_0102',
    name='黛玉进贾府见外祖母',
    kind='occurrence',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0153'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0493', 'hongloumeng_seg_0494']
)

Event(
    id='hongloumeng_evt_0103',
    name='贾母搂黛玉痛哭',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0495', 'hongloumeng_seg_0496', 'hongloumeng_seg_0497']
)

Event(
    id='hongloumeng_evt_0104',
    name='黛玉拜见大舅母、二舅母、珠大嫂子',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0154', 'hongloumeng_ent_0155', 'hongloumeng_ent_0156'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500', 'hongloumeng_seg_0501']
)

Event(
    id='hongloumeng_evt_0105',
    name='三姊妹来见黛玉',
    kind='action',
    participants=['hongloumeng_ent_0157', 'hongloumeng_ent_0158', 'hongloumeng_ent_0159', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0504', 'hongloumeng_seg_0509']
)

Event(
    id='hongloumeng_evt_0106',
    name='贾母为贾敏之死伤感',
    kind='occurrence',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0512', 'hongloumeng_seg_0513']
)

Event(
    id='hongloumeng_evt_0107',
    name='众人问黛玉病症',
    kind='action',
    participants=['hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0516']
)

Event(
    id='hongloumeng_evt_0108',
    name='王熙凤出场',
    kind='occurrence',
    participants=['hongloumeng_ent_0135'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0521', 'hongloumeng_seg_0525']
)

Event(
    id='hongloumeng_evt_0109',
    name='王熙凤携黛玉问话',
    kind='action',
    participants=['hongloumeng_ent_0135', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0540', 'hongloumeng_seg_0541']
)

Event(
    id='hongloumeng_evt_0110',
    name='王熙凤吩咐婆子安置黛玉行李随从',
    kind='action',
    participants=['hongloumeng_ent_0135'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0542', 'hongloumeng_seg_0543']
)

Claim(
    id='hongloumeng_clm_0126',
    subject='hongloumeng_ent_0153',
    predicate='is',
    object='hongloumeng_ent_0107',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0499']
)

Claim(
    id='hongloumeng_clm_0127',
    subject='hongloumeng_ent_0153',
    predicate='is_mother_of',
    object='hongloumeng_ent_0103',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0499']
)

Claim(
    id='hongloumeng_clm_0128',
    subject='hongloumeng_ent_0153',
    predicate='is_mother_of',
    object='hongloumeng_ent_0104',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0499']
)

Claim(
    id='hongloumeng_clm_0129',
    subject='hongloumeng_ent_0154',
    predicate='is_wife_of',
    object='hongloumeng_ent_0103',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Claim(
    id='hongloumeng_clm_0130',
    subject='hongloumeng_ent_0155',
    predicate='is_wife_of',
    object='hongloumeng_ent_0104',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Claim(
    id='hongloumeng_clm_0131',
    subject='hongloumeng_ent_0156',
    predicate='is_wife_of',
    object='hongloumeng_ent_0110',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0500']
)

Claim(
    id='hongloumeng_clm_0132',
    subject='hongloumeng_ent_0153',
    predicate='loves_most',
    object='hongloumeng_ent_0132',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0512']
)

Claim(
    id='hongloumeng_clm_0133',
    subject='hongloumeng_ent_0081',
    predicate='has_disease',
    object='hongloumeng_ent_0160',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0515']
)

Claim(
    id='hongloumeng_clm_0134',
    subject='hongloumeng_ent_0081',
    predicate='takes_medicine',
    object='hongloumeng_ent_0162',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0518']
)

Claim(
    id='hongloumeng_clm_0135',
    subject='hongloumeng_ent_0135',
    predicate='is_wife_of',
    object='hongloumeng_ent_0134',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0532']
)

Claim(
    id='hongloumeng_clm_0136',
    subject='hongloumeng_ent_0135',
    predicate='is_niece_of',
    object='hongloumeng_ent_0109',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0532']
)

Claim(
    id='hongloumeng_clm_0137',
    subject='hongloumeng_ent_0134',
    predicate='is_son_of',
    object='hongloumeng_ent_0103',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0532']
)

Relation(
    id='hongloumeng_rel_0083',
    subject='hongloumeng_ent_0153',
    predicate='is',
    object='hongloumeng_ent_0107',
    claim_id='hongloumeng_clm_0126',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0084',
    subject='hongloumeng_ent_0153',
    predicate='is_mother_of',
    object='hongloumeng_ent_0103',
    claim_id='hongloumeng_clm_0127',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0085',
    subject='hongloumeng_ent_0153',
    predicate='is_mother_of',
    object='hongloumeng_ent_0104',
    claim_id='hongloumeng_clm_0128',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0086',
    subject='hongloumeng_ent_0154',
    predicate='is_wife_of',
    object='hongloumeng_ent_0103',
    claim_id='hongloumeng_clm_0129',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0087',
    subject='hongloumeng_ent_0155',
    predicate='is_wife_of',
    object='hongloumeng_ent_0104',
    claim_id='hongloumeng_clm_0130',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0088',
    subject='hongloumeng_ent_0156',
    predicate='is_wife_of',
    object='hongloumeng_ent_0110',
    claim_id='hongloumeng_clm_0131',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0089',
    subject='hongloumeng_ent_0153',
    predicate='loves_most',
    object='hongloumeng_ent_0132',
    claim_id='hongloumeng_clm_0132',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0090',
    subject='hongloumeng_ent_0081',
    predicate='has_disease',
    object='hongloumeng_ent_0160',
    claim_id='hongloumeng_clm_0133',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0091',
    subject='hongloumeng_ent_0081',
    predicate='takes_medicine',
    object='hongloumeng_ent_0162',
    claim_id='hongloumeng_clm_0134',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0092',
    subject='hongloumeng_ent_0135',
    predicate='is_wife_of',
    object='hongloumeng_ent_0134',
    claim_id='hongloumeng_clm_0135',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0093',
    subject='hongloumeng_ent_0135',
    predicate='is_niece_of',
    object='hongloumeng_ent_0109',
    claim_id='hongloumeng_clm_0136',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0094',
    subject='hongloumeng_ent_0134',
    predicate='is_son_of',
    object='hongloumeng_ent_0103',
    claim_id='hongloumeng_clm_0137',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0170',
    name='王夫人',
    kind='person',
    aliases=['太太'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0548', 'hongloumeng_seg_0549']
)

Entity(
    id='hongloumeng_ent_0171',
    name='邢夫人',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0560']
)

Entity(
    id='hongloumeng_ent_0172',
    name='贾赦',
    kind='person',
    aliases=['老爷'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0569', 'hongloumeng_seg_0570']
)

Entity(
    id='hongloumeng_ent_0173',
    name='老嬷嬷',
    kind='person',
    aliases=['两个老嬷嬷', '众嬷嬷', '众婆子们', '嬷嬷', '老嬷嬷们', '两三个嬷嬷'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0556', 'hongloumeng_seg_0581', 'hongloumeng_seg_0564', 'hongloumeng_seg_0600', 'hongloumeng_seg_0577']
)

Entity(
    id='hongloumeng_ent_0174',
    name='小厮',
    kind='person',
    aliases=['众小厮们', '众小厮'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0563']
)

Entity(
    id='hongloumeng_ent_0175',
    name='姬妾丫鬟',
    kind='person',
    aliases=['盛妆丽服之姬妾丫鬟'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0568']
)

Entity(
    id='hongloumeng_ent_0176',
    name='本房内的丫鬟',
    kind='person',
    aliases=['这些丫鬟们', '一个丫鬟'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0602', 'hongloumeng_seg_0603', 'hongloumeng_seg_0604']
)

Entity(
    id='hongloumeng_ent_0177',
    name='后楼',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0548']
)

Entity(
    id='hongloumeng_ent_0178',
    name='穿堂',
    kind='location',
    aliases=['穿堂前', '东西的穿堂'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0562', 'hongloumeng_seg_0581']
)

Entity(
    id='hongloumeng_ent_0179',
    name='垂花门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0563']
)

Entity(
    id='hongloumeng_ent_0180',
    name='西角门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0564']
)

Entity(
    id='hongloumeng_ent_0181',
    name='荣府正门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0564']
)

Entity(
    id='hongloumeng_ent_0182',
    name='黑油大门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0564']
)

Entity(
    id='hongloumeng_ent_0183',
    name='仪门',
    kind='location',
    aliases=['三层仪门', '仪门前'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0564', 'hongloumeng_seg_0567']
)

Entity(
    id='hongloumeng_ent_0184',
    name='贾赦院',
    kind='location',
    aliases=['院中', '正房厢庑游廊', '正室'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0566', 'hongloumeng_seg_0565', 'hongloumeng_seg_0567', 'hongloumeng_seg_0568']
)

Entity(
    id='hongloumeng_ent_0185',
    name='外面书房',
    kind='location',
    aliases=['外面书房中'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0569']
)

Entity(
    id='hongloumeng_ent_0186',
    name='向南大厅',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0581']
)

Entity(
    id='hongloumeng_ent_0187',
    name='大院落',
    kind='location',
    aliases=['仪门内大院落'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0581']
)

Entity(
    id='hongloumeng_ent_0188',
    name='大正房',
    kind='location',
    aliases=['五间大正房', '正经正内室', '正室'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0581', 'hongloumeng_seg_0582', 'hongloumeng_seg_0568']
)

Entity(
    id='hongloumeng_ent_0189',
    name='荣禧堂',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0583']
)

Entity(
    id='hongloumeng_ent_0190',
    name='东边三间耳房',
    kind='location',
    aliases=['正室东边的三间耳房内', '东房门来'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0592', 'hongloumeng_seg_0593']
)

Entity(
    id='hongloumeng_ent_0191',
    name='东廊三间小正房',
    kind='location',
    aliases=['东廊三间小正房内'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0606']
)

Entity(
    id='hongloumeng_ent_0192',
    name='翠幄青紬车',
    kind='artifact',
    aliases=['车', '方才的车'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0563', 'hongloumeng_seg_0577']
)

Entity(
    id='hongloumeng_ent_0193',
    name='驯骡',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0564']
)

Entity(
    id='hongloumeng_ent_0194',
    name='缎子',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0548']
)

Entity(
    id='hongloumeng_ent_0195',
    name='月钱',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0546']
)

Entity(
    id='hongloumeng_ent_0196',
    name='大紫檀雕螭案',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0588']
)

Entity(
    id='hongloumeng_ent_0197',
    name='青绿古铜鼎',
    kind='artifact',
    aliases=['三尺来高青绿古铜鼎'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0588']
)

Entity(
    id='hongloumeng_ent_0198',
    name='待漏随朝墨龙大画',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0588']
)

Entity(
    id='hongloumeng_ent_0199',
    name='金蜼彝',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0588']
)

Entity(
    id='hongloumeng_ent_0200',
    name='玻璃盒',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0588']
)

Entity(
    id='hongloumeng_ent_0201',
    name='楠木交椅',
    kind='artifact',
    aliases=['两溜十六张楠木交椅'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0589']
)

Entity(
    id='hongloumeng_ent_0202',
    name='猩红洋罽',
    kind='artifact',
    aliases=['临窗大炕上猩红洋罽'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0594']
)

Entity(
    id='hongloumeng_ent_0203',
    name='大红金钱蟒靠背',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0594']
)

Entity(
    id='hongloumeng_ent_0204',
    name='石青金钱蟒引枕',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0594']
)

Entity(
    id='hongloumeng_ent_0205',
    name='秋香色金钱蟒大条褥',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0594']
)

Entity(
    id='hongloumeng_ent_0206',
    name='梅花式洋漆小几',
    kind='artifact',
    aliases=['一对梅花式洋漆小几', '一对高几', '几'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0595', 'hongloumeng_seg_0598']
)

Entity(
    id='hongloumeng_ent_0207',
    name='文王鼎',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0596']
)

Entity(
    id='hongloumeng_ent_0208',
    name='汝窑美人觚',
    kind='artifact',
    aliases=['觚'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0596']
)

Entity(
    id='hongloumeng_ent_0209',
    name='银红撒花椅搭',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0597']
)

Entity(
    id='hongloumeng_ent_0210',
    name='半旧的青缎靠背引枕',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0607']
)

Entity(
    id='hongloumeng_ent_0211',
    name='半旧的青缎靠背坐褥',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0608']
)

Entity(
    id='hongloumeng_ent_0212',
    name='万几宸翰之宝',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0587']
)

Entity(
    id='hongloumeng_ent_0213',
    name='荣国公贾源',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0585']
)

Entity(
    id='hongloumeng_ent_0214',
    name='东安郡王穆莳',
    kind='concept',
    aliases=['同乡世教弟勋袭东安郡王穆莳'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0591']
)

Event(
    id='hongloumeng_evt_0111',
    name='熙凤回王夫人月钱已放完且未找到缎子',
    kind='action',
    participants=['hongloumeng_ent_0135', 'hongloumeng_ent_0170'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0547', 'hongloumeng_seg_0548']
)

Event(
    id='hongloumeng_evt_0112',
    name='王夫人吩咐熙凤给黛玉拿缎子裁衣裳',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0135', 'hongloumeng_ent_0081'],
    time='晚上',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0549', 'hongloumeng_seg_0550', 'hongloumeng_seg_0551', 'hongloumeng_seg_0552']
)

Event(
    id='hongloumeng_evt_0113',
    name='熙凤回王夫人已预备下黛玉裁衣裳的缎子',
    kind='action',
    participants=['hongloumeng_ent_0135', 'hongloumeng_ent_0170', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0553', 'hongloumeng_seg_0554']
)

Event(
    id='hongloumeng_evt_0114',
    name='贾母命老嬷嬷带黛玉去见母舅',
    kind='occurrence',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0172', 'hongloumeng_ent_0081'],
    time='当下',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0556']
)

Event(
    id='hongloumeng_evt_0115',
    name='邢夫人带黛玉去见贾赦',
    kind='action',
    participants=['hongloumeng_ent_0171', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0562']
)

Event(
    id='hongloumeng_evt_0116',
    name='邢夫人携黛玉坐车去贾赦院',
    kind='occurrence',
    participants=['hongloumeng_ent_0171', 'hongloumeng_ent_0081', 'hongloumeng_ent_0173', 'hongloumeng_ent_0174'],
    time='',
    location='荣府正门 -> 黑油大门 -> 仪门',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0563', 'hongloumeng_seg_0564', 'hongloumeng_seg_0565']
)

Event(
    id='hongloumeng_evt_0117',
    name='邢夫人让黛玉坐并命人请贾赦',
    kind='occurrence',
    participants=['hongloumeng_ent_0171', 'hongloumeng_ent_0081', 'hongloumeng_ent_0172'],
    time='一时',
    location='贾赦院正室',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0569']
)

Event(
    id='hongloumeng_evt_0118',
    name='贾赦传话不忍相见并劝慰黛玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0172', 'hongloumeng_ent_0081'],
    time='连日',
    location='外面书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0570']
)

Event(
    id='hongloumeng_evt_0119',
    name='黛玉告辞邢夫人欲去拜见二舅舅',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0171'],
    time='',
    location='贾赦院',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0572', 'hongloumeng_seg_0574', 'hongloumeng_seg_0578']
)

Event(
    id='hongloumeng_evt_0120',
    name='邢夫人送黛玉上车去荣府',
    kind='action',
    participants=['hongloumeng_ent_0171', 'hongloumeng_ent_0081', 'hongloumeng_ent_0172'],
    time='',
    location='仪门前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0577', 'hongloumeng_seg_0579']
)

Event(
    id='hongloumeng_evt_0121',
    name='黛玉进荣府下车上东廊三间小正房',
    kind='occurrence',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0172'],
    time='一时',
    location='荣府 -> 向南大厅 -> 大院落 -> 大正房 -> 东边三间耳房 -> 东廊三间小正房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0580', 'hongloumeng_seg_0581', 'hongloumeng_seg_0593', 'hongloumeng_seg_0606']
)

Event(
    id='hongloumeng_evt_0122',
    name='王夫人让黛玉往东坐',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0081'],
    time='',
    location='东廊三间小正房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0609']
)

Claim(
    id='hongloumeng_clm_0138',
    subject='hongloumeng_ent_0135',
    predicate='said',
    object='hongloumeng_ent_0186',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0548']
)

Claim(
    id='hongloumeng_clm_0139',
    subject='hongloumeng_ent_0170',
    predicate='said',
    object='hongloumeng_ent_0135',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0552']
)

Claim(
    id='hongloumeng_clm_0140',
    subject='hongloumeng_ent_0135',
    predicate='owns',
    object='hongloumeng_ent_0186',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0554']
)

Claim(
    id='hongloumeng_clm_0141',
    subject='hongloumeng_ent_0172',
    predicate='said',
    object='hongloumeng_ent_0081',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0570']
)

Claim(
    id='hongloumeng_clm_0142',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0153',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0570']
)

Claim(
    id='hongloumeng_clm_0143',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0171',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0570']
)

Claim(
    id='hongloumeng_clm_0144',
    subject='hongloumeng_ent_0081',
    predicate='is_child_of',
    object='hongloumeng_ent_0172',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0556']
)

Claim(
    id='hongloumeng_clm_0145',
    subject='hongloumeng_ent_0081',
    predicate='is_child_of',
    object='hongloumeng_ent_0104',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0556']
)

Claim(
    id='hongloumeng_clm_0146',
    subject='hongloumeng_ent_0170',
    predicate='lives_in',
    object='hongloumeng_ent_0183',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0592']
)

Claim(
    id='hongloumeng_clm_0147',
    subject='hongloumeng_ent_0170',
    predicate='lives_in',
    object='hongloumeng_ent_0182',
    modality='asserted',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0592']
)

Claim(
    id='hongloumeng_clm_0148',
    subject='hongloumeng_ent_0193',
    predicate='is_member_of',
    object='hongloumeng_ent_0096',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0585']
)

Claim(
    id='hongloumeng_clm_0149',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0180',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0566']
)

Claim(
    id='hongloumeng_clm_0150',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0182',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0582']
)

Claim(
    id='hongloumeng_clm_0151',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0188',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0610']
)

Relation(
    id='hongloumeng_rel_0095',
    subject='hongloumeng_ent_0135',
    predicate='said',
    object='hongloumeng_ent_0186',
    claim_id='hongloumeng_clm_0138',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0096',
    subject='hongloumeng_ent_0170',
    predicate='said',
    object='hongloumeng_ent_0135',
    claim_id='hongloumeng_clm_0139',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0097',
    subject='hongloumeng_ent_0135',
    predicate='owns',
    object='hongloumeng_ent_0186',
    claim_id='hongloumeng_clm_0140',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0098',
    subject='hongloumeng_ent_0172',
    predicate='said',
    object='hongloumeng_ent_0081',
    claim_id='hongloumeng_clm_0141',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0099',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0153',
    claim_id='hongloumeng_clm_0142',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0100',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0171',
    claim_id='hongloumeng_clm_0143',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0101',
    subject='hongloumeng_ent_0081',
    predicate='is_child_of',
    object='hongloumeng_ent_0172',
    claim_id='hongloumeng_clm_0144',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0102',
    subject='hongloumeng_ent_0081',
    predicate='is_child_of',
    object='hongloumeng_ent_0104',
    claim_id='hongloumeng_clm_0145',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0103',
    subject='hongloumeng_ent_0170',
    predicate='lives_in',
    object='hongloumeng_ent_0183',
    claim_id='hongloumeng_clm_0146',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0104',
    subject='hongloumeng_ent_0170',
    predicate='lives_in',
    object='hongloumeng_ent_0182',
    claim_id='hongloumeng_clm_0147',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0105',
    subject='hongloumeng_ent_0193',
    predicate='is_member_of',
    object='hongloumeng_ent_0096',
    claim_id='hongloumeng_clm_0148',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0106',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0180',
    claim_id='hongloumeng_clm_0149',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0107',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0182',
    claim_id='hongloumeng_clm_0150',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0108',
    subject='hongloumeng_ent_0081',
    predicate='thinks',
    object='hongloumeng_ent_0188',
    claim_id='hongloumeng_clm_0151',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0215',
    name='弹墨椅袱',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0611']
)

Entity(
    id='hongloumeng_ent_0216',
    name='炕',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0611']
)

Entity(
    id='hongloumeng_ent_0217',
    name='南北宽夹道',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0621']
)

Entity(
    id='hongloumeng_ent_0218',
    name='倒座三间小小抱厦厅',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0622']
)

Entity(
    id='hongloumeng_ent_0219',
    name='粉油大影壁',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0622']
)

Entity(
    id='hongloumeng_ent_0220',
    name='凤姐姐的屋子',
    kind='location',
    aliases=['小小一所房室'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0622', 'hongloumeng_seg_0623']
)

Entity(
    id='hongloumeng_ent_0221',
    name='拂尘',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0635']
)

Entity(
    id='hongloumeng_ent_0222',
    name='漱盂',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0635']
)

Entity(
    id='hongloumeng_ent_0223',
    name='巾帕',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0635']
)

Entity(
    id='hongloumeng_ent_0224',
    name='小茶盘',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0638']
)

Entity(
    id='hongloumeng_ent_0225',
    name='《四书》',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0646']
)

Entity(
    id='hongloumeng_ent_0226',
    name='束发嵌宝紫金冠',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0227',
    name='二龙抢珠金抹额',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0228',
    name='二色金百蝶穿花大红箭袖',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0229',
    name='五彩丝攒花结长穗宫条',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0230',
    name='石青起花八团倭缎排穗褂',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0231',
    name='青缎粉底小朝靴',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0654']
)

Entity(
    id='hongloumeng_ent_0232',
    name='金螭璎珞',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0657']
)

Entity(
    id='hongloumeng_ent_0233',
    name='五色丝条',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0657']
)

Entity(
    id='hongloumeng_ent_0234',
    name='庙',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0613']
)

Entity(
    id='hongloumeng_ent_0235',
    name='小幺儿',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0618']
)

Entity(
    id='hongloumeng_ent_0236',
    name='李氏',
    kind='person',
    aliases=['李'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0627']
)

Event(
    id='hongloumeng_evt_0123',
    name='黛玉坐椅',
    kind='action',
    participants=['hongloumeng_ent_0081'],
    location='王夫人处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0611']
)

Event(
    id='hongloumeng_evt_0124',
    name='王夫人携黛玉上炕坐',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0081'],
    location='王夫人处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0612']
)

Event(
    id='hongloumeng_evt_0125',
    name='王夫人嘱咐黛玉不要沾惹宝玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0081'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0613']
)

Event(
    id='hongloumeng_evt_0126',
    name='黛玉向王夫人确认表兄是宝玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0170'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0616']
)

Event(
    id='hongloumeng_evt_0127',
    name='王夫人携黛玉去贾母处吃饭',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0081'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0621']
)

Event(
    id='hongloumeng_evt_0128',
    name='贾母等人安设桌椅吃饭',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081', 'hongloumeng_ent_0157', 'hongloumeng_ent_0158', 'hongloumeng_ent_0159', 'hongloumeng_ent_0135', 'hongloumeng_ent_0215'],
    location='贾母后院',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0626', 'hongloumeng_seg_0627', 'hongloumeng_seg_0628']
)

Event(
    id='hongloumeng_evt_0129',
    name='黛玉推让座位后入座',
    kind='action',
    participants=['hongloumeng_ent_0081'],
    location='贾母处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0629', 'hongloumeng_seg_0631']
)

Event(
    id='hongloumeng_evt_0130',
    name='迎春姊妹入座',
    kind='action',
    participants=['hongloumeng_ent_0157', 'hongloumeng_ent_0158', 'hongloumeng_ent_0159'],
    location='贾母处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0633', 'hongloumeng_seg_0634']
)

Event(
    id='hongloumeng_evt_0131',
    name='寂然饭毕上茶',
    kind='occurrence',
    participants=[],
    location='贾母处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0638']
)

Event(
    id='hongloumeng_evt_0132',
    name='黛玉随俗改习惯接茶漱口',
    kind='action',
    participants=['hongloumeng_ent_0081'],
    location='贾母处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0640', 'hongloumeng_seg_0641']
)

Event(
    id='hongloumeng_evt_0133',
    name='王夫人李纨熙凤退下',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0215', 'hongloumeng_ent_0135'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0644']
)

Event(
    id='hongloumeng_evt_0134',
    name='贾母问黛玉念何书',
    kind='occurrence',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0645']
)

Event(
    id='hongloumeng_evt_0135',
    name='黛玉回答念了四书并问姊妹读何书',
    kind='occurrence',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0153'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0646', 'hongloumeng_seg_0647']
)

Event(
    id='hongloumeng_evt_0136',
    name='贾母谦称姊妹们不过认得两个字',
    kind='occurrence',
    participants=['hongloumeng_ent_0153'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0648']
)

Event(
    id='hongloumeng_evt_0137',
    name='宝玉回来拜见贾母',
    kind='occurrence',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0153'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0649', 'hongloumeng_seg_0650', 'hongloumeng_seg_0659']
)

Event(
    id='hongloumeng_evt_0138',
    name='宝玉去见王夫人',
    kind='action',
    participants=['hongloumeng_ent_0111'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0660', 'hongloumeng_seg_0661']
)

Claim(
    id='hongloumeng_clm_0152',
    subject='hongloumeng_ent_0170',
    predicate='said',
    object='hongloumeng_ent_0111',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0613']
)

Claim(
    id='hongloumeng_clm_0153',
    subject='hongloumeng_ent_0111',
    predicate='is_described_as',
    object='hongloumeng_ent_0215',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0613', 'hongloumeng_seg_0614']
)

Claim(
    id='hongloumeng_clm_0154',
    subject='hongloumeng_ent_0111',
    predicate='is_child_of',
    object='hongloumeng_ent_0170',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0614']
)

Claim(
    id='hongloumeng_clm_0155',
    subject='hongloumeng_ent_0111',
    predicate='bears',
    object='hongloumeng_ent_0112',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0614', 'hongloumeng_seg_0616']
)

Claim(
    id='hongloumeng_clm_0156',
    subject='hongloumeng_ent_0153',
    predicate='spoils',
    object='hongloumeng_ent_0111',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0614']
)

Claim(
    id='hongloumeng_clm_0157',
    subject='hongloumeng_ent_0081',
    predicate='is_younger_than',
    object='hongloumeng_ent_0111',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0616']
)

Claim(
    id='hongloumeng_clm_0158',
    subject='hongloumeng_ent_0111',
    predicate='is_pampered_with',
    object='hongloumeng_ent_0129',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0618']
)

Claim(
    id='hongloumeng_clm_0159',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0223',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0623']
)

Claim(
    id='hongloumeng_clm_0160',
    subject='hongloumeng_ent_0081',
    predicate='is_guest_of',
    object='hongloumeng_ent_0153',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0630']
)

Claim(
    id='hongloumeng_clm_0161',
    subject='hongloumeng_ent_0079',
    predicate='taught',
    object='hongloumeng_ent_0081',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0639']
)

Claim(
    id='hongloumeng_clm_0162',
    subject='hongloumeng_ent_0081',
    predicate='has_read',
    object='hongloumeng_ent_0225',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0646']
)

Claim(
    id='hongloumeng_clm_0163',
    subject='hongloumeng_ent_0081',
    predicate='feels_familiar_with',
    object='hongloumeng_ent_0111',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0658']
)

Relation(
    id='hongloumeng_rel_0109',
    subject='hongloumeng_ent_0111',
    predicate='is_child_of',
    object='hongloumeng_ent_0170',
    claim_id='hongloumeng_clm_0156',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0110',
    subject='hongloumeng_ent_0111',
    predicate='bears',
    object='hongloumeng_ent_0112',
    claim_id='hongloumeng_clm_0157',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0111',
    subject='hongloumeng_ent_0153',
    predicate='spoils',
    object='hongloumeng_ent_0111',
    claim_id='hongloumeng_clm_0158',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0112',
    subject='hongloumeng_ent_0081',
    predicate='is_younger_than',
    object='hongloumeng_ent_0111',
    claim_id='hongloumeng_clm_0159',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0113',
    subject='hongloumeng_ent_0081',
    predicate='lives_in',
    object='hongloumeng_ent_0223',
    claim_id='hongloumeng_clm_0161',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0114',
    subject='hongloumeng_ent_0081',
    predicate='is_guest_of',
    object='hongloumeng_ent_0153',
    claim_id='hongloumeng_clm_0162',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0115',
    subject='hongloumeng_ent_0079',
    predicate='taught',
    object='hongloumeng_ent_0081',
    claim_id='hongloumeng_clm_0163',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0116',
    subject='hongloumeng_ent_0081',
    predicate='has_read',
    object='hongloumeng_ent_0225',
    claim_id='hongloumeng_clm_0164',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0117',
    subject='hongloumeng_ent_0081',
    predicate='feels_familiar_with',
    object='hongloumeng_ent_0111',
    claim_id='hongloumeng_clm_0165',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0237',
    name='红丝结束',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0238',
    name='金八宝坠角',
    kind='artifact',
    aliases=['坠角'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0239',
    name='银红撒花半旧大袄',
    kind='artifact',
    aliases=['大袄'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0240',
    name='项圈',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0241',
    name='寄名锁',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0242',
    name='护身符',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0243',
    name='松花撒花绿绫裤腿',
    kind='artifact',
    aliases=['绿绫裤腿'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0244',
    name='锦边弹墨袜',
    kind='artifact',
    aliases=['弹墨袜'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0245',
    name='厚底大红鞋',
    kind='artifact',
    aliases=['大红鞋'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0662']
)

Entity(
    id='hongloumeng_ent_0246',
    name='《古今人物通考》',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0703']
)

Entity(
    id='hongloumeng_ent_0247',
    name='颦颦',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0699']
)

Entity(
    id='hongloumeng_ent_0248',
    name='藕合色花帐',
    kind='artifact',
    aliases=['花帐'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0730']
)

Entity(
    id='hongloumeng_ent_0249',
    name='锦被缎褥',
    kind='artifact',
    aliases=['锦被', '缎褥'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0730']
)

Entity(
    id='hongloumeng_ent_0250',
    name='王嬷嬷',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0731']
)

Entity(
    id='hongloumeng_ent_0251',
    name='雪雁',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0731']
)

Entity(
    id='hongloumeng_ent_0252',
    name='鹦哥',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0732']
)

Entity(
    id='hongloumeng_ent_0253',
    name='碧纱橱',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0724']
)

Entity(
    id='hongloumeng_ent_0254',
    name='套间暖阁儿',
    kind='location',
    aliases=['暖阁儿'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0724']
)

Event(
    id='hongloumeng_evt_0139',
    name='贾母责备宝玉不见客',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0111'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0674', 'hongloumeng_seg_0675']
)

Event(
    id='hongloumeng_evt_0140',
    name='宝玉拜见黛玉',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0676']
)

Event(
    id='hongloumeng_evt_0141',
    name='宝玉细看黛玉容貌',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0677', 'hongloumeng_seg_0678', 'hongloumeng_seg_0679', 'hongloumeng_seg_0680', 'hongloumeng_seg_0681']
)

Event(
    id='hongloumeng_evt_0142',
    name='宝玉称曾见过黛玉',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081', 'hongloumeng_ent_0153'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0682', 'hongloumeng_seg_0683', 'hongloumeng_seg_0684', 'hongloumeng_seg_0685', 'hongloumeng_seg_0686', 'hongloumeng_seg_0687', 'hongloumeng_seg_0688']
)

Event(
    id='hongloumeng_evt_0143',
    name='宝玉问黛玉读书情况',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0689', 'hongloumeng_seg_0690', 'hongloumeng_seg_0691', 'hongloumeng_seg_0692']
)

Event(
    id='hongloumeng_evt_0144',
    name='宝玉问黛玉名字与表字并赠字颦颦',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081', 'hongloumeng_ent_0158'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0693', 'hongloumeng_seg_0694', 'hongloumeng_seg_0695', 'hongloumeng_seg_0696', 'hongloumeng_seg_0697', 'hongloumeng_seg_0698', 'hongloumeng_seg_0699', 'hongloumeng_seg_0700', 'hongloumeng_seg_0701', 'hongloumeng_seg_0702', 'hongloumeng_seg_0703', 'hongloumeng_seg_0704', 'hongloumeng_seg_0705', 'hongloumeng_seg_0706', 'hongloumeng_seg_0707']
)

Event(
    id='hongloumeng_evt_0145',
    name='宝玉问黛玉是否有玉',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0708', 'hongloumeng_seg_0709', 'hongloumeng_seg_0710', 'hongloumeng_seg_0711', 'hongloumeng_seg_0712']
)

Event(
    id='hongloumeng_evt_0146',
    name='宝玉摔玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0112'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0713', 'hongloumeng_seg_0714', 'hongloumeng_seg_0715']
)

Event(
    id='hongloumeng_evt_0147',
    name='贾母哄宝玉带上玉',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0111', 'hongloumeng_ent_0112'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0719', 'hongloumeng_seg_0720', 'hongloumeng_seg_0721', 'hongloumeng_seg_0722']
)

Event(
    id='hongloumeng_evt_0148',
    name='安排黛玉房舍',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081', 'hongloumeng_ent_0111'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0723', 'hongloumeng_seg_0724', 'hongloumeng_seg_0725', 'hongloumeng_seg_0726', 'hongloumeng_seg_0727', 'hongloumeng_seg_0728', 'hongloumeng_seg_0729']
)

Event(
    id='hongloumeng_evt_0149',
    name='熙凤送帐褥给黛玉',
    kind='action',
    participants=['hongloumeng_ent_0135', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0730']
)

Event(
    id='hongloumeng_evt_0150',
    name='贾母将鹦哥赐给黛玉',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0245', 'hongloumeng_ent_0081'],
    time='',
    location='',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0732']
)

Claim(
    id='hongloumeng_clm_0164',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0682']
)

Claim(
    id='hongloumeng_clm_0165',
    subject='hongloumeng_ent_0153',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0684']
)

Claim(
    id='hongloumeng_clm_0166',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0686']
)

Claim(
    id='hongloumeng_clm_0167',
    subject='hongloumeng_ent_0081',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0692']
)

Claim(
    id='hongloumeng_clm_0168',
    subject='hongloumeng_ent_0081',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0697']
)

Claim(
    id='hongloumeng_clm_0169',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0699']
)

Claim(
    id='hongloumeng_clm_0170',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0703']
)

Claim(
    id='hongloumeng_clm_0171',
    subject='hongloumeng_ent_0158',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0705']
)

Claim(
    id='hongloumeng_clm_0172',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0707']
)

Claim(
    id='hongloumeng_clm_0173',
    subject='hongloumeng_ent_0081',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0712']
)

Claim(
    id='hongloumeng_clm_0174',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0714']
)

Claim(
    id='hongloumeng_clm_0175',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0718']
)

Claim(
    id='hongloumeng_clm_0176',
    subject='hongloumeng_ent_0153',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0720']
)

Claim(
    id='hongloumeng_clm_0177',
    subject='hongloumeng_ent_0111',
    predicate='said',
    object='',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0726']
)

Claim(
    id='hongloumeng_clm_0178',
    subject='hongloumeng_ent_0081',
    predicate='owns',
    object='hongloumeng_ent_0243',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0731']
)

Claim(
    id='hongloumeng_clm_0179',
    subject='hongloumeng_ent_0081',
    predicate='owns',
    object='hongloumeng_ent_0244',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0731']
)

Relation(
    id='hongloumeng_rel_0118',
    subject='hongloumeng_ent_0081',
    predicate='owns',
    object='hongloumeng_ent_0243',
    claim_id='hongloumeng_clm_0177',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0119',
    subject='hongloumeng_ent_0081',
    predicate='owns',
    object='hongloumeng_ent_0244',
    claim_id='hongloumeng_clm_0178',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0255',
    name='李嬷嬷',
    kind='person',
    aliases=['宝玉之乳母'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0735']
)

Entity(
    id='hongloumeng_ent_0256',
    name='袭人',
    kind='person',
    aliases=['大丫鬟', '贾母之婢', '珍珠', '花'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0735', 'hongloumeng_seg_0736', 'hongloumeng_seg_0738']
)

Entity(
    id='hongloumeng_ent_0257',
    name='床',
    kind='artifact',
    aliases=['外面大床上', '床沿上'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0735', 'hongloumeng_seg_0745']
)

Entity(
    id='hongloumeng_ent_0258',
    name='旧人诗句',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0738']
)

Entity(
    id='hongloumeng_ent_0259',
    name='花气袭人',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0738']
)

Entity(
    id='hongloumeng_ent_0260',
    name='玉',
    kind='artifact',
    aliases=['那玉'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0746', 'hongloumeng_seg_0750']
)

Entity(
    id='hongloumeng_ent_0261',
    name='王夫人处',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Entity(
    id='hongloumeng_ent_0262',
    name='金陵来的书信',
    kind='artifact',
    aliases=['书信'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Entity(
    id='hongloumeng_ent_0263',
    name='王夫人之兄嫂',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Entity(
    id='hongloumeng_ent_0264',
    name='两个媳妇',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Entity(
    id='hongloumeng_ent_0265',
    name='金陵城',
    kind='location',
    aliases=['金陵'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Entity(
    id='hongloumeng_ent_0266',
    name='薛家姨母',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Entity(
    id='hongloumeng_ent_0267',
    name='薛蟠',
    kind='person',
    aliases=['姨表兄薛蟠', '薛家姨母之子'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Entity(
    id='hongloumeng_ent_0268',
    name='应天府',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Entity(
    id='hongloumeng_ent_0269',
    name='王子腾',
    kind='person',
    aliases=['母舅王子腾'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0758']
)

Event(
    id='hongloumeng_evt_0151',
    name='贾母分配人员服侍黛玉',
    kind='state_change',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0081', 'hongloumeng_ent_0250', 'hongloumeng_ent_0252'],
    time='当下',
    location='碧纱橱内',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0734']
)

Event(
    id='hongloumeng_evt_0152',
    name='袭人陪侍宝玉',
    kind='state_change',
    participants=['hongloumeng_ent_0256', 'hongloumeng_ent_0111', 'hongloumeng_ent_0255'],
    time='当下',
    location='外面大床上',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0735']
)

Event(
    id='hongloumeng_evt_0153',
    name='贾母将袭人给宝玉',
    kind='action',
    participants=['hongloumeng_ent_0153', 'hongloumeng_ent_0256', 'hongloumeng_ent_0111'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0737']
)

Event(
    id='hongloumeng_evt_0154',
    name='宝玉为袭人更名',
    kind='action',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0256', 'hongloumeng_ent_0153'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0738']
)

Event(
    id='hongloumeng_evt_0155',
    name='宝玉李嬷嬷安歇',
    kind='occurrence',
    participants=['hongloumeng_ent_0111', 'hongloumeng_ent_0255'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0741']
)

Event(
    id='hongloumeng_evt_0156',
    name='袭人探望黛玉',
    kind='action',
    participants=['hongloumeng_ent_0256', 'hongloumeng_ent_0081'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0742', 'hongloumeng_seg_0745']
)

Event(
    id='hongloumeng_evt_0157',
    name='黛玉因摔玉之事伤心',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0111', 'hongloumeng_ent_0260'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0746']
)

Event(
    id='hongloumeng_evt_0158',
    name='袭人宽慰黛玉',
    kind='action',
    participants=['hongloumeng_ent_0256', 'hongloumeng_ent_0081'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0748']
)

Event(
    id='hongloumeng_evt_0159',
    name='黛玉询问玉的来历',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0256', 'hongloumeng_ent_0260'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0750']
)

Event(
    id='hongloumeng_evt_0160',
    name='袭人讲述玉的来历',
    kind='action',
    participants=['hongloumeng_ent_0256', 'hongloumeng_ent_0260'],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0752']
)

Event(
    id='hongloumeng_evt_0161',
    name='黛玉阻止袭人拿玉',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0256'],
    time='夜深',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0754']
)

Event(
    id='hongloumeng_evt_0162',
    name='大家安歇',
    kind='occurrence',
    participants=[],
    time='是晚',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0755']
)

Event(
    id='hongloumeng_evt_0163',
    name='黛玉省过贾母',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0153'],
    time='次日',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Event(
    id='hongloumeng_evt_0164',
    name='黛玉往王夫人处',
    kind='action',
    participants=['hongloumeng_ent_0081', 'hongloumeng_ent_0170'],
    time='次日',
    location='王夫人处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Event(
    id='hongloumeng_evt_0165',
    name='王夫人熙凤看书信',
    kind='action',
    participants=['hongloumeng_ent_0170', 'hongloumeng_ent_0135', 'hongloumeng_ent_0262'],
    time='次日',
    location='王夫人处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Event(
    id='hongloumeng_evt_0166',
    name='王夫人兄嫂遣人来说话',
    kind='occurrence',
    participants=['hongloumeng_ent_0263', 'hongloumeng_ent_0264'],
    time='次日',
    location='王夫人处',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0756']
)

Event(
    id='hongloumeng_evt_0167',
    name='薛蟠打死人命',
    kind='occurrence',
    participants=['hongloumeng_ent_0267'],
    location='金陵城',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Event(
    id='hongloumeng_evt_0168',
    name='薛蟠案下审理',
    kind='state_change',
    participants=['hongloumeng_ent_0267'],
    location='应天府',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Event(
    id='hongloumeng_evt_0169',
    name='王子腾遣人告诉这边',
    kind='action',
    participants=['hongloumeng_ent_0269'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0758']
)

Claim(
    id='hongloumeng_clm_0180',
    subject='hongloumeng_ent_0256',
    predicate='is',
    object='hongloumeng_ent_0256',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0736']
)

Claim(
    id='hongloumeng_clm_0181',
    subject='hongloumeng_ent_0256',
    predicate='formerly_named',
    object='hongloumeng_ent_0256',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0736']
)

Claim(
    id='hongloumeng_clm_0182',
    subject='hongloumeng_ent_0153',
    predicate='fears',
    object='hongloumeng_ent_0111',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0737']
)

Claim(
    id='hongloumeng_clm_0183',
    subject='hongloumeng_ent_0153',
    predicate='gives',
    object='hongloumeng_ent_0256',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0737']
)

Claim(
    id='hongloumeng_clm_0184',
    subject='hongloumeng_ent_0111',
    predicate='renames',
    object='hongloumeng_ent_0256',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0738']
)

Claim(
    id='hongloumeng_clm_0185',
    subject='hongloumeng_ent_0256',
    predicate='serves',
    object='hongloumeng_ent_0153',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0739']
)

Claim(
    id='hongloumeng_clm_0186',
    subject='hongloumeng_ent_0256',
    predicate='serves',
    object='hongloumeng_ent_0111',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0739']
)

Claim(
    id='hongloumeng_clm_0187',
    subject='hongloumeng_ent_0256',
    predicate='feels',
    object='hongloumeng_ent_0111',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0740']
)

Claim(
    id='hongloumeng_clm_0188',
    subject='hongloumeng_ent_0081',
    predicate='feels_guilty_about',
    object='hongloumeng_ent_0111',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0746']
)

Claim(
    id='hongloumeng_clm_0189',
    subject='hongloumeng_ent_0260',
    predicate='originated_from',
    object='hongloumeng_ent_0111',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0752']
)

Claim(
    id='hongloumeng_clm_0190',
    subject='hongloumeng_ent_0267',
    predicate='is_child_of',
    object='hongloumeng_ent_0266',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Claim(
    id='hongloumeng_clm_0191',
    subject='hongloumeng_ent_0267',
    predicate='is_cousin_of',
    object='hongloumeng_ent_0081',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0757']
)

Claim(
    id='hongloumeng_clm_0192',
    subject='hongloumeng_ent_0269',
    predicate='is_uncle_of',
    object='hongloumeng_ent_0170',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0758']
)

Relation(
    id='hongloumeng_rel_0120',
    subject='hongloumeng_ent_0256',
    predicate='is',
    object='hongloumeng_ent_0256',
    claim_id='hongloumeng_clm_0180',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0121',
    subject='hongloumeng_ent_0153',
    predicate='gives',
    object='hongloumeng_ent_0256',
    claim_id='hongloumeng_clm_0183',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0122',
    subject='hongloumeng_ent_0111',
    predicate='renames',
    object='hongloumeng_ent_0256',
    claim_id='hongloumeng_clm_0184',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0123',
    subject='hongloumeng_ent_0256',
    predicate='serves',
    object='hongloumeng_ent_0153',
    claim_id='hongloumeng_clm_0185',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0124',
    subject='hongloumeng_ent_0256',
    predicate='serves',
    object='hongloumeng_ent_0111',
    claim_id='hongloumeng_clm_0186',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0125',
    subject='hongloumeng_ent_0260',
    predicate='originated_from',
    object='hongloumeng_ent_0111',
    claim_id='hongloumeng_clm_0189',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0126',
    subject='hongloumeng_ent_0267',
    predicate='is_child_of',
    object='hongloumeng_ent_0266',
    claim_id='hongloumeng_clm_0190',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0127',
    subject='hongloumeng_ent_0267',
    predicate='is_cousin_of',
    object='hongloumeng_ent_0081',
    claim_id='hongloumeng_clm_0191',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0128',
    subject='hongloumeng_ent_0269',
    predicate='is_uncle_of',
    object='hongloumeng_ent_0170',
    claim_id='hongloumeng_clm_0192',
    evidence_refs=[]
)

