# Auto-generated by t2c v3.4-flash — DO NOT EDIT
from t2c.ontology import Claim, Entity, Event, EvidenceRef, IgnoreSegment, Relation

Entity(
    id='hongloumeng_ent_0001',
    name='甄士隐',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0001', start=5, end=8, quote_hash='sha256:ae447e11053b82fb15ffb75ebd9a9b4f8b0c3308dbe5e573ab2498bfffd57116')],
    source_segment_ids=['hongloumeng_seg_0001']
)

Entity(
    id='hongloumeng_ent_0002',
    name='贾雨村',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0001', start=14, end=17, quote_hash='sha256:72bcfb98fe0d35996d4fdc36fad3ac25ec1ce8b582672abdfe2c7f5372c90764')],
    source_segment_ids=['hongloumeng_seg_0001']
)

Entity(
    id='hongloumeng_ent_0003',
    name='女娲氏',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0005', start=2, end=5, quote_hash='sha256:9e52df007f6050a518a827110d873fd45b2b0d5d2de75845231d3f85a499edd1')],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0006']
)

Entity(
    id='hongloumeng_ent_0004',
    name='石头',
    kind='artifact',
    aliases=['顽石'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0005', start=33, end=35, quote_hash='sha256:70e3b3c4f322ce00579cc4f05cd33e54393db680817ae440addd3e9ebb81d7a1')],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0006', 'hongloumeng_seg_0007', 'hongloumeng_seg_0009', 'hongloumeng_seg_0019', 'hongloumeng_seg_0026', 'hongloumeng_seg_0027']
)

Entity(
    id='hongloumeng_ent_0005',
    name='僧',
    kind='person',
    aliases=['茫茫大士', '二仙师'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0008', start=12, end=16, quote_hash='sha256:a00d05adcacc5b1ff2eaeb8d8c9556d77d6f8201474d681a31c5dd5e9188bd7d')],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0016', 'hongloumeng_seg_0019', 'hongloumeng_seg_0023', 'hongloumeng_seg_0027', 'hongloumeng_seg_0010']
)

Entity(
    id='hongloumeng_ent_0006',
    name='道人',
    kind='person',
    aliases=['渺渺真人', '二仙师'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0008', start=14, end=16, quote_hash='sha256:7bed704e45e7deee745ab54e541c5284fc3e00d94a4a59a078c0d8cfb965cb98')],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0025', 'hongloumeng_seg_0027', 'hongloumeng_seg_0010']
)

Entity(
    id='hongloumeng_ent_0007',
    name='美玉',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0019', start=24, end=31, quote_hash='sha256:20a7294df4f6669ece5eaf77ec95f88b06e085903f81a5276e3577cd0a700199')],
    source_segment_ids=['hongloumeng_seg_0019', 'hongloumeng_seg_0020']
)

Entity(
    id='hongloumeng_ent_0008',
    name='空空道人',
    kind='person',
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0026', start=15, end=19, quote_hash='sha256:8eb932a39270b2dd7fc1e5219291273f7bf95a7445a6b21301f70d68d63c743f'),
        EvidenceRef(segment_id='hongloumeng_seg_0027', start=0, end=4, quote_hash='sha256:8eb932a39270b2dd7fc1e5219291273f7bf95a7445a6b21301f70d68d63c743f'),
        EvidenceRef(segment_id='hongloumeng_seg_0032', start=0, end=4, quote_hash='sha256:8eb932a39270b2dd7fc1e5219291273f7bf95a7445a6b21301f70d68d63c743f')
    ],
    source_segment_ids=['hongloumeng_seg_0026', 'hongloumeng_seg_0027', 'hongloumeng_seg_0032']
)

Entity(
    id='hongloumeng_ent_0009',
    name='大荒山',
    kind='location',
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0005', start=13, end=16, quote_hash='sha256:dd6a319cf0883331d99aa6fe3e534f847522469b8890214cfeac20b31499121e'),
        EvidenceRef(segment_id='hongloumeng_seg_0026', start=26, end=29, quote_hash='sha256:dd6a319cf0883331d99aa6fe3e534f847522469b8890214cfeac20b31499121e')
    ],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0026']
)

Entity(
    id='hongloumeng_ent_0010',
    name='无稽崖',
    kind='location',
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0005', start=16, end=19, quote_hash='sha256:765feb73d980f3de1afcaf9963762f8e31902b1fab6caa322b8fef138983ed1d'),
        EvidenceRef(segment_id='hongloumeng_seg_0026', start=29, end=32, quote_hash='sha256:765feb73d980f3de1afcaf9963762f8e31902b1fab6caa322b8fef138983ed1d')
    ],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0026']
)

Entity(
    id='hongloumeng_ent_0011',
    name='青埂峰',
    kind='location',
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0006', start=29, end=32, quote_hash='sha256:a7e55076bd4a3f007dcd83f7d27d3db3328726035811e960810fdc5db31461b1'),
        EvidenceRef(segment_id='hongloumeng_seg_0026', start=32, end=35, quote_hash='sha256:a7e55076bd4a3f007dcd83f7d27d3db3328726035811e960810fdc5db31461b1')
    ],
    source_segment_ids=['hongloumeng_seg_0006', 'hongloumeng_seg_0026']
)

Event(
    id='hongloumeng_evt_0001',
    name='女娲炼石补天',
    kind='occurrence',
    participants=['hongloumeng_ent_0003'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0005', start=2, end=9, quote_hash='sha256:77d4e684fff1f70d97118b560c27c204874fd807d53c8d1647aed55f033fb078')],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0006']
)

Event(
    id='hongloumeng_evt_0002',
    name='石头被弃青埂峰下',
    kind='occurrence',
    participants=['hongloumeng_ent_0003', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0006', start=25, end=33, quote_hash='sha256:9a4db36cec0f7ac97d8d9a271da64d197df06e37aaaf63e31d3fdc6a3123842c')],
    source_segment_ids=['hongloumeng_seg_0006']
)

Event(
    id='hongloumeng_evt_0003',
    name='僧道来至峰下',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0008', start=12, end=20, quote_hash='sha256:60c534a3804a56031e9a133a3bda8a2c92be92182dcc1cbf3362d54232e32ef8')],
    source_segment_ids=['hongloumeng_seg_0008']
)

Event(
    id='hongloumeng_evt_0004',
    name='石头苦求入红尘',
    kind='occurrence',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0012', start=18, end=22, quote_hash='sha256:949b11f38b313332d9f24ca3dfd476b5b849d33629573edef5b30ca9dc4440d2')],
    source_segment_ids=['hongloumeng_seg_0009', 'hongloumeng_seg_0012']
)

Event(
    id='hongloumeng_evt_0005',
    name='僧念咒将石头变美玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0004', 'hongloumeng_ent_0007'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0019', start=13, end=31, quote_hash='sha256:32b969091b1e138a3dfdffc39e333126f1f114f9dc27a104c42dab1c4254ffac')],
    source_segment_ids=['hongloumeng_seg_0019']
)

Event(
    id='hongloumeng_evt_0006',
    name='僧道携石飘然而去',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0025', start=3, end=17, quote_hash='sha256:a0179be7485bf115097e87ec80310582be96eddbbee03c30386531f09a19c906')],
    source_segment_ids=['hongloumeng_seg_0025']
)

Event(
    id='hongloumeng_evt_0007',
    name='空空道人见石上字迹',
    kind='occurrence',
    participants=['hongloumeng_ent_0008', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0026', start=39, end=50, quote_hash='sha256:c06dbbfd0fadddde1aef62eac833b042f5d6e25365ffa7c9d313097224437860')],
    source_segment_ids=['hongloumeng_seg_0026', 'hongloumeng_seg_0027']
)

IgnoreSegment(id='hongloumeng_ign_0001', segment_id='hongloumeng_seg_0002', reason='narrator framing', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0002', segment_id='hongloumeng_seg_0003', reason='narrator commentary', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0003', segment_id='hongloumeng_seg_0004', reason='narrator commentary', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0004', segment_id='hongloumeng_seg_0028', reason='poem verse', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0005', segment_id='hongloumeng_seg_0029', reason='poem verse', evidence_refs=[])

Entity(
    id='hongloumeng_ent_0001',
    name='封氏',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0050', start=0, end=4, quote_hash='sha256:24f3dea0ba3f29bcbc7bb10f6c6a48f123ea1adc7aa162b9c84eeff55f58f08c')],
    source_segment_ids=['hongloumeng_seg_0050']
)

Entity(
    id='hongloumeng_ent_0002',
    name='玉峰',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0041', start=0, end=9, quote_hash='sha256:c5027ddbef0b67fba1bb97cb90d3e836ff1ab880e76d9593f34fd86068989e5b')],
    source_segment_ids=['hongloumeng_seg_0041']
)

Entity(
    id='hongloumeng_ent_0003',
    name='孔梅溪',
    kind='person',
    aliases=['东鲁孔梅溪'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0042', start=0, end=14, quote_hash='sha256:f8fe58ec783c558e17acf140de30411a2dae84987dd2d42c4c43bea558af94d5')],
    source_segment_ids=['hongloumeng_seg_0042']
)

Entity(
    id='hongloumeng_ent_0004',
    name='脂砚斋',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0045', start=1, end=10, quote_hash='sha256:675f4077bfb709fec5dfd1ccad7b3a41d06c8cea15d48c0a30a9c4d285328e9f')],
    source_segment_ids=['hongloumeng_seg_0045']
)

Entity(
    id='hongloumeng_ent_0005',
    name='姑苏',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0047', start=12, end=17, quote_hash='sha256:7775d68f5a67a16e962fe6463726d3c4d4e1420cc0d268ea037adc0083ec00e4')],
    source_segment_ids=['hongloumeng_seg_0047']
)

Entity(
    id='hongloumeng_ent_0006',
    name='阊门',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0047', start=18, end=24, quote_hash='sha256:188243f7e18c626e382408706eb0bf754eb815f90ea65e382dad513d24c94315')],
    source_segment_ids=['hongloumeng_seg_0047', 'hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0007',
    name='十里街',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0048', start=4, end=9, quote_hash='sha256:d29deee38b12006bdab843f2b06ae6641fe95a21a26ed22f841b5df5b38e99d0')],
    source_segment_ids=['hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0008',
    name='仁清巷',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0048', start=12, end=17, quote_hash='sha256:ac06c1bba37e20983f412a78a74445a283893ae2ca8d5c96469aab546f5a3795')],
    source_segment_ids=['hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0009',
    name='葫芦庙',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0048', start=31, end=38, quote_hash='sha256:2e00607b85d159fbc2d89c8974115c5ca4a0940d3795ffa9b6805767a48dc949')],
    source_segment_ids=['hongloumeng_seg_0048', 'hongloumeng_seg_0049']
)

Entity(
    id='hongloumeng_ent_0010',
    name='《石头记》',
    kind='artifact',
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0036', start=17, end=22, quote_hash='sha256:b53df08de120a527823f02420f54afcb65f4d67556ccadd696915187a71511c5'),
        EvidenceRef(segment_id='hongloumeng_seg_0039', start=32, end=37, quote_hash='sha256:b53df08de120a527823f02420f54afcb65f4d67556ccadd696915187a71511c5'),
        EvidenceRef(segment_id='hongloumeng_seg_0045', start=13, end=18, quote_hash='sha256:b53df08de120a527823f02420f54afcb65f4d67556ccadd696915187a71511c5')
    ],
    source_segment_ids=['hongloumeng_seg_0033', 'hongloumeng_seg_0036', 'hongloumeng_seg_0039', 'hongloumeng_seg_0045']
)

Entity(
    id='hongloumeng_ent_0011',
    name='《情僧录》',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0039', start=38, end=43, quote_hash='sha256:75941b55c80d4b18a0b306500f293bfe8121b153d0c3bbe244d09b3029025081')],
    source_segment_ids=['hongloumeng_seg_0039']
)

Entity(
    id='hongloumeng_ent_0012',
    name='《红楼梦》',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0041', start=4, end=9, quote_hash='sha256:17d37dd963e43a7534e796b33f9f963fae5ccc79e96294fb2f359a89a4c1abf3')],
    source_segment_ids=['hongloumeng_seg_0041']
)

Entity(
    id='hongloumeng_ent_0013',
    name='《风月宝鉴》',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0042', start=8, end=14, quote_hash='sha256:f1bb558e8f7aabc596131283fb30417064835e8314e8323d159661ecbfc139e9')],
    source_segment_ids=['hongloumeng_seg_0042']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0008',
    predicate='contains',
    object='hongloumeng_ent_0009',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0048', start=18, end=24, quote_hash='sha256:35dd97da0cd68f700aabf84d6815407ba0d2854d0852fa627be0befcbfffd6fe')],
    source_segment_ids=['hongloumeng_seg_0048']
)

Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0008',
    predicate='renamed_to',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0039', start=20, end=30, quote_hash='sha256:6f1ba9b7fe9462d87d8fad4b920d6a2a63a6e80b2c45d0a69e2765359e6abfe1')],
    source_segment_ids=['hongloumeng_seg_0039']
)

Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0010',
    predicate='renamed_to',
    object='hongloumeng_ent_0011',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0039', start=31, end=43, quote_hash='sha256:7f5e5cc8acaf812a8672ef95b4deba5661fcd31183f26f3f29f988c9e71dd067')],
    source_segment_ids=['hongloumeng_seg_0039']
)

Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0002',
    predicate='titled',
    object='hongloumeng_ent_0012',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0041', start=0, end=9, quote_hash='sha256:c5027ddbef0b67fba1bb97cb90d3e836ff1ab880e76d9593f34fd86068989e5b')],
    source_segment_ids=['hongloumeng_seg_0041']
)

Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0003',
    predicate='titled',
    object='hongloumeng_ent_0013',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0042', start=2, end=14, quote_hash='sha256:29dafc19f0df0717d43bbc49163c16e7633c33261b83252f278ac5910af90af8')],
    source_segment_ids=['hongloumeng_seg_0042']
)

Event(
    id='hongloumeng_evt_0001',
    name='石头与空空道人论石头记',
    kind='occurrence',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0008'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0034', start=0, end=5, quote_hash='sha256:8577d4fed0a177d6305c1327502d3bbf658edd88ab939a929925af67a7a2ca8e')],
    source_segment_ids=['hongloumeng_seg_0033', 'hongloumeng_seg_0034', 'hongloumeng_seg_0035']
)

Event(
    id='hongloumeng_evt_0002',
    name='空空道人抄录石头记',
    kind='occurrence',
    participants=['hongloumeng_ent_0008'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0038', start=9, end=17, quote_hash='sha256:34f634121702feafdc20b6a445582db1cc894d74039a890f8e0439a76b38a701')],
    source_segment_ids=['hongloumeng_seg_0036', 'hongloumeng_seg_0038']
)

Event(
    id='hongloumeng_evt_0003',
    name='空空道人改名情僧并改书名',
    kind='occurrence',
    participants=['hongloumeng_ent_0008'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0039', start=20, end=30, quote_hash='sha256:6f1ba9b7fe9462d87d8fad4b920d6a2a63a6e80b2c45d0a69e2765359e6abfe1')],
    source_segment_ids=['hongloumeng_seg_0039']
)

Event(
    id='hongloumeng_evt_0004',
    name='脂砚斋评石头记',
    kind='occurrence',
    participants=['hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0045', start=1, end=10, quote_hash='sha256:675f4077bfb709fec5dfd1ccad7b3a41d06c8cea15d48c0a30a9c4d285328e9f')],
    source_segment_ids=['hongloumeng_seg_0045']
)

IgnoreSegment(id='hongloumeng_ign_0001', segment_id='hongloumeng_seg_0040', reason='残缺文本（‘至?’）', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0002', segment_id='hongloumeng_seg_0043', reason='开卷题诗，属文学修辞', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0003', segment_id='hongloumeng_seg_0044', reason='开卷题诗，属文学修辞', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0004', segment_id='hongloumeng_seg_0046', reason='过渡性叙述文字', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0005', segment_id='hongloumeng_seg_0037', reason='对书旨的总括陈述，无新实体/事件', evidence_refs=[])

Relation(
    id='hongloumeng_rel_0005',
    subject='hongloumeng_ent_0008',
    predicate='contains',
    object='hongloumeng_ent_0009',
    claim_id='hongloumeng_clm_0007',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0048', start=18, end=24, quote_hash='sha256:35dd97da0cd68f700aabf84d6815407ba0d2854d0852fa627be0befcbfffd6fe')]
)

Relation(
    id='hongloumeng_rel_0006',
    subject='hongloumeng_ent_0010',
    predicate='renamed_to',
    object='hongloumeng_ent_0011',
    claim_id='hongloumeng_clm_0009',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0039', start=31, end=43, quote_hash='sha256:7f5e5cc8acaf812a8672ef95b4deba5661fcd31183f26f3f29f988c9e71dd067')]
)

Relation(
    id='hongloumeng_rel_0007',
    subject='hongloumeng_ent_0002',
    predicate='titled',
    object='hongloumeng_ent_0012',
    claim_id='hongloumeng_clm_0010',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0041', start=0, end=9, quote_hash='sha256:c5027ddbef0b67fba1bb97cb90d3e836ff1ab880e76d9593f34fd86068989e5b')]
)

Relation(
    id='hongloumeng_rel_0008',
    subject='hongloumeng_ent_0003',
    predicate='titled',
    object='hongloumeng_ent_0013',
    claim_id='hongloumeng_clm_0011',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0042', start=2, end=14, quote_hash='sha256:29dafc19f0df0717d43bbc49163c16e7633c33261b83252f278ac5910af90af8')]
)

Entity(
    id='hongloumeng_ent_0001',
    name='英莲',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0053']
)

Entity(
    id='hongloumeng_ent_0002',
    name='警幻仙子',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0003',
    name='绛珠仙子',
    kind='person',
    aliases=['绛珠草'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0004',
    name='神瑛侍者',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0005',
    name='太虚幻境',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0090', 'hongloumeng_seg_0091']
)

Entity(
    id='hongloumeng_ent_0006',
    name='灵河',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0007',
    name='三生石',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0001',
    name='甄士隐入梦',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0054', start=29, end=33, quote_hash='sha256:4e018f83ef879330f412e94b21f38b511ed20a92aa05cd19087e485bff995616')],
    source_segment_ids=['hongloumeng_seg_0054', 'hongloumeng_seg_0055']
)

Event(
    id='hongloumeng_evt_0002',
    name='僧道论还泪公案',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0056', 'hongloumeng_seg_0073']
)

Event(
    id='hongloumeng_evt_0003',
    name='士隐观通灵宝玉',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0005', 'hongloumeng_ent_0007'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0084', 'hongloumeng_seg_0088']
)

Event(
    id='hongloumeng_evt_0004',
    name='士隐欲随入太虚幻境',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0094', start=15, end=21, quote_hash='sha256:f046c182129a2f74035f0d62831709dcdcfeeb27d4cb6d63f30734d2c3e9e98d')],
    source_segment_ids=['hongloumeng_seg_0090', 'hongloumeng_seg_0094']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0007',
    predicate='inscribed_with',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0087', 'hongloumeng_seg_0088']
)

Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0005',
    predicate='couplet',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0093', start=0, end=7, quote_hash='sha256:79c70cfd5a43fe5c1d7c346ab4104c7308a697fad3247652dbd2eb7ee7c8d903')],
    source_segment_ids=['hongloumeng_seg_0093']
)

Entity(
    id='hongloumeng_ent_0001',
    name='奶母',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0096', start=2, end=4, quote_hash='sha256:a7b751a1a17f5bdff3e601934856936c763638dade990e2bf807be5a2206b290')],
    source_segment_ids=['hongloumeng_seg_0096']
)

Entity(
    id='hongloumeng_ent_0002',
    name='严老爷',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0120', start=1, end=6, quote_hash='sha256:1009cacd874acda4e04d493ad8144e83dbab020356c569f1b2cb6b761b0a4b51')],
    source_segment_ids=['hongloumeng_seg_0120']
)

Entity(
    id='hongloumeng_ent_0003',
    name='甄家丫鬟',
    kind='person',
    aliases=['丫鬟'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0127', start=25, end=29, quote_hash='sha256:2cc50b91e4182dd689e67e878b9f8bfcb1126d57ba45e5d63884efbd9f36241f')],
    source_segment_ids=['hongloumeng_seg_0127', 'hongloumeng_seg_0130']
)

Entity(
    id='hongloumeng_ent_0004',
    name='胡州',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0113', start=6, end=10, quote_hash='sha256:93d1e614c8b822111596b6f3f50f7cb5cd3f18386b957135ea8701cd539e8123')],
    source_segment_ids=['hongloumeng_seg_0113']
)

Entity(
    id='hongloumeng_ent_0005',
    name='北邙山',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0107', start=26, end=29, quote_hash='sha256:f922a12a54e7a7c0d919054e901b6c241eed3b1e6ffacd168aaf9e02f8f080fc')],
    source_segment_ids=['hongloumeng_seg_0107']
)

Event(
    id='hongloumeng_evt_0001',
    name='士隐梦醒抱英莲看热闹',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0095', start=2, end=6, quote_hash='sha256:717047e2fcca20d3fb16ca0ff1ebf212419e2a0e19712ecaabd06adc45f23ba3')],
    source_segment_ids=['hongloumeng_seg_0095', 'hongloumeng_seg_0096', 'hongloumeng_seg_0097']
)

Event(
    id='hongloumeng_evt_0002',
    name='僧道出现',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0098', start=13, end=17, quote_hash='sha256:a00d05adcacc5b1ff2eaeb8d8c9556d77d6f8201474d681a31c5dd5e9188bd7d')],
    source_segment_ids=['hongloumeng_seg_0098', 'hongloumeng_seg_0099']
)

Event(
    id='hongloumeng_evt_0003',
    name='僧人向士隐索要英莲并念预言诗',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0102', start=1, end=4, quote_hash='sha256:e53c6201ba916fa9298ee0daf8c0e5e60cfe770d4550eb22b7820c55e2f08de7')],
    source_segment_ids=['hongloumeng_seg_0100', 'hongloumeng_seg_0102', 'hongloumeng_seg_0103', 'hongloumeng_seg_0104', 'hongloumeng_seg_0105']
)

Event(
    id='hongloumeng_evt_0004',
    name='僧道分手相约北邙山',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0107', start=8, end=12, quote_hash='sha256:cf5ec86cad933e80391d2f45860d7f6a925a48fe401f875c09aa60f82fde5273')],
    source_segment_ids=['hongloumeng_seg_0107', 'hongloumeng_seg_0108', 'hongloumeng_seg_0109', 'hongloumeng_seg_0110']
)

Event(
    id='hongloumeng_evt_0005',
    name='贾雨村出场并自我介绍',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0112', start=23, end=27, quote_hash='sha256:11959e3e6e5574ee1b1f671230ee7e662fef4673691b2f9e7aca809b1dd151f8')],
    source_segment_ids=['hongloumeng_seg_0112', 'hongloumeng_seg_0113', 'hongloumeng_seg_0114']
)

Event(
    id='hongloumeng_evt_0006',
    name='士隐邀雨村入书房',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0117', start=31, end=37, quote_hash='sha256:41b6c6a12ca3424891010c7938c542071dc625b412c9c21316b3b0d0900f9fcb')],
    source_segment_ids=['hongloumeng_seg_0115', 'hongloumeng_seg_0116', 'hongloumeng_seg_0117', 'hongloumeng_seg_0118', 'hongloumeng_seg_0119']
)

Event(
    id='hongloumeng_evt_0007',
    name='严老爷来拜访士隐出迎',
    kind='occurrence',
    participants=['hongloumeng_ent_0002', 'hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0120', start=1, end=6, quote_hash='sha256:1009cacd874acda4e04d493ad8144e83dbab020356c569f1b2cb6b761b0a4b51')],
    source_segment_ids=['hongloumeng_seg_0120', 'hongloumeng_seg_0121', 'hongloumeng_seg_0122', 'hongloumeng_seg_0123', 'hongloumeng_seg_0124', 'hongloumeng_seg_0125']
)

Event(
    id='hongloumeng_evt_0008',
    name='丫鬟撷花雨村窗外观看',
    kind='occurrence',
    participants=['hongloumeng_ent_0003', 'hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0127', start=33, end=35, quote_hash='sha256:8dce005ae39e48e310453483cce5ba35c74e0cd698225c8a9b47fbd461910f20')],
    source_segment_ids=['hongloumeng_seg_0127', 'hongloumeng_seg_0128', 'hongloumeng_seg_0129', 'hongloumeng_seg_0130', 'hongloumeng_seg_0131', 'hongloumeng_seg_0132', 'hongloumeng_seg_0133', 'hongloumeng_seg_0134', 'hongloumeng_seg_0135']
)

Event(
    id='hongloumeng_evt_0009',
    name='雨村离开士隐家',
    kind='occurrence',
    participants=['hongloumeng_ent_0002', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0136', start=30, end=34, quote_hash='sha256:5749a2b3ab948fda0586c1ab9168b8a4945a6722156202c094105cdc41fbb5df')],
    source_segment_ids=['hongloumeng_seg_0136', 'hongloumeng_seg_0137']
)

Event(
    id='hongloumeng_evt_0010',
    name='中秋士隐邀雨村',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0138', start=5, end=9, quote_hash='sha256:482fad0460ad8d3280ce6b72dcde76a25ef5bf33b5adaffc7039f04fcd8a41d3')],
    source_segment_ids=['hongloumeng_seg_0138', 'hongloumeng_seg_0139']
)

Event(
    id='hongloumeng_evt_0011',
    name='雨村中秋赋诗',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0141', start=6, end=11, quote_hash='sha256:2db89a04db28280bc95cd1980b261c61949ab40fa9d8ae5fea46f1b29707dfc9')],
    source_segment_ids=['hongloumeng_seg_0140', 'hongloumeng_seg_0141', 'hongloumeng_seg_0142', 'hongloumeng_seg_0143', 'hongloumeng_seg_0144']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0002',
    predicate='居住地',
    object='hongloumeng_ent_0009',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0112', start=11, end=17, quote_hash='sha256:d7fd18c7a1dd32ec8b7d052ee3ef15e2283c13f7f27c4ff2199754ebf78380b5')],
    source_segment_ids=['hongloumeng_seg_0112', 'hongloumeng_seg_0114']
)

Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0002',
    predicate='生计',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0114', start=21, end=27, quote_hash='sha256:e96b5422d1ec8f2d6f43486b39058cb740ed8ed7b533808ee8358d8c788dc8bd')],
    source_segment_ids=['hongloumeng_seg_0114']
)

Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0001',
    predicate='交往',
    object='hongloumeng_ent_0002',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0114', start=29, end=36, quote_hash='sha256:bb44160d8999a809c896065c65da490f6ed8a6ac985bc4cb4f6db5254cc12f02')],
    source_segment_ids=['hongloumeng_seg_0114']
)

Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0001',
    predicate='外貌',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0097', start=9, end=13, quote_hash='sha256:40df1d472826b77510651232b41f783b469a4319e75024c251d08e781e62f1d7')],
    source_segment_ids=['hongloumeng_seg_0097']
)

Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0003',
    predicate='外貌',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0128', start=2, end=6, quote_hash='sha256:5b19c5c0fef62d6a2299039a699a9b6d6a2e32ba52ec99442b2d94a1a370237e')],
    source_segment_ids=['hongloumeng_seg_0128']
)

Claim(
    id='hongloumeng_clm_0013',
    subject='hongloumeng_ent_0005',
    predicate='预言',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0105', start=0, end=15, quote_hash='sha256:d74cacb8bbbc2d3f52da987c8c263754a97fa5954e66b2b9c6f430a4505a8964')],
    source_segment_ids=['hongloumeng_seg_0105']
)

Claim(
    id='hongloumeng_clm_0014',
    subject='hongloumeng_ent_0002',
    predicate='认为',
    modality='uncertain',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0135', start=11, end=20, quote_hash='sha256:829b7e2dccd97a6a018419126e0a4addf32be6acfd13295291d31da2438ccd66')],
    source_segment_ids=['hongloumeng_seg_0135']
)

Claim(
    id='hongloumeng_clm_0015',
    subject='hongloumeng_ent_0002',
    predicate='认为',
    modality='uncertain',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0140', start=20, end=26, quote_hash='sha256:640ddb74217f268bb1f216fddf1e320937d88685b29a36af4681214627c58be5')],
    source_segment_ids=['hongloumeng_seg_0140']
)

Claim(
    id='hongloumeng_clm_0016',
    subject='hongloumeng_ent_0003',
    predicate='认为',
    modality='uncertain',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0131', start=31, end=48, quote_hash='sha256:e21fe905b5cc5f236a567a86efb22954927c4f63eb4e8502e961bd950ecb5650')],
    source_segment_ids=['hongloumeng_seg_0131', 'hongloumeng_seg_0132']
)

Entity(
    id='hongloumeng_ent_0001',
    name='霍启',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0179', 'hongloumeng_seg_0180', 'hongloumeng_seg_0181', 'hongloumeng_seg_0182']
)

Entity(
    id='hongloumeng_ent_0002',
    name='神都',
    kind='location',
    aliases=['神京'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0167', 'hongloumeng_seg_0175']
)

Event(
    id='hongloumeng_evt_0001',
    name='雨村吟联',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0145', 'hongloumeng_seg_0146']
)

Event(
    id='hongloumeng_evt_0002',
    name='士隐邀雨村饮酒赏月',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0153', 'hongloumeng_seg_0154', 'hongloumeng_seg_0155', 'hongloumeng_seg_0156', 'hongloumeng_seg_0157', 'hongloumeng_seg_0158', 'hongloumeng_seg_0159', 'hongloumeng_seg_0160', 'hongloumeng_seg_0161']
)

Event(
    id='hongloumeng_evt_0003',
    name='雨村再吟诗',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0162', 'hongloumeng_seg_0163']
)

Event(
    id='hongloumeng_evt_0004',
    name='士隐赞雨村敬酒',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0164', 'hongloumeng_seg_0165', 'hongloumeng_seg_0166']
)

Event(
    id='hongloumeng_evt_0005',
    name='士隐赠银冬衣',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0170']
)

Event(
    id='hongloumeng_evt_0006',
    name='雨村进京',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0176']
)

Event(
    id='hongloumeng_evt_0007',
    name='元宵佳节',
    kind='occurrence',
    participants=[],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0178']
)

Event(
    id='hongloumeng_evt_0008',
    name='英莲失踪',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0179', 'hongloumeng_seg_0180', 'hongloumeng_seg_0181', 'hongloumeng_seg_0182']
)

Event(
    id='hongloumeng_evt_0009',
    name='士隐夫妇患病',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0186', 'hongloumeng_seg_0187']
)

Event(
    id='hongloumeng_evt_0010',
    name='葫芦庙火灾',
    kind='occurrence',
    participants=['hongloumeng_ent_0009'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0188', 'hongloumeng_seg_0189', 'hongloumeng_seg_0190', 'hongloumeng_seg_0191']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0009',
    predicate='caught_fire',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0188', start=27, end=31, quote_hash='sha256:dce2be31df37b7a46ae283f77b7caac36a1a70f4a6b650816461794d7cbf60d7'),
        EvidenceRef(segment_id='hongloumeng_seg_0189', start=31, end=43, quote_hash='sha256:95972e3a402ab3bf16c6cbb381b3bcb8444f0783b93b74c71bebee27964e02d8')
    ],
    source_segment_ids=['hongloumeng_seg_0188', 'hongloumeng_seg_0189', 'hongloumeng_seg_0190', 'hongloumeng_seg_0191']
)

Entity(
    id='hongloumeng_ent_0001',
    name='封肃',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0197', start=0, end=7, quote_hash='sha256:86f2c17f97f36b8e6f15890ba4855f335f4e3c776c2078054ccfa21f031bb72f')],
    source_segment_ids=['hongloumeng_seg_0197', 'hongloumeng_seg_0198', 'hongloumeng_seg_0200', 'hongloumeng_seg_0202', 'hongloumeng_seg_0246']
)

Entity(
    id='hongloumeng_ent_0002',
    name='大如州',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0197', start=8, end=15, quote_hash='sha256:376e2ab9d5af9dfc7bb13e04d9dc597aed223691e607102e419a765a15aad6e0')],
    source_segment_ids=['hongloumeng_seg_0197']
)

Entity(
    id='hongloumeng_ent_0003',
    name='新太爷',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0247', start=28, end=33, quote_hash='sha256:e4fd58965a143c121b6853d1e8584d4afe13129c528253fd91e927b3aa0f1d7f')],
    source_segment_ids=['hongloumeng_seg_0247', 'hongloumeng_seg_0249']
)

Entity(
    id='hongloumeng_ent_0004',
    name='好了歌',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0219', start=0, end=11, quote_hash='sha256:ddf9174eb513fa14237f939bdaf02db85b33db260d0a7dfa42d79f6cc3308308')],
    source_segment_ids=['hongloumeng_seg_0219', 'hongloumeng_seg_0222', 'hongloumeng_seg_0225', 'hongloumeng_seg_0236']
)

Entity(
    id='hongloumeng_ent_0005',
    name='甄家大丫鬟',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0247', start=3, end=9, quote_hash='sha256:f19a7fcd99f840185c85d5d987904e5f405152dbc9a064132770d273d849f94b')],
    source_segment_ids=['hongloumeng_seg_0247', 'hongloumeng_seg_0248', 'hongloumeng_seg_0250']
)

Event(
    id='hongloumeng_evt_0001',
    name='甄家被烧',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0192', start=11, end=18, quote_hash='sha256:2d10973e557fbb96a3a0f8aeea887406b2dc1763f3e7541e9c52ab8da1853fd7')],
    source_segment_ids=['hongloumeng_seg_0192']
)

Event(
    id='hongloumeng_evt_0002',
    name='士隐投靠岳丈封肃',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0196', start=22, end=28, quote_hash='sha256:659351db7472a4d5e1c8bb38c811b11f2082ceeb22ed0535a637abe9da6941fe')],
    source_segment_ids=['hongloumeng_seg_0196']
)

Event(
    id='hongloumeng_evt_0003',
    name='封肃半哄半赚',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0200', start=4, end=8, quote_hash='sha256:b42839db4d58e06a163fe43134eaa9b449f8440ec06b99be6aee102e35f7e4f3')],
    source_segment_ids=['hongloumeng_seg_0200']
)

Event(
    id='hongloumeng_evt_0004',
    name='士隐贫病交攻',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0203', start=34, end=38, quote_hash='sha256:8fb81ab4e9fe6d7c93ee6ad3ce8035850c80c0630440b3496f2454f6dcb0c09e')],
    source_segment_ids=['hongloumeng_seg_0203']
)

Event(
    id='hongloumeng_evt_0005',
    name='士隐遇跛足道人',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0204', start=26, end=30, quote_hash='sha256:9ebad7c57673b170619268b487f7cf5d35f28409c32210937d408acdedf55ac5')],
    source_segment_ids=['hongloumeng_seg_0204']
)

Event(
    id='hongloumeng_evt_0006',
    name='跛足道人唱好了歌',
    kind='occurrence',
    participants=['hongloumeng_ent_0006', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0205', start=0, end=7, quote_hash='sha256:053e2a5b5b6f983215b5bab536555a90d104fd18f5df3e74bed30134319b5297')],
    source_segment_ids=['hongloumeng_seg_0205', 'hongloumeng_seg_0213', 'hongloumeng_seg_0219']
)

Event(
    id='hongloumeng_evt_0007',
    name='士隐解注好了歌',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0222', start=10, end=16, quote_hash='sha256:16a973eac473414f477d7c760c8ce4ab5556ce0e1164fae292c821356599f4be')],
    source_segment_ids=['hongloumeng_seg_0222', 'hongloumeng_seg_0225', 'hongloumeng_seg_0236']
)

Event(
    id='hongloumeng_evt_0008',
    name='士隐出家随道人去',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0006'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0241', start=19, end=28, quote_hash='sha256:025939d812731c35fc79e9cb84fc74e41d0cc2e40dd32cef29f8d29f008c6a33')],
    source_segment_ids=['hongloumeng_seg_0241']
)

Event(
    id='hongloumeng_evt_0009',
    name='封氏依靠父母度日',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0244', start=7, end=15, quote_hash='sha256:b6c66364eb03c5fdf172bba5376a1100ce3b699bdba9474d4fe6e35f7c4ef6a2')],
    source_segment_ids=['hongloumeng_seg_0244', 'hongloumeng_seg_0245']
)

Event(
    id='hongloumeng_evt_0010',
    name='新太爷到任',
    kind='occurrence',
    participants=['hongloumeng_ent_0003'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0247', start=28, end=33, quote_hash='sha256:e4fd58965a143c121b6853d1e8584d4afe13129c528253fd91e927b3aa0f1d7f')],
    source_segment_ids=['hongloumeng_seg_0247', 'hongloumeng_seg_0249']
)

Entity(
    id='hongloumeng_ent_0001',
    name='太爷',
    kind='person',
    aliases=['本府太爷'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0252', start=1, end=5, quote_hash='sha256:23f9dcfd2ecc8dbeeb3fb0eb4cf15221894803d37ad5ad7dfe241a47d005ef59')],
    source_segment_ids=['hongloumeng_seg_0252']
)

Event(
    id='hongloumeng_evt_0001',
    name='太爷差人传封肃问话',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0252', start=1, end=12, quote_hash='sha256:e0cb859a42d85f23de4d94b759574ffa8c5ded61077b69d0fe4419ad484a1763')],
    source_segment_ids=['hongloumeng_seg_0252']
)

IgnoreSegment(id='hongloumeng_ign_0001', segment_id='hongloumeng_seg_0251', reason='句子主语及指代对象不明确，缺少上下文', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0002', segment_id='hongloumeng_seg_0254', reason='章末套语（且听下回分解）', evidence_refs=[])

