# Auto-generated by t2c v3.4-flash — DO NOT EDIT
from t2c.ontology import Claim, Entity, Event, IgnoreSegment, Relation, Residual

Entity(
    id='hongloumeng_ent_0001',
    name='女娲氏',
    kind='person',
    aliases=['娲皇氏'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0006']
)

Entity(
    id='hongloumeng_ent_0002',
    name='顽石',
    kind='artifact',
    aliases=['石头', '美玉', '弟子'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0005', 'hongloumeng_seg_0006', 'hongloumeng_seg_0007', 'hongloumeng_seg_0008', 'hongloumeng_seg_0009', 'hongloumeng_seg_0014', 'hongloumeng_seg_0015', 'hongloumeng_seg_0017', 'hongloumeng_seg_0018', 'hongloumeng_seg_0019', 'hongloumeng_seg_0020', 'hongloumeng_seg_0021', 'hongloumeng_seg_0022', 'hongloumeng_seg_0025']
)

Entity(
    id='hongloumeng_ent_0003',
    name='大荒山无稽崖',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0005']
)

Entity(
    id='hongloumeng_ent_0004',
    name='青埂峰',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0006', 'hongloumeng_seg_0007', 'hongloumeng_seg_0008', 'hongloumeng_seg_0019']
)

Entity(
    id='hongloumeng_ent_0005',
    name='僧',
    kind='person',
    aliases=['那僧', '大师', '二仙师'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0010', 'hongloumeng_seg_0013', 'hongloumeng_seg_0016', 'hongloumeng_seg_0017', 'hongloumeng_seg_0019', 'hongloumeng_seg_0020', 'hongloumeng_seg_0023', 'hongloumeng_seg_0025', 'hongloumeng_seg_0009']
)

Entity(
    id='hongloumeng_ent_0006',
    name='道人',
    kind='person',
    aliases=['那道', '二仙师'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0010', 'hongloumeng_seg_0025']
)

Entity(
    id='hongloumeng_ent_0007',
    name='红尘中荣华富贵处',
    kind='location',
    aliases=['红尘', '富贵场中', '温柔乡里', '昌明隆盛之邦', '诗礼簪缨之族', '花柳繁华地', '温柔富贵乡'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008', 'hongloumeng_seg_0009', 'hongloumeng_seg_0020']
)

Event(
    id='hongloumeng_evt_0001',
    name='女娲氏炼石补天',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    time='远古',
    location='hongloumeng_ent_0003',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0005']
)

Event(
    id='hongloumeng_evt_0002',
    name='顽石被弃于青埂峰下',
    kind='state_change',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0002'],
    time='炼石补天之后',
    location='hongloumeng_ent_0004',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0006']
)

Event(
    id='hongloumeng_evt_0003',
    name='顽石灵性已通',
    kind='state_change',
    participants=['hongloumeng_ent_0002'],
    location='hongloumeng_ent_0004',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007']
)

Event(
    id='hongloumeng_evt_0004',
    name='僧道来访青埂峰',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    location='hongloumeng_ent_0004',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0008']
)

Event(
    id='hongloumeng_evt_0005',
    name='顽石恳求二仙师携入红尘',
    kind='action',
    participants=['hongloumeng_ent_0002', 'hongloumeng_ent_0005', 'hongloumeng_ent_0006'],
    location='hongloumeng_ent_0004',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0009', 'hongloumeng_seg_0012']
)

Event(
    id='hongloumeng_evt_0006',
    name='二仙师警告红尘无常后允诺',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010', 'hongloumeng_seg_0011', 'hongloumeng_seg_0013', 'hongloumeng_seg_0017']
)

Event(
    id='hongloumeng_evt_0007',
    name='僧念咒书符将顽石变为美玉',
    kind='state_change',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0002'],
    location='hongloumeng_ent_0004',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0019']
)

Event(
    id='hongloumeng_evt_0008',
    name='僧袖美玉与道人飘然而去',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0006', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0025']
)

Claim(
    id='hongloumeng_clm_0001',
    subject='hongloumeng_ent_0002',
    predicate='created_by',
    object='hongloumeng_ent_0001',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0005']
)

Claim(
    id='hongloumeng_clm_0002',
    subject='hongloumeng_ent_0002',
    predicate='abandoned_at',
    object='hongloumeng_ent_0004',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0006']
)

Claim(
    id='hongloumeng_clm_0003',
    subject='hongloumeng_ent_0002',
    predicate='has_spiritual_awareness',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0007']
)

Claim(
    id='hongloumeng_clm_0004',
    subject='hongloumeng_ent_0002',
    predicate='requests_to_enter',
    object='hongloumeng_ent_0007',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0009']
)

Claim(
    id='hongloumeng_clm_0005',
    subject='hongloumeng_ent_0005',
    predicate='transforms',
    object='hongloumeng_ent_0002',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0019']
)

Claim(
    id='hongloumeng_clm_0006',
    subject='hongloumeng_ent_0005',
    predicate='plans_to_inscribe',
    object='hongloumeng_ent_0002',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0020']
)

Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0005',
    predicate='departed_with',
    object='hongloumeng_ent_0002',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0025']
)

Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0006',
    predicate='departed_with',
    object='hongloumeng_ent_0005',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0025']
)

Relation(
    id='hongloumeng_rel_0001',
    subject='hongloumeng_ent_0002',
    predicate='created_by',
    object='hongloumeng_ent_0001',
    claim_id='hongloumeng_clm_0001',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0002',
    subject='hongloumeng_ent_0002',
    predicate='abandoned_at',
    object='hongloumeng_ent_0004',
    claim_id='hongloumeng_clm_0002',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0003',
    subject='hongloumeng_ent_0005',
    predicate='transforms',
    object='hongloumeng_ent_0002',
    claim_id='hongloumeng_clm_0005',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0004',
    subject='hongloumeng_ent_0005',
    predicate='departed_with',
    object='hongloumeng_ent_0002',
    claim_id='hongloumeng_clm_0007',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0005',
    subject='hongloumeng_ent_0006',
    predicate='departed_with',
    object='hongloumeng_ent_0005',
    claim_id='hongloumeng_clm_0008',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0001',
    segment_id='hongloumeng_seg_0001',
    category='structural',
    importance='high',
    reason="章回标题。标题中'甄士隐梦幻识通灵'与'贾雨村风尘怀闺秀'二人未在本段文本出现；但'通灵'一词暗中预指顽石未来化为通灵宝玉的关键伏笔，无法由本回正文内容独立结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0002',
    segment_id='hongloumeng_seg_0002',
    category='structural',
    importance='high',
    reason="开篇'列位看官'为说书人套语，确立全书的拟说书体叙事框架，是红楼梦叙事学的关键设定",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0003',
    segment_id='hongloumeng_seg_0003',
    category='implication',
    importance='high',
    reason="作者自述'虽近荒唐，细按则深有趣味'——点明文本的寓言性质，暗示读者需细读方解其味，是全书的解读方法论提示",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0004',
    segment_id='hongloumeng_seg_0008',
    category='stylistic',
    importance='medium',
    reason="僧道外貌'骨格不凡，丰神迥别'采用典型仙话笔法，体现全书神魔/仙道语域特征",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0005',
    segment_id='hongloumeng_seg_0011',
    category='cultural',
    importance='high',
    reason="'美中不足，好事多磨'是经典谶语式命题，与下文'瞬息间则又乐极悲生'共同构成全书悲喜交织主旨的预叙（凡例诗谶源头之一）",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0006',
    segment_id='hongloumeng_seg_0013',
    category='implication',
    importance='high',
    reason="'静极思动，无中生有之数'——道家/易学式的哲理评论，对顽石入世动机的形而上解释，含有命运前定意味，无法结构化为单一断言",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0007',
    segment_id='hongloumeng_seg_0017',
    category='implication',
    importance='medium',
    reason="僧称石头'性灵却又质蠢，并无奇贵之处，只好踮脚而已'——对顽石资质既肯定又贬抑的含糊评价，以及'待劫终之日，复还本质，以了此案'的'劫终归本'许诺，为石头入世下凡与最终归位提供因果框架，但具体所指（何案、何本质、何劫终）俱不明，无法结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0008',
    segment_id='hongloumeng_seg_0020',
    category='implication',
    importance='high',
    reason="'昌明隆盛之邦、诗礼簪缨之族、花柳繁华地、温柔富贵乡'四组排比是后世指向金陵贾府的关键隐喻集合，但属隐性指引而非常识可定地点，无法安全结构化为单一地理实体",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0009',
    segment_id='hongloumeng_seg_0025',
    category='implication',
    importance='medium',
    reason="'竟不知投奔何方何舍'——僧道携石所往目的地被叙述者主动悬置，构成目的地的叙事性留白",
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0008',
    name='道人',
    kind='person',
    aliases=['空空道人', '茫茫大士', '渺渺真人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026', 'hongloumeng_seg_0027', 'hongloumeng_seg_0032', 'hongloumeng_seg_0033']
)

Entity(
    id='hongloumeng_ent_0009',
    name='班姑',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Entity(
    id='hongloumeng_ent_0010',
    name='蔡女',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Entity(
    id='hongloumeng_ent_0011',
    name='石上故事',
    kind='artifact',
    aliases=['石上字迹'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026', 'hongloumeng_seg_0027', 'hongloumeng_seg_0030', 'hongloumeng_seg_0031', 'hongloumeng_seg_0033']
)

Event(
    id='hongloumeng_evt_0009',
    name='空空道人访道求仙经过青埂峰',
    kind='action',
    participants=['hongloumeng_ent_0006'],
    location='大荒山无稽崖青埂峰',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026']
)

Event(
    id='hongloumeng_evt_0010',
    name='空空道人阅读石上字迹',
    kind='action',
    participants=['hongloumeng_ent_0006'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0027']
)

Event(
    id='hongloumeng_evt_0011',
    name='空空道人向石头说话',
    kind='action',
    participants=['hongloumeng_ent_0006', 'hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0032', 'hongloumeng_seg_0033']
)

Event(
    id='hongloumeng_evt_0012',
    name='石头笑答',
    kind='action',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0034']
)

Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0002',
    predicate='has_writing',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026']
)

Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0002',
    predicate='records',
    object='hongloumeng_ent_0010',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026', 'hongloumeng_seg_0027', 'hongloumeng_seg_0030']
)

Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0002',
    predicate='carried_by',
    object='hongloumeng_ent_0006',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0027']
)

Claim(
    id='hongloumeng_clm_0012',
    subject='hongloumeng_ent_0002',
    predicate='carried_into',
    object='hongloumeng_ent_0007',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0027']
)

Claim(
    id='hongloumeng_clm_0013',
    subject='hongloumeng_ent_0002',
    predicate='located_at',
    object='hongloumeng_ent_0004',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0026']
)

Claim(
    id='hongloumeng_clm_0014',
    subject='hongloumeng_ent_0010',
    predicate='lacks_historical_geo_setting',
    modality='asserted',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0031']
)

Claim(
    id='hongloumeng_clm_0015',
    subject='hongloumeng_ent_0006',
    predicate='claimed_no_dynasty_record',
    modality='claimed_by_source',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Claim(
    id='hongloumeng_clm_0016',
    subject='hongloumeng_ent_0006',
    predicate='claimed_no_virtuous_administration',
    modality='claimed_by_source',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Claim(
    id='hongloumeng_clm_0017',
    subject='hongloumeng_ent_0006',
    predicate='claimed_only_unusual_women',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Claim(
    id='hongloumeng_clm_0018',
    subject='hongloumeng_ent_0006',
    predicate='claimed_women_lack_classical_virtue',
    modality='claimed_by_source',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)

Relation(
    id='hongloumeng_rel_0006',
    subject='hongloumeng_ent_0002',
    predicate='records',
    object='hongloumeng_ent_0010',
    claim_id='hongloumeng_clm_0010',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0007',
    subject='hongloumeng_ent_0002',
    predicate='carried_by',
    object='hongloumeng_ent_0006',
    claim_id='hongloumeng_clm_0011',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0008',
    subject='hongloumeng_ent_0002',
    predicate='carried_into',
    object='hongloumeng_ent_0007',
    claim_id='hongloumeng_clm_0012',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0009',
    subject='hongloumeng_ent_0002',
    predicate='located_at',
    object='hongloumeng_ent_0004',
    claim_id='hongloumeng_clm_0013',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0010',
    segment_id='hongloumeng_seg_0028',
    category='stylistic',
    importance='high',
    reason="石头自叹诗'无材可去补苍天，枉入红尘若许年'是通灵宝玉主题的诗化核心表达，含自嘲与宿命感，无法安全结构化为事实命题",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0011',
    segment_id='hongloumeng_seg_0029',
    category='stylistic',
    importance='high',
    reason="石头自问诗'倩谁记去作奇传'，暗示石头主动求传，是石头入世动机与小说叙事框架的重要隐喻",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0012',
    segment_id='hongloumeng_seg_0033',
    category='cultural',
    importance='medium',
    reason='引用班姑（班昭）、蔡女（蔡琰）作为古代才德女性的典范，属文化背景知识，需读者具备历史知识方可解读',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0013',
    segment_id='hongloumeng_seg_0033',
    category='implication',
    importance='high',
    reason="空空道人'几个异样女子'的反传统定位隐含曹雪芹的女性观，'异样女子'与'班姑蔡女'的对比暗含价值颠覆与自我辩护，无法仅以claim结构化",
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0012',
    name='潘安',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0013',
    name='子建',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0014',
    name='西子',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0015',
    name='文君',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0016',
    name='红娘',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0017',
    name='小玉',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0018',
    name='情僧',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0039']
)

Entity(
    id='hongloumeng_ent_0019',
    name='玉峰',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0041']
)

Entity(
    id='hongloumeng_ent_0020',
    name='孔梅溪',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0042']
)

Entity(
    id='hongloumeng_ent_0021',
    name='脂砚斋',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0045']
)

Entity(
    id='hongloumeng_ent_0022',
    name='《石头记》',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035', 'hongloumeng_seg_0036', 'hongloumeng_seg_0037', 'hongloumeng_seg_0038', 'hongloumeng_seg_0039', 'hongloumeng_seg_0045']
)

Entity(
    id='hongloumeng_ent_0023',
    name='《情僧录》',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0039']
)

Entity(
    id='hongloumeng_ent_0024',
    name='《红楼梦》',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0041']
)

Entity(
    id='hongloumeng_ent_0025',
    name='《风月宝鉴》',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0042']
)

Entity(
    id='hongloumeng_ent_0026',
    name='野史',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0027',
    name='风月笔墨',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Entity(
    id='hongloumeng_ent_0028',
    name='佳人才子书',
    kind='concept',
    aliases=['佳人才子等书'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Event(
    id='hongloumeng_evt_0013',
    name='顽石对僧道陈述创作理念',
    kind='action',
    participants=['hongloumeng_ent_0002', 'hongloumeng_ent_0005', 'hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0035']
)

Event(
    id='hongloumeng_evt_0014',
    name='空空道人检阅《石头记》',
    kind='action',
    participants=['hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0036']
)

Event(
    id='hongloumeng_evt_0015',
    name='空空道人抄录《石头记》以问世传奇',
    kind='action',
    participants=['hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038']
)

Event(
    id='hongloumeng_evt_0016',
    name='空空道人易名为情僧并改《石头记》为《情僧录》',
    kind='state_change',
    participants=['hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0039']
)

Event(
    id='hongloumeng_evt_0017',
    name='玉峰题书名为《红楼梦》',
    kind='action',
    participants=['hongloumeng_ent_0019'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0041']
)

Event(
    id='hongloumeng_evt_0018',
    name='孔梅溪题书名为《风月宝鉴》',
    kind='action',
    participants=['hongloumeng_ent_0020'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0042']
)

Event(
    id='hongloumeng_evt_0019',
    name='脂砚斋甲戌年抄阅再评',
    kind='action',
    participants=['hongloumeng_ent_0021'],
    time='甲戌年',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0045']
)

Claim(
    id='hongloumeng_clm_0019',
    subject='hongloumeng_ent_0022',
    predicate='contains_moral_criticism',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0036']
)

Claim(
    id='hongloumeng_clm_0020',
    subject='hongloumeng_ent_0022',
    predicate='contains_ethical_praise',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0036']
)

Claim(
    id='hongloumeng_clm_0021',
    subject='hongloumeng_ent_0022',
    predicate='main_theme_is_emotion',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0037']
)

Claim(
    id='hongloumeng_clm_0022',
    subject='hongloumeng_ent_0022',
    predicate='records_actual_events',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0037']
)

Claim(
    id='hongloumeng_clm_0023',
    subject='hongloumeng_ent_0022',
    predicate='does_not_interfere_with_politics',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0038']
)

Claim(
    id='hongloumeng_clm_0024',
    subject='hongloumeng_ent_0008',
    predicate='renamed_to',
    object='hongloumeng_ent_0018',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0039']
)

Claim(
    id='hongloumeng_clm_0025',
    subject='hongloumeng_ent_0022',
    predicate='renamed_to',
    object='hongloumeng_ent_0023',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0039']
)

Claim(
    id='hongloumeng_clm_0026',
    subject='hongloumeng_ent_0019',
    predicate='titled_as',
    object='hongloumeng_ent_0024',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0041']
)

Claim(
    id='hongloumeng_clm_0027',
    subject='hongloumeng_ent_0020',
    predicate='titled_as',
    object='hongloumeng_ent_0025',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0042']
)

Claim(
    id='hongloumeng_clm_0028',
    subject='hongloumeng_ent_0021',
    predicate='re_reviewed_and_kept_name',
    object='hongloumeng_ent_0022',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0045']
)

Relation(
    id='hongloumeng_rel_0010',
    subject='hongloumeng_ent_0008',
    predicate='renamed_to',
    object='hongloumeng_ent_0018',
    claim_id='hongloumeng_clm_0024',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0011',
    subject='hongloumeng_ent_0022',
    predicate='renamed_to',
    object='hongloumeng_ent_0023',
    claim_id='hongloumeng_clm_0025',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0012',
    subject='hongloumeng_ent_0019',
    predicate='titled_as',
    object='hongloumeng_ent_0024',
    claim_id='hongloumeng_clm_0026',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0013',
    subject='hongloumeng_ent_0020',
    predicate='titled_as',
    object='hongloumeng_ent_0025',
    claim_id='hongloumeng_clm_0027',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0014',
    subject='hongloumeng_ent_0021',
    predicate='re_reviewed',
    object='hongloumeng_ent_0022',
    claim_id='hongloumeng_clm_0028',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0014',
    segment_id='hongloumeng_seg_0035',
    category='structural',
    importance='high',
    reason='本段是作者借顽石之口发表的文学宣言,系统阐释创作理念(不拘朝代、实录其事、批判俗套),具有提纲性质,但内含反讽与作者意图,难以安全结构化为事实',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0015',
    segment_id='hongloumeng_seg_0039',
    category='cultural',
    importance='high',
    reason='"因空见色,由色生情,传情入色,自色悟空"为佛学色空循环的哲学命题,蕴含全书哲学骨架,无法以单一事实结构化',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0016',
    segment_id='hongloumeng_seg_0043',
    category='stylistic',
    importance='high',
    reason='"满纸荒唐言,一把辛酸泪!都云作者痴,谁解其中味?"为开卷题诗,具提纲性质且含反讽意味,难直接结构化为事实',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0017',
    segment_id='hongloumeng_seg_0035',
    category='implication',
    importance='medium',
    reason='0035的说话人身份可有多重解读(顽石自述/作者叙述声音),原文未明确标明,不宜强行归属',
    evidence_refs=[]
)

IgnoreSegment(id='hongloumeng_ign_0001', segment_id='hongloumeng_seg_0040', reason='"至?"为印刷或分章残段,疑为下段"至吴玉峰题曰"开头的错分,属格式噪声', evidence_refs=[])

Entity(
    id='hongloumeng_ent_0029',
    name='姑苏',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0047']
)

Entity(
    id='hongloumeng_ent_0030',
    name='阊门',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0047', 'hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0031',
    name='十里街',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0032',
    name='仁清巷',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0033',
    name='葫芦庙',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0048']
)

Entity(
    id='hongloumeng_ent_0034',
    name='甄士隐',
    kind='person',
    aliases=['士隐'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0049', 'hongloumeng_seg_0052', 'hongloumeng_seg_0053', 'hongloumeng_seg_0054']
)

Entity(
    id='hongloumeng_ent_0035',
    name='封氏',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0050']
)

Entity(
    id='hongloumeng_ent_0036',
    name='英莲',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0053']
)

Entity(
    id='hongloumeng_ent_0037',
    name='西方灵河岸',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0038',
    name='三生石',
    kind='location',
    aliases=['三生石畔'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0039',
    name='绛珠草',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0040',
    name='赤瑕宫',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0041',
    name='神瑛侍者',
    kind='person',
    aliases=['神瑛'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0042',
    name='离恨天',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0043',
    name='蜜青果',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0044',
    name='灌愁海水',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0045',
    name='警幻仙子',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0046',
    name='绛珠仙子',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Entity(
    id='hongloumeng_ent_0047',
    name='风流公案',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0059']
)

Entity(
    id='hongloumeng_ent_0048',
    name='风流冤家',
    kind='concept',
    aliases=['风流冤孽'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0059', 'hongloumeng_seg_0061', 'hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0020',
    name='甄士隐书房午睡入梦',
    kind='occurrence',
    participants=['hongloumeng_ent_0034'],
    time='炎夏永昼',
    location='书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0054']
)

Event(
    id='hongloumeng_evt_0021',
    name='甄士隐梦中遇一僧一道且行且谈',
    kind='occurrence',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0005', 'hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0055', 'hongloumeng_seg_0056']
)

Event(
    id='hongloumeng_evt_0022',
    name='僧道梦中对话（谈蠢物下凡与还泪公案）',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0008', 'hongloumeng_ent_0002', 'hongloumeng_ent_0047', 'hongloumeng_ent_0048'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0057', 'hongloumeng_seg_0058', 'hongloumeng_seg_0059', 'hongloumeng_seg_0060', 'hongloumeng_seg_0061', 'hongloumeng_seg_0062', 'hongloumeng_seg_0063', 'hongloumeng_seg_0064', 'hongloumeng_seg_0065', 'hongloumeng_seg_0066', 'hongloumeng_seg_0067', 'hongloumeng_seg_0068']
)

Event(
    id='hongloumeng_evt_0023',
    name='神瑛侍者甘露灌溉绛珠草',
    kind='action',
    participants=['hongloumeng_ent_0041', 'hongloumeng_ent_0039'],
    location='西方灵河岸三生石畔',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0025',
    name='神瑛侍者凡心偶炽，意欲下凡造历幻缘，已在警幻仙子案前挂号',
    kind='action',
    participants=['hongloumeng_ent_0041', 'hongloumeng_ent_0045'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0026',
    name='警幻仙子问及灌溉之情未偿',
    kind='action',
    participants=['hongloumeng_ent_0045', 'hongloumeng_ent_0041', 'hongloumeng_ent_0046'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Event(
    id='hongloumeng_evt_0027',
    name='绛珠仙子决意下世为人，以一生眼泪偿还神瑛侍者灌溉之德',
    kind='action',
    participants=['hongloumeng_ent_0046', 'hongloumeng_ent_0041'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Claim(
    id='hongloumeng_clm_0029',
    subject='hongloumeng_ent_0034',
    predicate='lives_at',
    object='hongloumeng_ent_0033',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0049']
)

Claim(
    id='hongloumeng_clm_0030',
    subject='hongloumeng_ent_0035',
    predicate='is_wife_of',
    object='hongloumeng_ent_0034',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0049', 'hongloumeng_seg_0050']
)

Claim(
    id='hongloumeng_clm_0044',
    subject='hongloumeng_ent_0039',
    predicate='transforms_into',
    object='hongloumeng_ent_0046',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

Residual(
    id='hongloumeng_res_0018',
    segment_id='hongloumeng_seg_0046',
    category='structural',
    importance='medium',
    reason='承前启下过渡句，叙事上从前情总评转入石上正文，是章节结构的衔接标志',
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0029',
    name='贾雨村',
    kind='person',
    aliases=['时飞', '雨村', '雨村者'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0112']
)

Entity(
    id='hongloumeng_ent_0030',
    name='北邙山',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0107']
)

Entity(
    id='hongloumeng_ent_0031',
    name='太虚幻境',
    kind='location',
    aliases=['幻境'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0089', 'hongloumeng_seg_0091', 'hongloumeng_seg_0107']
)

Entity(
    id='hongloumeng_ent_0032',
    name='奶母',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0096']
)

Entity(
    id='hongloumeng_ent_0033',
    name='顽石',
    kind='artifact',
    aliases=['弟子', '蠢物', '通灵宝玉'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0071', 'hongloumeng_seg_0075', 'hongloumeng_seg_0083', 'hongloumeng_seg_0087', 'hongloumeng_seg_0079']
)

Entity(
    id='hongloumeng_ent_0034',
    name='风流孽鬼',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0071']
)

Event(
    id='hongloumeng_evt_0020',
    name='僧道商议去警幻仙子宫交割蠢物',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0008'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0069', 'hongloumeng_seg_0071', 'hongloumeng_seg_0073']
)

Event(
    id='hongloumeng_evt_0021',
    name='僧将蠢物取出递给甄士隐看',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0085', 'hongloumeng_seg_0086', 'hongloumeng_seg_0087', 'hongloumeng_seg_0088']
)

Event(
    id='hongloumeng_evt_0022',
    name='僧道从甄士隐手中夺回蠢物并穿过太虚幻境牌坊',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0008'],
    location='太虚幻境',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0089', 'hongloumeng_seg_0090', 'hongloumeng_seg_0091', 'hongloumeng_seg_0092', 'hongloumeng_seg_0093']
)

Event(
    id='hongloumeng_evt_0023',
    name='甄士隐被霹雳惊醒忘却梦中之事',
    kind='state_change',
    participants=['hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0094', 'hongloumeng_seg_0095']
)

Event(
    id='hongloumeng_evt_0025',
    name='癞僧跛道出现并对甄士隐言说英莲累及爹娘',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0008', 'hongloumeng_ent_0034', 'hongloumeng_ent_0036'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0098', 'hongloumeng_seg_0099', 'hongloumeng_seg_0100', 'hongloumeng_seg_0101', 'hongloumeng_seg_0102', 'hongloumeng_seg_0103']
)

Event(
    id='hongloumeng_evt_0026',
    name='癞僧指着士隐大笑并口念四句言词预言',
    kind='action',
    participants=['hongloumeng_ent_0005'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0103', 'hongloumeng_seg_0104', 'hongloumeng_seg_0105']
)

Event(
    id='hongloumeng_evt_0027',
    name='僧道约定北邙山三劫后相见后消失',
    kind='action',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0008'],
    location='北邙山',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0106', 'hongloumeng_seg_0107', 'hongloumeng_seg_0109', 'hongloumeng_seg_0110']
)

Claim(
    id='hongloumeng_clm_0029',
    subject='hongloumeng_ent_0002',
    predicate='has_inscription',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0087', 'hongloumeng_seg_0088']
)

Claim(
    id='hongloumeng_clm_0030',
    subject='hongloumeng_ent_0034',
    predicate='heard_dialogue_of',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0074']
)

Residual(
    id='hongloumeng_res_0018',
    segment_id='hongloumeng_seg_0099',
    category='stylistic',
    importance='medium',
    reason='僧道外貌描写（癞头跣脚、跛足蓬头、疯疯癫癫）暗示其非俗世中人，是神话人物的典型形象塑造，兼具表意与叙事功能',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0019',
    segment_id='hongloumeng_seg_0104',
    category='cultural',
    importance='high',
    reason="癞僧预言诗'菱花空对雪澌澌'、'好防佳节元宵后，便是烟消火灭时'为英莲命运的关键伏笔，菱花喻莲，雪为薛家谐音，元宵后指被拐之时，烟消火灭指英莲悲剧命运，蕴含大量隐喻难以完全结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0020',
    segment_id='hongloumeng_seg_0111',
    category='interpersonal',
    importance='medium',
    reason="士隐'心下犹豫'、'悔却晚也'等心理活动反映其对僧道来历的怀疑与错过询问机会的遗憾，是关键人际心理转折",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0021',
    segment_id='hongloumeng_seg_0081',
    category='implication',
    importance='high',
    reason="'跳出火坑'隐含整部红楼梦救赎主题，二仙师许诺士隐只要不忘他们便能跳出火坑，其具体所指（红尘/凡世/情孽）含糊难明，为全书主旨埋下伏笔",
    evidence_refs=[]
)

IgnoreSegment(id='hongloumeng_ign_0002', segment_id='hongloumeng_seg_0070', reason='纯说话人标记（那僧道：），无实质内容', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0003', segment_id='hongloumeng_seg_0072', reason='纯说话人标记（道人道：），无实质内容', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0004', segment_id='hongloumeng_seg_0080', reason='纯说话人标记（二仙笑道：），无实质内容', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0005', segment_id='hongloumeng_seg_0084', reason='纯说话人标记（那僧道：），无实质内容', evidence_refs=[])

IgnoreSegment(id='hongloumeng_ign_0006', segment_id='hongloumeng_seg_0108', reason='纯说话人标记（那僧道：），无实质内容', evidence_refs=[])

Entity(
    id='hongloumeng_ent_0035',
    name='胡州',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0113']
)

Entity(
    id='hongloumeng_ent_0036',
    name='严老爷',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0120']
)

Entity(
    id='hongloumeng_ent_0037',
    name='甄家丫鬟',
    kind='person',
    aliases=['丫鬟', '甄家之婢'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0127', 'hongloumeng_seg_0130', 'hongloumeng_seg_0140']
)

Entity(
    id='hongloumeng_ent_0038',
    name='书房',
    kind='location',
    aliases=['小斋'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0117', 'hongloumeng_seg_0118', 'hongloumeng_seg_0139']
)

Entity(
    id='hongloumeng_ent_0039',
    name='前厅',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0125']
)

Entity(
    id='hongloumeng_ent_0040',
    name='雨村中秋诗',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0141', 'hongloumeng_seg_0142', 'hongloumeng_seg_0143', 'hongloumeng_seg_0144']
)

Entity(
    id='hongloumeng_ent_0041',
    name='雨村吟联',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0146']
)

Event(
    id='hongloumeng_evt_0029',
    name='贾雨村寄居葫芦庙卖字为生',
    kind='action',
    participants=['hongloumeng_ent_0029'],
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0113', 'hongloumeng_seg_0114']
)

Event(
    id='hongloumeng_evt_0030',
    name='甄士隐迎雨村入书房闲话',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0029'],
    location='书房',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0115', 'hongloumeng_seg_0116', 'hongloumeng_seg_0117', 'hongloumeng_seg_0118', 'hongloumeng_seg_0119']
)

Event(
    id='hongloumeng_evt_0033',
    name='雨村不告而别离甄家',
    kind='action',
    participants=['hongloumeng_ent_0029'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0136', 'hongloumeng_seg_0137']
)

Event(
    id='hongloumeng_evt_0034',
    name='士隐中秋亲至庙中邀雨村',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0029'],
    time='中秋佳节',
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0138', 'hongloumeng_seg_0139']
)

Event(
    id='hongloumeng_evt_0035',
    name='雨村即兴赋诗吟联抒怀',
    kind='action',
    participants=['hongloumeng_ent_0029'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0140', 'hongloumeng_seg_0141', 'hongloumeng_seg_0142', 'hongloumeng_seg_0143', 'hongloumeng_seg_0144', 'hongloumeng_seg_0145', 'hongloumeng_seg_0146']
)

Event(
    id='hongloumeng_evt_0036',
    name='士隐听雨村吟诗并评其抱负',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0029'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0147', 'hongloumeng_seg_0148', 'hongloumeng_seg_0149', 'hongloumeng_seg_0150', 'hongloumeng_seg_0151', 'hongloumeng_seg_0152', 'hongloumeng_seg_0153']
)

Claim(
    id='hongloumeng_clm_0044',
    subject='hongloumeng_ent_0029',
    predicate='earns_living_by_selling_calligraphy',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0114']
)

Claim(
    id='hongloumeng_clm_0050',
    subject='hongloumeng_ent_0034',
    predicate='praises_ambition_of',
    object='hongloumeng_ent_0029',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0147', 'hongloumeng_seg_0148']
)

Claim(
    id='hongloumeng_clm_0051',
    subject='hongloumeng_ent_0029',
    predicate='claims_modesty',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0149', 'hongloumeng_seg_0150']
)

Residual(
    id='hongloumeng_res_0022',
    segment_id='hongloumeng_seg_0141',
    category='stylistic',
    importance='high',
    reason="雨村所吟七言律诗含'未卜三生愿，频添一段愁''蟾光如有意，先上玉人楼'等关键诗句，暗示其对甄家丫鬟的暗中心仪及对前世姻缘之执念，是雨村心理活动之集中表达，不宜作事实声明结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0023',
    segment_id='hongloumeng_seg_0146',
    category='stylistic',
    importance='high',
    reason="对联'玉在匮中求善价，钗于奁内待时飞'以器物自喻求售与待时而起之志，'待时飞'暗合雨村字'时飞'，是人物自我期许之重要伏笔并兼具情节预言功能，涉及人物心理暗示与作者隐喻，不宜作为事实结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0024',
    segment_id='hongloumeng_seg_0131',
    category='implication',
    importance='medium',
    reason="甄家丫鬟心中转述'我家主人常说的什么贾雨村了，每有意帮助周济'及'怪道又说他必非久困之人'，前者为士隐私下评价与意图之转述（modality应为reported），后者为对雨村未来之预言性断言（uncertain），故无法作事实结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0025',
    segment_id='hongloumeng_seg_0135',
    category='implication',
    importance='high',
    reason="雨村'自谓这女子心中有意于他'并'自谓此女子必是个巨眼英豪，风尘中之知己也'，此为雨村自作多情之心理投射。丫鬟'回头两次'是事实，'有意'则属雨村臆断，带有反讽意味的自我拔高，文本对此心态有隐约之批评，不宜作事实结构化",
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0042',
    name='封肃',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Entity(
    id='hongloumeng_ent_0043',
    name='跛足道人',
    kind='person',
    aliases=['那道人'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0204', 'hongloumeng_seg_0215']
)

Entity(
    id='hongloumeng_ent_0044',
    name='大如州',
    kind='location',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Entity(
    id='hongloumeng_ent_0045',
    name='《好了歌》',
    kind='artifact',
    aliases=['好了歌'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0219']
)

Event(
    id='hongloumeng_evt_0037',
    name='甄士隐得病',
    kind='state_change',
    participants=['hongloumeng_ent_0034'],
    time='一月后',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0186']
)

Event(
    id='hongloumeng_evt_0038',
    name='封氏因思女构疾',
    kind='state_change',
    participants=['hongloumeng_ent_0035'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0187']
)

Event(
    id='hongloumeng_evt_0039',
    name='葫芦庙炸供起火',
    kind='occurrence',
    participants=['hongloumeng_ent_0033'],
    time='三月十五',
    location='葫芦庙',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0188']
)

Event(
    id='hongloumeng_evt_0040',
    name='大火蔓延烧街',
    kind='occurrence',
    participants=[],
    time='三月十五之夜',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0189', 'hongloumeng_seg_0190', 'hongloumeng_seg_0191']
)

Event(
    id='hongloumeng_evt_0041',
    name='甄家房屋被焚成瓦砾',
    kind='occurrence',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0035'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0192']
)

Event(
    id='hongloumeng_evt_0042',
    name='士隐携妻子与丫鬟投靠岳丈封肃',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0035', 'hongloumeng_ent_0042'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0194', 'hongloumeng_seg_0196']
)

Event(
    id='hongloumeng_evt_0043',
    name='封肃半哄半赚给予士隐薄田朽屋',
    kind='action',
    participants=['hongloumeng_ent_0042', 'hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0199', 'hongloumeng_seg_0200']
)

Event(
    id='hongloumeng_evt_0044',
    name='士隐家道中落',
    kind='state_change',
    participants=['hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0201']
)

Event(
    id='hongloumeng_evt_0045',
    name='士隐贫病交攻露出下世光景',
    kind='state_change',
    participants=['hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0203']
)

Event(
    id='hongloumeng_evt_0046',
    name='跛足道人在街前出现',
    kind='occurrence',
    participants=['hongloumeng_ent_0043'],
    location='街前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0204']
)

Event(
    id='hongloumeng_evt_0047',
    name='跛足道人唱诵《好了歌》',
    kind='action',
    participants=['hongloumeng_ent_0043', 'hongloumeng_ent_0045'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0204', 'hongloumeng_seg_0205', 'hongloumeng_seg_0206', 'hongloumeng_seg_0207', 'hongloumeng_seg_0208', 'hongloumeng_seg_0209', 'hongloumeng_seg_0210', 'hongloumeng_seg_0211', 'hongloumeng_seg_0212', 'hongloumeng_seg_0213']
)

Event(
    id='hongloumeng_evt_0048',
    name='士隐请求解注《好了歌》',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0043', 'hongloumeng_ent_0045'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0220', 'hongloumeng_seg_0221', 'hongloumeng_seg_0222']
)

Claim(
    id='hongloumeng_clm_0052',
    subject='hongloumeng_ent_0035',
    predicate='is_wife_of',
    object='hongloumeng_ent_0034',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0187', 'hongloumeng_seg_0194']
)

Claim(
    id='hongloumeng_clm_0053',
    subject='hongloumeng_ent_0042',
    predicate='is_father_of',
    object='hongloumeng_ent_0035',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0196', 'hongloumeng_seg_0197']
)

Claim(
    id='hongloumeng_clm_0054',
    subject='hongloumeng_ent_0042',
    predicate='is_father_in_law_of',
    object='hongloumeng_ent_0034',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0196', 'hongloumeng_seg_0197']
)

Claim(
    id='hongloumeng_clm_0055',
    subject='hongloumeng_ent_0042',
    predicate='originally_from',
    object='hongloumeng_ent_0044',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Claim(
    id='hongloumeng_clm_0056',
    subject='hongloumeng_ent_0042',
    predicate='is_farmer',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Claim(
    id='hongloumeng_clm_0057',
    subject='hongloumeng_ent_0042',
    predicate='family_is_prosperous',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0197']
)

Claim(
    id='hongloumeng_clm_0058',
    subject='hongloumeng_ent_0034',
    predicate='is_reader',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0201']
)

Claim(
    id='hongloumeng_clm_0059',
    subject='hongloumeng_ent_0034',
    predicate='has_prenatal_wisdom',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0220']
)

Claim(
    id='hongloumeng_clm_0060',
    subject='hongloumeng_ent_0043',
    predicate='author_of',
    object='hongloumeng_ent_0045',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0219']
)

Relation(
    id='hongloumeng_rel_0023',
    subject='hongloumeng_ent_0035',
    predicate='is_wife_of',
    object='hongloumeng_ent_0034',
    claim_id='hongloumeng_clm_0052',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0024',
    subject='hongloumeng_ent_0042',
    predicate='is_father_of',
    object='hongloumeng_ent_0035',
    claim_id='hongloumeng_clm_0053',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0025',
    subject='hongloumeng_ent_0042',
    predicate='is_father_in_law_of',
    object='hongloumeng_ent_0034',
    claim_id='hongloumeng_clm_0054',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0026',
    subject='hongloumeng_ent_0042',
    predicate='originally_from',
    object='hongloumeng_ent_0044',
    claim_id='hongloumeng_clm_0055',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0027',
    subject='hongloumeng_ent_0043',
    predicate='author_of',
    object='hongloumeng_ent_0045',
    claim_id='hongloumeng_clm_0059',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0026',
    segment_id='hongloumeng_seg_0205',
    category='cultural',
    importance='high',
    reason='《好了歌》四段诗歌原文承载重要哲学命题（功名/金银/姣妻/儿孙之虚妄），属于文学性整体文本，无法完整结构化为简单Claim',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0027',
    segment_id='hongloumeng_seg_0220',
    category='implication',
    importance='high',
    reason="士隐'彻悟'为内在心理/精神状态，属主观体验，无法安全结构化为外部可验证事实",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0028',
    segment_id='hongloumeng_seg_0203',
    category='implication',
    importance='high',
    reason="'露出下世光景'为文学性死亡暗示的模糊表达，含叙事预兆功能",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0029',
    segment_id='hongloumeng_seg_0202',
    category='interpersonal',
    importance='medium',
    reason="封肃'人前人后'讽刺'不善过活/好吃懒做'的评价含亲属关系张力与立场偏向，无法中立结构化",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0030',
    segment_id='hongloumeng_seg_0217',
    category='modal',
    importance='high',
    reason="跛足道人提出'好便是了，了便是好'的哲学命题属转述/声称，承载价值观判断，不宜作为事实Claim",
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0031',
    segment_id='hongloumeng_seg_0203',
    category='modal',
    importance='medium',
    reason="士隐'投人不着'的悔恨为内心自责，叠加'上年惊唬'等含糊指代，叙事层面而非可验证事实",
    evidence_refs=[]
)

Entity(
    id='hongloumeng_ent_0046',
    name='褡裢',
    kind='artifact',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0241']
)

Entity(
    id='hongloumeng_ent_0047',
    name='陋室空堂',
    kind='concept',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0225', 'hongloumeng_seg_0226', 'hongloumeng_seg_0227', 'hongloumeng_seg_0228', 'hongloumeng_seg_0229', 'hongloumeng_seg_0230', 'hongloumeng_seg_0231', 'hongloumeng_seg_0232', 'hongloumeng_seg_0233', 'hongloumeng_seg_0234', 'hongloumeng_seg_0235', 'hongloumeng_seg_0236']
)

Event(
    id='hongloumeng_evt_0049',
    name='跛足道人听完后拍掌笑道',
    kind='action',
    participants=['hongloumeng_ent_0043'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0237', 'hongloumeng_seg_0238']
)

Event(
    id='hongloumeng_evt_0050',
    name='甄士隐随跛足道人出家而去',
    kind='action',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0043'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0239', 'hongloumeng_seg_0240', 'hongloumeng_seg_0241']
)

Event(
    id='hongloumeng_evt_0051',
    name='街坊传扬士隐出家之事',
    kind='occurrence',
    participants=['hongloumeng_ent_0034', 'hongloumeng_ent_0043'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0242']
)

Event(
    id='hongloumeng_evt_0052',
    name='封氏哭寻夫',
    kind='action',
    participants=['hongloumeng_ent_0035', 'hongloumeng_ent_0034'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0243']
)

Event(
    id='hongloumeng_evt_0053',
    name='封氏依靠父母度日并以针线贴补家用',
    kind='state_change',
    participants=['hongloumeng_ent_0035', 'hongloumeng_ent_0037'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0244', 'hongloumeng_seg_0245']
)

Event(
    id='hongloumeng_evt_0054',
    name='封肃日日抱怨',
    kind='action',
    participants=['hongloumeng_ent_0042'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0246']
)

Event(
    id='hongloumeng_evt_0055',
    name='甄家大丫鬟在门前买线',
    kind='action',
    participants=['hongloumeng_ent_0037'],
    location='甄家门前',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0247']
)

Event(
    id='hongloumeng_evt_0056',
    name='新太爷到任',
    kind='occurrence',
    participants=['hongloumeng_ent_0029'],
    location='本地',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0247', 'hongloumeng_seg_0248', 'hongloumeng_seg_0249']
)

Event(
    id='hongloumeng_evt_0057',
    name='本府差人传封肃问话',
    kind='action',
    participants=['hongloumeng_ent_0042', 'hongloumeng_ent_0029'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0252', 'hongloumeng_seg_0253']
)

Event(
    id='hongloumeng_evt_0058',
    name='封肃受惊',
    kind='state_change',
    participants=['hongloumeng_ent_0042'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0253']
)

Claim(
    id='hongloumeng_clm_0061',
    subject='hongloumeng_ent_0043',
    predicate='said',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0238']
)

Claim(
    id='hongloumeng_clm_0062',
    subject='hongloumeng_ent_0034',
    predicate='said',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0240']
)

Claim(
    id='hongloumeng_clm_0063',
    subject='hongloumeng_ent_0034',
    predicate='seized',
    object='hongloumeng_ent_0046',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0241']
)

Claim(
    id='hongloumeng_clm_0064',
    subject='hongloumeng_ent_0034',
    predicate='left_with',
    object='hongloumeng_ent_0043',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0241']
)

Claim(
    id='hongloumeng_clm_0065',
    subject='hongloumeng_ent_0034',
    predicate='did_not_return_home',
    modality='asserted',
    polarity='negative',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0241']
)

Claim(
    id='hongloumeng_clm_0066',
    subject='hongloumeng_ent_0035',
    predicate='cried',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0243']
)

Claim(
    id='hongloumeng_clm_0067',
    subject='hongloumeng_ent_0035',
    predicate='dispatched_people_to_search',
    object='hongloumeng_ent_0034',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0243']
)

Claim(
    id='hongloumeng_clm_0068',
    subject='hongloumeng_ent_0035',
    predicate='depends_on_parents',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0244']
)

Claim(
    id='hongloumeng_clm_0069',
    subject='hongloumeng_ent_0037',
    predicate='serves',
    object='hongloumeng_ent_0035',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0245']
)

Claim(
    id='hongloumeng_clm_0070',
    subject='hongloumeng_ent_0042',
    predicate='complained_daily',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0246']
)

Claim(
    id='hongloumeng_clm_0071',
    subject='hongloumeng_ent_0037',
    predicate='felt_new_official_looked_familiar',
    modality='reported',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0250']
)

Claim(
    id='hongloumeng_clm_0072',
    subject='hongloumeng_ent_0042',
    predicate='summoned_by_yamen',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0252']
)

Claim(
    id='hongloumeng_clm_0073',
    subject='hongloumeng_ent_0042',
    predicate='was_frightened',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0253']
)

Claim(
    id='hongloumeng_clm_0074',
    subject='hongloumeng_ent_0046',
    predicate='carried_by',
    object='hongloumeng_ent_0043',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0241']
)

Relation(
    id='hongloumeng_rel_0028',
    subject='hongloumeng_ent_0034',
    predicate='seized',
    object='hongloumeng_ent_0046',
    claim_id='hongloumeng_clm_0063',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0029',
    subject='hongloumeng_ent_0034',
    predicate='left_with',
    object='hongloumeng_ent_0043',
    claim_id='hongloumeng_clm_0064',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0031',
    subject='hongloumeng_ent_0037',
    predicate='serves',
    object='hongloumeng_ent_0035',
    claim_id='hongloumeng_clm_0069',
    evidence_refs=[]
)

Relation(
    id='hongloumeng_rel_0032',
    subject='hongloumeng_ent_0046',
    predicate='carried_by',
    object='hongloumeng_ent_0043',
    claim_id='hongloumeng_clm_0074',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0032',
    segment_id='hongloumeng_seg_0225',
    category='stylistic',
    importance='high',
    reason='「陋室空堂」系列诗是《好了歌》的注解，深刻揭示世事无常、富贵荣华转瞬即逝的哲理主题，是全书的哲学纲领；其中大量对仗、典故、反讽等修辞元素与多义意象，无法安全结构化为简单事实',
    evidence_refs=[]
)

Residual(
    id='hongloumeng_res_0033',
    segment_id='hongloumeng_seg_0250',
    category='implication',
    importance='high',
    reason='丫鬟觉得新太爷「好面善」却想不起在哪里见过——这是重要伏笔，暗示新太爷正是此前寄居葫芦庙的贾雨村；丫鬟本人未确认身份，不可断言为事实',
    evidence_refs=[]
)

IgnoreSegment(id='hongloumeng_ign_0007', segment_id='hongloumeng_seg_0254', reason='章末套语「且听下回分解」，结构噪声，无实质信息价值', evidence_refs=[])

