# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import CoverageReport

CoverageReport(
    id='case_001_coverage',
    doc_id='case_001',
    total_segments=27,
    status_counts={'covered': 1, 'partial': 0, 'raw_only': 0, 'ignored': 0, 'uncovered': 26},
    generated_at='2026-06-05T00:00:00Z'
)
