# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import Relation, EvidenceRef

rela_0000 = Relation(
    id='case_001_rel_0001',
    subject='case_001_ent_0001',
    predicate='at',
    object='case_001_ent_0002',
    claim_id='case_001_clm_0001',
    evidence_refs=[]
)

