# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import Entity, EvidenceRef
from .text import seg_0012

ent_zh_11ef35 = Entity(
    id='case_001_ent_0001',
    name='爱丽丝',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='case_001_seg_0001', start=0, end=3, quote_hash='sha256:cf2c6c2759201f1eb54e800f09cfd43dad69cab1d4099dc919ef586fec4e11c9')],
    source_segment_ids=['case_001_seg_0001']
)

ent_zh_d1cb77 = Entity(
    id='case_001_ent_0002',
    name='火车站',
    kind='location',
    evidence_refs=[EvidenceRef(segment_id='case_001_seg_0001', start=4, end=7, quote_hash='sha256:738cf3d291a6d3379ea88aad59fb3d3c9adb7d30e14e6dac8dff9a6c62d62c88')],
    source_segment_ids=['case_001_seg_0001']
)

