# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import Document, Block, Segment

doc_case_001 = Document(
    id='case_001',
    source_path='/Users/mixi/Desktop/text2code/examples/corpus/case_001.txt',
    raw_text_hash='sha256:7598ba83d86bd92cc38582e64c4a2337b9b75a43d3e812f47cdd3ce43358ebaf',
    total_length=580,
    block_count=11,
    created_at='2026-06-05T11:00:31.149643+00:00'
)

bloc_0001 = Block(
    id='case_001_blk_0000',
    doc_id='case_001',
    index=0,
    block_type='paragraph',
    start_offset=0,
    end_offset=34,
    text_slice='爱丽丝站在火车站的月台上，寒风刺骨。她看了看手表，已经是下午三点了。',
    hash='sha256:dec1505f5a111ecfc01891f01c09748c2bbc8e62022193acc9290472254faa21'
)

bloc_0002 = Block(
    id='case_001_blk_0001',
    doc_id='case_001',
    index=1,
    block_type='paragraph',
    start_offset=36,
    end_offset=79,
    text_slice='「你来得真早啊，」一个陌生的声音从背后传来。爱丽丝转过身，看到一个穿着灰色外套的男人。',
    hash='sha256:bfa891fd07b2fa93c869bb2f739edd06746102d5eda7a34a1d55eee7787df0be'
)

bloc_0003 = Block(
    id='case_001_blk_0002',
    doc_id='case_001',
    index=2,
    block_type='paragraph',
    start_offset=81,
    end_offset=129,
    text_slice='「我在等一位朋友，」爱丽丝回答道，语气平静但略带警惕。「他说下午两点半到，可是到现在还没出现。」',
    hash='sha256:d9d281065fdac3fd32fe7f148dd858c27ca914b02812d3d48666d7f6f027a852'
)

bloc_0004 = Block(
    id='case_001_blk_0003',
    doc_id='case_001',
    index=3,
    block_type='paragraph',
    start_offset=131,
    end_offset=166,
    text_slice='那个男人笑了笑：「或许他只是迟到了。在这个城市里，火车总是不准时的。」',
    hash='sha256:40c8187c1ef74f2e966868c8ebb5a280fa18cbc2b6f7a340e99900f317c8d448'
)

bloc_0005 = Block(
    id='case_001_blk_0004',
    doc_id='case_001',
    index=4,
    block_type='paragraph',
    start_offset=168,
    end_offset=220,
    text_slice='据车站工作人员透露，上午的列车确实出现了延误，原因是北方地区的一场暴风雪。不过下午的班次应该恢复正常了。',
    hash='sha256:e870ae230ad46e94c1f30fea13020917744e5df38011884a984bb8064542f5fc'
)

bloc_0006 = Block(
    id='case_001_blk_0005',
    doc_id='case_001',
    index=5,
    block_type='paragraph',
    start_offset=222,
    end_offset=304,
    text_slice='爱丽丝对此并不确信。她隐约觉得，这位自称"只是路过"的男人，似乎对她等待的那个人有所了解。他话里话外的暗示，让爱丽丝心生疑虑——难道她的朋友并不是因为天气原因迟到？',
    hash='sha256:2d525f0dff6877ee155a3241f206f8dd9cb635e8512b74f333e5df778fb3f33b'
)

bloc_0007 = Block(
    id='case_001_blk_0006',
    doc_id='case_001',
    index=6,
    block_type='paragraph',
    start_offset=306,
    end_offset=393,
    text_slice='第三条 当旅客因不可抗力因素导致行程延误时，铁路公司应提供必要的协助与信息通报。（一）延误时间超过两小时的，应提供餐饮补偿。（二）延误时间超过四小时的，应协助旅客改签或退票。',
    hash='sha256:2a77bd5ed4d24d632b287e141f2a40372b6c144e8ce38d30b5b34df4f8064c40'
)

bloc_0008 = Block(
    id='case_001_blk_0007',
    doc_id='case_001',
    index=7,
    block_type='table',
    start_offset=395,
    end_offset=473,
    text_slice='| 项目 | 内容 | 备注 |\n| 姓名 | 爱丽丝 | 乘客 |\n| 目的地 | 北方城市 | 经停站 |\n| 列车班次 | K1025 | 下午班 |',
    hash='sha256:cb70fc8135a84f3a30a9ef54ed14cc4596ff09f83f2df4bf1cab5a33bc87424a'
)

bloc_0009 = Block(
    id='case_001_blk_0008',
    doc_id='case_001',
    index=8,
    block_type='list',
    start_offset=475,
    end_offset=512,
    text_slice='- 火车站月台温度低于零度\n- 列车延误公告已发布\n- 餐饮补偿方案已启动',
    hash='sha256:b3e36b13109bcbcabc392bb45fc0d7ece3e267d4ea38b80f6a5fd36765477ae9'
)

bloc_0010 = Block(
    id='case_001_blk_0009',
    doc_id='case_001',
    index=9,
    block_type='heading',
    start_offset=514,
    end_offset=520,
    text_slice='# 案件摘要',
    hash='sha256:d492bc153cf6838d3a3ce800a0aa9504f5f462743d5060b00adc8570d031723e'
)

bloc_0011 = Block(
    id='case_001_blk_0010',
    doc_id='case_001',
    index=10,
    block_type='paragraph',
    start_offset=522,
    end_offset=580,
    text_slice='本案涉及一名乘客在火车站月台等候朋友时，与一位自称"路过"的陌生男子发生对话的情况。乘客对该男子的真实意图存在疑虑。',
    hash='sha256:bac13a6f0509b4efad1963fc37d4f197ae932d697b99b0d201b7d231522db809'
)

seg_0012 = Segment(
    id='case_001_seg_0001',
    doc_id='case_001',
    block_index=0,
    segment_type='sentence',
    start_offset=0,
    end_offset=18,
    text_slice='爱丽丝站在火车站的月台上，寒风刺骨。',
    hash='sha256:2ecd31728186527c27e293f2c6f1885950f545bd717f98c42d1eb9490b06c833'
)

seg_0013 = Segment(
    id='case_001_seg_0002',
    doc_id='case_001',
    block_index=0,
    segment_type='sentence',
    start_offset=18,
    end_offset=34,
    text_slice='她看了看手表，已经是下午三点了。',
    hash='sha256:2df89e3ce5b4a934e60f427e6c35775feaba6c5ff29d56f3ce74dcb74b48d008'
)

seg_0014 = Segment(
    id='case_001_seg_0003',
    doc_id='case_001',
    block_index=1,
    segment_type='sentence',
    start_offset=36,
    end_offset=58,
    text_slice='「你来得真早啊，」一个陌生的声音从背后传来。',
    hash='sha256:01a7533ba71f72f70a95e7e8c4425289217c0d4a6ec044ffb17ffb585bacb6dd'
)

seg_0015 = Segment(
    id='case_001_seg_0004',
    doc_id='case_001',
    block_index=1,
    segment_type='sentence',
    start_offset=58,
    end_offset=79,
    text_slice='爱丽丝转过身，看到一个穿着灰色外套的男人。',
    hash='sha256:2fdd7f9bd52a5c10289627420b50ea0fe27c97f63efe874fe29e54ca0e68d1f6'
)

seg_0016 = Segment(
    id='case_001_seg_0005',
    doc_id='case_001',
    block_index=2,
    segment_type='dialogue',
    start_offset=81,
    end_offset=91,
    text_slice='「我在等一位朋友，」',
    hash='sha256:1c5738dc4c539456dddaf3b1d5626bb5049d1aec88c16c8074f7e56a579c07e0'
)

seg_0017 = Segment(
    id='case_001_seg_0006',
    doc_id='case_001',
    block_index=2,
    segment_type='sentence',
    start_offset=91,
    end_offset=108,
    text_slice='爱丽丝回答道，语气平静但略带警惕。',
    hash='sha256:b8e7881e014311ff43e876da50c925fdc62084cdb0814a2c5a46103bb2ef3821'
)

seg_0018 = Segment(
    id='case_001_seg_0007',
    doc_id='case_001',
    block_index=2,
    segment_type='dialogue',
    start_offset=108,
    end_offset=129,
    text_slice='「他说下午两点半到，可是到现在还没出现。」',
    hash='sha256:dc7d21ef1b497969247cf3ba3c82990d02b426851a4dc164f0072c788454c02e'
)

seg_0019 = Segment(
    id='case_001_seg_0008',
    doc_id='case_001',
    block_index=3,
    segment_type='sentence',
    start_offset=131,
    end_offset=149,
    text_slice='那个男人笑了笑：「或许他只是迟到了。',
    hash='sha256:ff8c012dd933ebabf48bc0849d1affc134750140a3ad59a90fc208fc7c94def9'
)

seg_0020 = Segment(
    id='case_001_seg_0009',
    doc_id='case_001',
    block_index=3,
    segment_type='sentence',
    start_offset=149,
    end_offset=165,
    text_slice='在这个城市里，火车总是不准时的。',
    hash='sha256:765c2af4747e95dda6753ea7adee7cd1250d8c08b04ca4dbc3bd33be98d025dc'
)

seg_0021 = Segment(
    id='case_001_seg_0010',
    doc_id='case_001',
    block_index=4,
    segment_type='sentence',
    start_offset=168,
    end_offset=205,
    text_slice='据车站工作人员透露，上午的列车确实出现了延误，原因是北方地区的一场暴风雪。',
    hash='sha256:15f15d5f84ac0651dbfb7061a8ea39a79f46db061665c4c9a3417c3dbdc246f5'
)

seg_0022 = Segment(
    id='case_001_seg_0011',
    doc_id='case_001',
    block_index=4,
    segment_type='sentence',
    start_offset=205,
    end_offset=220,
    text_slice='不过下午的班次应该恢复正常了。',
    hash='sha256:76bac54dbe5c4c1a370b311c5bc49d58576ee7ef95ba3aa8ee80c41d08f01c2e'
)

seg_0023 = Segment(
    id='case_001_seg_0012',
    doc_id='case_001',
    block_index=5,
    segment_type='sentence',
    start_offset=222,
    end_offset=232,
    text_slice='爱丽丝对此并不确信。',
    hash='sha256:af0b8ad4e4cbe52f825f6007abb3ffaef987dbb9a75084c8239ecc48b78604cd'
)

seg_0024 = Segment(
    id='case_001_seg_0013',
    doc_id='case_001',
    block_index=5,
    segment_type='sentence',
    start_offset=232,
    end_offset=267,
    text_slice='她隐约觉得，这位自称"只是路过"的男人，似乎对她等待的那个人有所了解。',
    hash='sha256:c454c08514735e3f0fbf1eff6033574504f870e7d6e836381eda4368469b1469'
)

seg_0025 = Segment(
    id='case_001_seg_0014',
    doc_id='case_001',
    block_index=5,
    segment_type='sentence',
    start_offset=267,
    end_offset=304,
    text_slice='他话里话外的暗示，让爱丽丝心生疑虑——难道她的朋友并不是因为天气原因迟到？',
    hash='sha256:9a198719266dfb77e0d08741e675aafdbc18ba1a0967b2aed014e94f9634de7b'
)

seg_0026 = Segment(
    id='case_001_seg_0015',
    doc_id='case_001',
    block_index=6,
    segment_type='sentence',
    start_offset=306,
    end_offset=346,
    text_slice='第三条 当旅客因不可抗力因素导致行程延误时，铁路公司应提供必要的协助与信息通报。',
    hash='sha256:f102981f20074a23a6c7a10ce54330c671bcfaf735b03d38b79f764054bfec66'
)

seg_0027 = Segment(
    id='case_001_seg_0016',
    doc_id='case_001',
    block_index=6,
    segment_type='sentence',
    start_offset=346,
    end_offset=368,
    text_slice='（一）延误时间超过两小时的，应提供餐饮补偿。',
    hash='sha256:53a6e14d3758d1b4da67e21460be19f3462ac14aabffd2c901424337899d0d6e'
)

seg_0028 = Segment(
    id='case_001_seg_0017',
    doc_id='case_001',
    block_index=6,
    segment_type='sentence',
    start_offset=368,
    end_offset=393,
    text_slice='（二）延误时间超过四小时的，应协助旅客改签或退票。',
    hash='sha256:841e6066dd759cff83cc42ca844d45ca6af7e40696b6ebc5bef71e89fa92344c'
)

seg_0029 = Segment(
    id='case_001_seg_0018',
    doc_id='case_001',
    block_index=7,
    segment_type='table_row',
    start_offset=395,
    end_offset=411,
    text_slice='| 项目 | 内容 | 备注 |',
    hash='sha256:356aeb52beea1666c74a6c85b5f64117bc4c579eee2e2ab13615e93d96072f10'
)

seg_0030 = Segment(
    id='case_001_seg_0019',
    doc_id='case_001',
    block_index=7,
    segment_type='table_row',
    start_offset=412,
    end_offset=429,
    text_slice='| 姓名 | 爱丽丝 | 乘客 |',
    hash='sha256:4cd1770d1080876288f98dda32eb9bd05eb1e7736ed3acdb7476ec3f1d3a0109'
)

seg_0031 = Segment(
    id='case_001_seg_0020',
    doc_id='case_001',
    block_index=7,
    segment_type='table_row',
    start_offset=430,
    end_offset=450,
    text_slice='| 目的地 | 北方城市 | 经停站 |',
    hash='sha256:1e37e887de57d0e15115450cb7fa5169a1fbfa6b30215761a31fdee3a40e0a12'
)

seg_0032 = Segment(
    id='case_001_seg_0021',
    doc_id='case_001',
    block_index=7,
    segment_type='table_row',
    start_offset=451,
    end_offset=473,
    text_slice='| 列车班次 | K1025 | 下午班 |',
    hash='sha256:164811f656e88337144bd01e8f2d325ac2ca5043d499627e3eb339abde696918'
)

seg_0033 = Segment(
    id='case_001_seg_0022',
    doc_id='case_001',
    block_index=8,
    segment_type='list_item',
    start_offset=475,
    end_offset=488,
    text_slice='- 火车站月台温度低于零度',
    hash='sha256:7534eed2b0c4f0f33e314de94c0812ed060ec7f1f5cd53f044c44a4f7c7f9854'
)

seg_0034 = Segment(
    id='case_001_seg_0023',
    doc_id='case_001',
    block_index=8,
    segment_type='list_item',
    start_offset=489,
    end_offset=500,
    text_slice='- 列车延误公告已发布',
    hash='sha256:b29c16d30d173bc102a33d221ae84d94b917053206de0cc0eb70cc0ddccec025'
)

seg_0035 = Segment(
    id='case_001_seg_0024',
    doc_id='case_001',
    block_index=8,
    segment_type='list_item',
    start_offset=501,
    end_offset=512,
    text_slice='- 餐饮补偿方案已启动',
    hash='sha256:6e9910f3882ce76a6268b56d511b2f535ea3f89ee1354a20d7705675e249cbbc'
)

seg_0036 = Segment(
    id='case_001_seg_0025',
    doc_id='case_001',
    block_index=9,
    segment_type='heading',
    start_offset=514,
    end_offset=520,
    text_slice='# 案件摘要',
    hash='sha256:d492bc153cf6838d3a3ce800a0aa9504f5f462743d5060b00adc8570d031723e'
)

seg_0037 = Segment(
    id='case_001_seg_0026',
    doc_id='case_001',
    block_index=10,
    segment_type='sentence',
    start_offset=522,
    end_offset=564,
    text_slice='本案涉及一名乘客在火车站月台等候朋友时，与一位自称"路过"的陌生男子发生对话的情况。',
    hash='sha256:94646c0ed37702776dd55fffe37ef9093154b50d76dc92b317fc0365c55caba1'
)

seg_0038 = Segment(
    id='case_001_seg_0027',
    doc_id='case_001',
    block_index=10,
    segment_type='sentence',
    start_offset=564,
    end_offset=580,
    text_slice='乘客对该男子的真实意图存在疑虑。',
    hash='sha256:833a3fc492d67a735f807709792a9237e72ec9fee8e5fbf88470938c66904425'
)

