# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Claim, EvidenceRef
from .entities import ent_zh_1d4f27, ent_zh_28d0da, ent_zh_2940ee, ent_zh_3ae3a3, ent_zh_3c0877, ent_zh_8f506e, ent_zh_a1b34e, ent_zh_f4edbe
from .text import seg_0036, seg_0037, seg_0041, seg_0044, seg_0046, seg_0047, seg_0049, seg_0104, seg_0124, seg_0128, seg_0131

claim_hongloumeng_ent_0012_said_ = Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0012',
    predicate='said',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0036', start=120, end=128, quote_hash='sha256:77a3048a62063cff6c167a49dace4151d2b20f6e0abe1c9a8579ac3d44682e56')],
    source_segment_ids=['hongloumeng_seg_0036']
)  # hongloumeng_ent_0012 said

claim_zh_0b0897 = Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0012',
    predicate='comforts',
    object='hongloumeng_ent_0009',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0036', start=583, end=595, quote_hash='sha256:faf2c4c79ddf3b926f51f71600d12c7cb1ba3e28250d0419838898f262216420')],
    source_segment_ids=['hongloumeng_seg_0036']
)  # hongloumeng_ent_0012 comforts hongloumeng_ent_0009

claim_hongloumeng_ent_0006_plans_to_ = Claim(
    id='hongloumeng_clm_0012',
    subject='hongloumeng_ent_0006',
    predicate='plans_to',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0037', start=21, end=30, quote_hash='sha256:44ce9b90fbd481bad4381bc071b28de74c06309af0e0b98252666705ea00112f'),
        EvidenceRef(segment_id='hongloumeng_seg_0046', start=5, end=22, quote_hash='sha256:deacc026c6c9ba3d1e39b8d3e0f58fbaa792d4e84b78b1bbca8cdca69c23853a')
    ],
    source_segment_ids=['hongloumeng_seg_0037', 'hongloumeng_seg_0046']
)  # hongloumeng_ent_0006 plans_to

claim_hongloumeng_ent_0013_said_ = Claim(
    id='hongloumeng_clm_0013',
    subject='hongloumeng_ent_0013',
    predicate='said',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0044', start=1, end=10, quote_hash='sha256:e28cb2098c06c2a3da4fdb4b63b68a6c757a7a10445dbb8f866545749b05c486')],
    source_segment_ids=['hongloumeng_seg_0044', 'hongloumeng_seg_0045']
)  # hongloumeng_ent_0013 said

claim_zh_615a18 = Claim(
    id='hongloumeng_clm_0014',
    subject='hongloumeng_ent_0013',
    predicate='informs',
    object='hongloumeng_ent_0012',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0041', start=13, end=17, quote_hash='sha256:89aa51121dcc57b9ff72aaa63e58e6fa0978fc155cda5b5646abca4a0868c36c'),
        EvidenceRef(segment_id='hongloumeng_seg_0049', start=6, end=14, quote_hash='sha256:57cb078ee9bf74dac67f0898695be4db7be24945a60f5b393a167d457486b232')
    ],
    source_segment_ids=['hongloumeng_seg_0041', 'hongloumeng_seg_0049']
)  # hongloumeng_ent_0013 informs hongloumeng_ent_0012

claim_hongloumeng_ent_0006_receives_ = Claim(
    id='hongloumeng_clm_0015',
    subject='hongloumeng_ent_0006',
    predicate='receives',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0047', start=2, end=12, quote_hash='sha256:b83374262e20282c4c2878a654b50c53c7e9b105f011a445fa9ed8421fb75fd4')],
    source_segment_ids=['hongloumeng_seg_0047']
)  # hongloumeng_ent_0006 receives

claim_zh_f0b79d = Claim(
    id='hongloumeng_clm_0002',
    subject='hongloumeng_ent_0001',
    predicate='said',
    object='hongloumeng_ent_0004',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0104', start=39, end=46, quote_hash='sha256:a809c9c44ba7a44b3716a673b801eb68afbf047db54c690c728b9ce41efe0077')],
    source_segment_ids=['hongloumeng_seg_0104']
)  # hongloumeng_ent_0001 said hongloumeng_ent_0004

claim_zh_afc6b9 = Claim(
    id='hongloumeng_clm_0003',
    subject='hongloumeng_ent_0008',
    predicate='requests',
    object='hongloumeng_ent_0001',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0124', start=8, end=24, quote_hash='sha256:1d7f229dbe5bb8088c9456a9ffc7aad6982b2b58eb9f031304a2086b5cbaec85')],
    source_segment_ids=['hongloumeng_seg_0124']
)  # hongloumeng_ent_0008 requests hongloumeng_ent_0001

claim_zh_ebb356 = Claim(
    id='hongloumeng_clm_0006',
    subject='hongloumeng_ent_0013',
    predicate='is_friend_of',
    object='hongloumeng_ent_0002',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0131', start=19, end=27, quote_hash='sha256:60b6ae8f2af78a29171ff0191ef401ac520ce956f1c5003ec90c178a3220aef0')],
    source_segment_ids=['hongloumeng_seg_0131']
)  # hongloumeng_ent_0013 is_friend_of hongloumeng_ent_0002

claim_zh_06d3e8 = Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0008',
    predicate='informs',
    object='hongloumeng_ent_0013',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0128', start=27, end=36, quote_hash='sha256:25b0e0aa20119963956ca20cc63598a9740475945519fb480c87ae20a11576ba')],
    source_segment_ids=['hongloumeng_seg_0128']
)  # hongloumeng_ent_0008 informs hongloumeng_ent_0013

claim_hongloumeng_ent_0013_plans_to_ = Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0013',
    predicate='plans_to',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0131', start=65, end=76, quote_hash='sha256:327f15a1723226cfaa4d004ba075003b6ace4789d07458c20813270914e5b93c')],
    source_segment_ids=['hongloumeng_seg_0131']
)  # hongloumeng_ent_0013 plans_to

