# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import CoverageReport

coverage_report = CoverageReport(
    id='hongloumeng_coverage',
    doc_id='hongloumeng',
    total_segments=133,
    status_counts={'covered': 55, 'partial': 0, 'raw_only': 27, 'ignored': 8, 'uncovered': 43},
    requires_raw_fallback=['hongloumeng_seg_0001', 'hongloumeng_seg_0002', 'hongloumeng_seg_0004', 'hongloumeng_seg_0005', 'hongloumeng_seg_0006', 'hongloumeng_seg_0007', 'hongloumeng_seg_0008', 'hongloumeng_seg_0009', 'hongloumeng_seg_0013', 'hongloumeng_seg_0014', 'hongloumeng_seg_0017', 'hongloumeng_seg_0018', 'hongloumeng_seg_0019', 'hongloumeng_seg_0020', 'hongloumeng_seg_0021', 'hongloumeng_seg_0022', 'hongloumeng_seg_0023', 'hongloumeng_seg_0028', 'hongloumeng_seg_0038', 'hongloumeng_seg_0039', 'hongloumeng_seg_0040', 'hongloumeng_seg_0042', 'hongloumeng_seg_0043', 'hongloumeng_seg_0048', 'hongloumeng_seg_0050', 'hongloumeng_seg_0051', 'hongloumeng_seg_0052', 'hongloumeng_seg_0053', 'hongloumeng_seg_0054', 'hongloumeng_seg_0055', 'hongloumeng_seg_0056', 'hongloumeng_seg_0057', 'hongloumeng_seg_0058', 'hongloumeng_seg_0060', 'hongloumeng_seg_0061', 'hongloumeng_seg_0062', 'hongloumeng_seg_0063', 'hongloumeng_seg_0064', 'hongloumeng_seg_0065', 'hongloumeng_seg_0066', 'hongloumeng_seg_0067', 'hongloumeng_seg_0069', 'hongloumeng_seg_0070', 'hongloumeng_seg_0072', 'hongloumeng_seg_0073', 'hongloumeng_seg_0074', 'hongloumeng_seg_0075', 'hongloumeng_seg_0076', 'hongloumeng_seg_0077', 'hongloumeng_seg_0078', 'hongloumeng_seg_0079', 'hongloumeng_seg_0080', 'hongloumeng_seg_0081', 'hongloumeng_seg_0082', 'hongloumeng_seg_0083', 'hongloumeng_seg_0084', 'hongloumeng_seg_0085', 'hongloumeng_seg_0086', 'hongloumeng_seg_0087', 'hongloumeng_seg_0088', 'hongloumeng_seg_0089', 'hongloumeng_seg_0091', 'hongloumeng_seg_0093', 'hongloumeng_seg_0094', 'hongloumeng_seg_0095', 'hongloumeng_seg_0096', 'hongloumeng_seg_0097', 'hongloumeng_seg_0098', 'hongloumeng_seg_0099', 'hongloumeng_seg_0100', 'hongloumeng_seg_0101', 'hongloumeng_seg_0130'],
    generated_at='2026-06-08T06:57:58.131468+00:00'
)  # coverage: hongloumeng
