# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Relation, EvidenceRef
from .claims import claim_hongloumeng_ent_0006_plans_to_, claim_hongloumeng_ent_0013_said_, claim_zh_06d3e8, claim_zh_0b0897, claim_zh_615a18, claim_zh_afc6b9, claim_zh_ebb356, claim_zh_f0b79d
from .entities import ent_zh_3ae3a3, ent_zh_3c0877, ent_zh_3c220d, ent_zh_446291, ent_zh_4e74e8, ent_zh_54ab4f, ent_zh_8f506e, ent_zh_a1b34e, ent_zh_e8931a, ent_zh_f7c68e
from .text import seg_0010, seg_0016, seg_0024, seg_0027, seg_0029

rela_0000 = Relation(
    id='hongloumeng_rel_0002',
    subject='hongloumeng_ent_0006',
    predicate='is_spouse_of',
    object='hongloumeng_ent_0007',
    claim_id='hongloumeng_clm_0002',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0024', start=1, end=5, quote_hash='sha256:d6801e009185c071e4abf62790f32ef9d702c25621887c6e9a08493fd8ea9ff3')]
)  # hongloumeng_ent_0006 is_spouse_of hongloumeng_ent_0007

rela_0001 = Relation(
    id='hongloumeng_rel_0003',
    subject='hongloumeng_ent_0006',
    predicate='is_relative_of',
    object='hongloumeng_ent_0001',
    claim_id='hongloumeng_clm_0003',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0010', start=5, end=8, quote_hash='sha256:d0cd9fa9ced6d40fc0e8c484f5f692dda0b47099041804bc49935553a0397982')]
)  # hongloumeng_ent_0006 is_relative_of hongloumeng_ent_0001

rela_0002 = Relation(
    id='hongloumeng_rel_0006',
    subject='hongloumeng_ent_0007',
    predicate='visits',
    object='hongloumeng_ent_0015',
    claim_id='hongloumeng_clm_0006',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0024', start=15, end=28, quote_hash='sha256:da25e306f6b3df50cba67606e291a8f1a412879df4f3c59d02d97853a11d498e')]
)  # hongloumeng_ent_0007 visits hongloumeng_ent_0015

rela_0003 = Relation(
    id='hongloumeng_rel_0007',
    subject='hongloumeng_ent_0012',
    predicate='gives',
    object='hongloumeng_ent_0007',
    claim_id='hongloumeng_clm_0007',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0024', start=42, end=55, quote_hash='sha256:03a1f5eda9d9f5730f45f58ceafe45b31aa9982df11319200a576b0bb92c26a2')]
)  # hongloumeng_ent_0012 gives hongloumeng_ent_0007

rela_0004 = Relation(
    id='hongloumeng_rel_0009',
    subject='hongloumeng_ent_0003',
    predicate='is_relative_of',
    object='hongloumeng_ent_0009',
    claim_id='hongloumeng_clm_0011',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0027', start=82, end=87, quote_hash='sha256:9e95f57e5c98fdb1879fc8a7608cc44d101f685bef35277ca62eb681ec331b01')]
)  # hongloumeng_ent_0003 is_relative_of hongloumeng_ent_0009

rela_0005 = Relation(
    id='hongloumeng_rel_0010',
    subject='hongloumeng_ent_0005',
    predicate='requests',
    object='hongloumeng_ent_0006',
    claim_id='hongloumeng_clm_0012',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0029', start=16, end=25, quote_hash='sha256:8eff5470179e9d70eadaf0c883eabef847c6297661e63451510a6f93dafd63d5')]
)  # hongloumeng_ent_0005 requests hongloumeng_ent_0006

rela_0006 = Relation(
    id='hongloumeng_rel_0011',
    subject='hongloumeng_ent_0001',
    predicate='attends',
    object='hongloumeng_ent_0016',
    claim_id='hongloumeng_clm_0013',
    evidence_refs=[]
)  # hongloumeng_ent_0001 attends hongloumeng_ent_0016

rela_0007 = Relation(
    id='hongloumeng_rel_0012',
    subject='hongloumeng_ent_0010',
    predicate='gives',
    object='hongloumeng_ent_0001',
    claim_id='hongloumeng_clm_0014',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0016', start=15, end=26, quote_hash='sha256:69a8734d00d8d70a168d05c3a5efeee7e2d72f35e8efcb6c065d4f379ef4f05e')]
)  # hongloumeng_ent_0010 gives hongloumeng_ent_0001

