# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Entity, EvidenceRef
from .text import seg_0059, seg_0103, seg_0104, seg_0106, seg_0124, seg_0125, seg_0126, seg_0128, seg_0131

ent_zh_1d4f27 = Entity(
    id='hongloumeng_ent_0008',
    name='贾蓉',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0003', 'hongloumeng_seg_0034']
)  # 贾蓉 (person)

ent_zh_3ae3a3 = Entity(
    id='hongloumeng_ent_0009',
    name='秦可卿',
    kind='person',
    aliases=['蓉大奶奶', '秦钟他姐姐'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0027', 'hongloumeng_seg_0034']
)  # 秦可卿 (person)

ent_zh_446291 = Entity(
    id='hongloumeng_ent_0010',
    name='薛蟠',
    kind='person',
    aliases=['薛大爷'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0015', 'hongloumeng_seg_0016']
)  # 薛蟠 (person)

ent_zh_796da9 = Entity(
    id='hongloumeng_ent_0011',
    name='王熙凤',
    kind='person',
    aliases=['凤姐', '凤姐儿', '琏二奶奶'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010', 'hongloumeng_seg_0024']
)  # 王熙凤 (person)

ent_zh_a1b34e = Entity(
    id='hongloumeng_ent_0012',
    name='尤氏',
    kind='person',
    aliases=['珍大奶奶'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0024', 'hongloumeng_seg_0025', 'hongloumeng_seg_0027', 'hongloumeng_seg_0033', 'hongloumeng_seg_0035']
)  # 尤氏 (person)

ent_zh_2940ee = Entity(
    id='hongloumeng_ent_0013',
    name='贾珍',
    kind='person',
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0033']
)  # 贾珍 (person)

ent_zh_229be9 = Entity(
    id='hongloumeng_ent_0014',
    name='宁府',
    kind='location',
    aliases=['东府'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0024', 'hongloumeng_seg_0025', 'hongloumeng_seg_0027', 'hongloumeng_seg_0032', 'hongloumeng_seg_0033']
)  # 宁府 (location)

ent_zh_e8931a = Entity(
    id='hongloumeng_ent_0015',
    name='荣府',
    kind='location',
    aliases=['西府'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0010', 'hongloumeng_seg_0024', 'hongloumeng_seg_0027']
)  # 荣府 (location)

ent_zh_54ab4f = Entity(
    id='hongloumeng_ent_0016',
    name='贾家学房',
    kind='location',
    aliases=['学里', '学房'],
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0011', 'hongloumeng_seg_0012', 'hongloumeng_seg_0026', 'hongloumeng_seg_0027', 'hongloumeng_seg_0029']
)  # 贾家学房 (location)

ent_zh_8f506e = Entity(
    id='hongloumeng_ent_0006',
    name='大太太',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0059', start=37, end=40, quote_hash='sha256:60a7b061d00b20f638cdac0c29b50354e72caac71be3485aea76e84f14f29ff0')],
    source_segment_ids=['hongloumeng_seg_0059']
)  # 大太太 (person)

ent_zh_3c220d = Entity(
    id='hongloumeng_ent_0007',
    name='二太太',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0059', start=41, end=44, quote_hash='sha256:80435ac2bab228b2668808a1a8a460eea8563ce8c9487eefe8e19e51bbe5b827')],
    source_segment_ids=['hongloumeng_seg_0059']
)  # 二太太 (person)

ent_zh_3c0877 = Entity(
    id='hongloumeng_ent_0001',
    name='张友士',
    kind='person',
    aliases=['先生'],
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0103', start=0, end=2, quote_hash='sha256:cd98e43da31bb1b90dc152851c85c7d266d47ba97bc5ff7bd137c5920429d467'),
        EvidenceRef(segment_id='hongloumeng_seg_0124', start=10, end=12, quote_hash='sha256:cd98e43da31bb1b90dc152851c85c7d266d47ba97bc5ff7bd137c5920429d467'),
        EvidenceRef(segment_id='hongloumeng_seg_0125', start=0, end=2, quote_hash='sha256:cd98e43da31bb1b90dc152851c85c7d266d47ba97bc5ff7bd137c5920429d467'),
        EvidenceRef(segment_id='hongloumeng_seg_0128', start=6, end=8, quote_hash='sha256:cd98e43da31bb1b90dc152851c85c7d266d47ba97bc5ff7bd137c5920429d467')
    ],
    source_segment_ids=['hongloumeng_seg_0102', 'hongloumeng_seg_0103', 'hongloumeng_seg_0104', 'hongloumeng_seg_0105', 'hongloumeng_seg_0123', 'hongloumeng_seg_0124', 'hongloumeng_seg_0125', 'hongloumeng_seg_0126', 'hongloumeng_seg_0128']
)  # 张友士 (person)

ent_zh_28d0da = Entity(
    id='hongloumeng_ent_0002',
    name='冯紫英',
    kind='person',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0131', start=19, end=22, quote_hash='sha256:f57e9a5dc29c223ed68766e88c3f526337089d3701d3fe3b28953c63b633b356')],
    source_segment_ids=['hongloumeng_seg_0131']
)  # 冯紫英 (person)

ent_zh_f7c68e = Entity(
    id='hongloumeng_ent_0003',
    name='益气养荣补脾和肝汤',
    kind='artifact',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0106', start=0, end=9, quote_hash='sha256:5ea829f012e1a48143d91902d1fa5aaa07afed93415f27db55d56593c8514c60')],
    source_segment_ids=['hongloumeng_seg_0106', 'hongloumeng_seg_0107', 'hongloumeng_seg_0108', 'hongloumeng_seg_0109', 'hongloumeng_seg_0110', 'hongloumeng_seg_0111', 'hongloumeng_seg_0112', 'hongloumeng_seg_0113', 'hongloumeng_seg_0114', 'hongloumeng_seg_0115', 'hongloumeng_seg_0116', 'hongloumeng_seg_0117', 'hongloumeng_seg_0118', 'hongloumeng_seg_0119', 'hongloumeng_seg_0120', 'hongloumeng_seg_0121', 'hongloumeng_seg_0122']
)  # 益气养荣补脾和肝汤 (artifact)

ent_zh_f4edbe = Entity(
    id='hongloumeng_ent_0004',
    name='水亏木旺',
    kind='concept',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0104', start=39, end=46, quote_hash='sha256:a809c9c44ba7a44b3716a673b801eb68afbf047db54c690c728b9ce41efe0077')],
    source_segment_ids=['hongloumeng_seg_0104']
)  # 水亏木旺 (concept)

ent_zh_4e74e8 = Entity(
    id='hongloumeng_ent_0005',
    name='春分',
    kind='concept',
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0126', start=57, end=61, quote_hash='sha256:b39a72a0aa06a27394b5cf03380f1e30f3bfd64cbbcaa37ab2ffd7f1261cfff3')],
    source_segment_ids=['hongloumeng_seg_0126']
)  # 春分 (concept)

