# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Event, EvidenceRef
from .entities import ent_zh_28d0da, ent_zh_3c0877, ent_zh_5ee9d6, ent_zh_72991f, ent_zh_cd67d2
from .text import seg_0041, seg_0053, seg_0059, seg_0064

evt_zh_fbb6dc = Event(
    id='hongloumeng_evt_0004',
    name='贾珍回府',
    kind='occurrence',
    participants=['hongloumeng_ent_0003'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0041', start=6, end=12, quote_hash='sha256:1c1c98f039fae8126884ca2f2c0652add0d68355f1bb2df4bc7a98ee34f953d2')],
    source_segment_ids=['hongloumeng_seg_0041']
)  # 贾珍回府

evt_zh_4e24ad = Event(
    id='hongloumeng_evt_0001',
    name='贾珍差人请张友士为秦氏诊病',
    kind='occurrence',
    participants=['hongloumeng_ent_0003', 'hongloumeng_ent_0001', 'hongloumeng_ent_0002', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0053', start=266, end=276, quote_hash='sha256:cb55bb6d763d79a9bf90c42a5900c3b8a7e5c10ae072b20bda51118d970b53c6')],
    source_segment_ids=['hongloumeng_seg_0053', 'hongloumeng_seg_0061']
)  # 贾珍差人请张友士为秦氏诊病

evt_zh_36c78a = Event(
    id='hongloumeng_evt_0002',
    name='尤氏吩咐贾蓉备寿筵并请西府女眷',
    kind='occurrence',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0002', 'hongloumeng_ent_0003', 'hongloumeng_ent_0004', 'hongloumeng_ent_0008'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0059', start=1, end=15, quote_hash='sha256:ce137184f43929af68951c3b12c1858929b772ff242b1cc6936b53b439499dda')],
    source_segment_ids=['hongloumeng_seg_0058', 'hongloumeng_seg_0059']
)  # 尤氏吩咐贾蓉备寿筵并请西府女眷

evt_zh_496e41 = Event(
    id='hongloumeng_evt_0003',
    name='张友士应允次日到宁府看脉',
    kind='occurrence',
    participants=['hongloumeng_ent_0001', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0064', start=9, end=15, quote_hash='sha256:f7ce4a3e4ff581889a5eb21568ff613ac90de0cff6e0369fd1730b4d629b95ce')],
    source_segment_ids=['hongloumeng_seg_0063', 'hongloumeng_seg_0064', 'hongloumeng_seg_0065']
)  # 张友士应允次日到宁府看脉

