# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Residual, EvidenceRef, IgnoreSegment
from .text import seg_0001, seg_0002, seg_0003, seg_0004, seg_0005, seg_0006, seg_0007, seg_0008, seg_0009, seg_0010, seg_0011, seg_0012, seg_0013, seg_0014, seg_0015, seg_0016, seg_0017, seg_0018, seg_0019, seg_0020, seg_0021, seg_0022, seg_0023, seg_0024, seg_0025, seg_0026, seg_0027, seg_0028, seg_0029, seg_0030, seg_0031, seg_0032, seg_0033, seg_0034, seg_0035, seg_0040, seg_0042, seg_0044, seg_0049, seg_0050, seg_0051, seg_0052, seg_0054, seg_0056, seg_0060, seg_0066, seg_0067, seg_0068, seg_0069, seg_0070, seg_0071, seg_0072, seg_0073, seg_0074, seg_0075, seg_0076, seg_0077, seg_0078, seg_0079, seg_0080, seg_0081, seg_0082, seg_0083, seg_0084, seg_0085, seg_0086, seg_0087, seg_0088, seg_0089, seg_0090, seg_0091, seg_0092, seg_0093, seg_0094, seg_0095, seg_0096, seg_0097, seg_0098, seg_0099, seg_0100, seg_0101, seg_0102, seg_0103, seg_0104, seg_0105, seg_0106, seg_0107, seg_0108, seg_0109, seg_0110, seg_0111, seg_0112, seg_0113, seg_0114, seg_0115, seg_0116, seg_0117, seg_0118, seg_0119, seg_0120, seg_0121, seg_0122, seg_0123, seg_0124, seg_0125, seg_0126, seg_0127, seg_0128, seg_0129, seg_0130, seg_0131, seg_0132, seg_0133

res_seg_0073 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0073',
    segment_id='hongloumeng_seg_0073',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0126 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0126',
    segment_id='hongloumeng_seg_0126',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0032 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0032',
    segment_id='hongloumeng_seg_0032',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0026 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0026',
    segment_id='hongloumeng_seg_0026',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0071 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0071',
    segment_id='hongloumeng_seg_0071',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0069 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0069',
    segment_id='hongloumeng_seg_0069',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0095 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0095',
    segment_id='hongloumeng_seg_0095',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0098 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0098',
    segment_id='hongloumeng_seg_0098',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0089 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0089',
    segment_id='hongloumeng_seg_0089',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0131 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0131',
    segment_id='hongloumeng_seg_0131',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0124 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0124',
    segment_id='hongloumeng_seg_0124',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0002 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0002',
    segment_id='hongloumeng_seg_0002',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0109 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0109',
    segment_id='hongloumeng_seg_0109',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0009 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0009',
    segment_id='hongloumeng_seg_0009',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0118 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0118',
    segment_id='hongloumeng_seg_0118',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0010 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0010',
    segment_id='hongloumeng_seg_0010',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0015 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0015',
    segment_id='hongloumeng_seg_0015',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0044 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0044',
    segment_id='hongloumeng_seg_0044',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0108 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0108',
    segment_id='hongloumeng_seg_0108',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0014 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0014',
    segment_id='hongloumeng_seg_0014',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0074 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0074',
    segment_id='hongloumeng_seg_0074',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0107 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0107',
    segment_id='hongloumeng_seg_0107',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0060 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0060',
    segment_id='hongloumeng_seg_0060',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0011 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0011',
    segment_id='hongloumeng_seg_0011',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0088 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0088',
    segment_id='hongloumeng_seg_0088',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0008 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0008',
    segment_id='hongloumeng_seg_0008',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0056 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0056',
    segment_id='hongloumeng_seg_0056',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0077 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0077',
    segment_id='hongloumeng_seg_0077',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0028 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0028',
    segment_id='hongloumeng_seg_0028',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0007 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0007',
    segment_id='hongloumeng_seg_0007',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0094 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0094',
    segment_id='hongloumeng_seg_0094',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0106 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0106',
    segment_id='hongloumeng_seg_0106',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0027 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0027',
    segment_id='hongloumeng_seg_0027',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0102 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0102',
    segment_id='hongloumeng_seg_0102',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0033 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0033',
    segment_id='hongloumeng_seg_0033',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0067 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0067',
    segment_id='hongloumeng_seg_0067',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0005 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0005',
    segment_id='hongloumeng_seg_0005',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0110 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0110',
    segment_id='hongloumeng_seg_0110',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0129 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0129',
    segment_id='hongloumeng_seg_0129',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0019 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0019',
    segment_id='hongloumeng_seg_0019',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0013 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0013',
    segment_id='hongloumeng_seg_0013',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0099 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0099',
    segment_id='hongloumeng_seg_0099',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0100 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0100',
    segment_id='hongloumeng_seg_0100',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0097 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0097',
    segment_id='hongloumeng_seg_0097',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0081 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0081',
    segment_id='hongloumeng_seg_0081',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0112 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0112',
    segment_id='hongloumeng_seg_0112',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0004 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0004',
    segment_id='hongloumeng_seg_0004',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0133 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0133',
    segment_id='hongloumeng_seg_0133',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0128 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0128',
    segment_id='hongloumeng_seg_0128',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0086 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0086',
    segment_id='hongloumeng_seg_0086',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0083 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0083',
    segment_id='hongloumeng_seg_0083',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0054 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0054',
    segment_id='hongloumeng_seg_0054',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0075 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0075',
    segment_id='hongloumeng_seg_0075',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0029 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0029',
    segment_id='hongloumeng_seg_0029',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0023 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0023',
    segment_id='hongloumeng_seg_0023',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0070 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0070',
    segment_id='hongloumeng_seg_0070',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0072 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0072',
    segment_id='hongloumeng_seg_0072',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0034 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0034',
    segment_id='hongloumeng_seg_0034',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0116 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0116',
    segment_id='hongloumeng_seg_0116',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0051 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0051',
    segment_id='hongloumeng_seg_0051',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0101 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0101',
    segment_id='hongloumeng_seg_0101',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0117 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0117',
    segment_id='hongloumeng_seg_0117',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0076 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0076',
    segment_id='hongloumeng_seg_0076',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0020 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0020',
    segment_id='hongloumeng_seg_0020',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0122 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0122',
    segment_id='hongloumeng_seg_0122',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0105 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0105',
    segment_id='hongloumeng_seg_0105',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0119 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0119',
    segment_id='hongloumeng_seg_0119',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0025 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0025',
    segment_id='hongloumeng_seg_0025',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0125 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0125',
    segment_id='hongloumeng_seg_0125',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0093 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0093',
    segment_id='hongloumeng_seg_0093',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0021 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0021',
    segment_id='hongloumeng_seg_0021',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0052 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0052',
    segment_id='hongloumeng_seg_0052',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0078 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0078',
    segment_id='hongloumeng_seg_0078',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0018 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0018',
    segment_id='hongloumeng_seg_0018',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0035 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0035',
    segment_id='hongloumeng_seg_0035',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0090 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0090',
    segment_id='hongloumeng_seg_0090',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0082 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0082',
    segment_id='hongloumeng_seg_0082',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0121 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0121',
    segment_id='hongloumeng_seg_0121',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0130 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0130',
    segment_id='hongloumeng_seg_0130',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0120 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0120',
    segment_id='hongloumeng_seg_0120',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0111 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0111',
    segment_id='hongloumeng_seg_0111',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0001 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0001',
    segment_id='hongloumeng_seg_0001',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0087 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0087',
    segment_id='hongloumeng_seg_0087',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0080 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0080',
    segment_id='hongloumeng_seg_0080',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0103 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0103',
    segment_id='hongloumeng_seg_0103',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0003 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0003',
    segment_id='hongloumeng_seg_0003',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0084 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0084',
    segment_id='hongloumeng_seg_0084',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0104 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0104',
    segment_id='hongloumeng_seg_0104',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0022 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0022',
    segment_id='hongloumeng_seg_0022',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0040 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0040',
    segment_id='hongloumeng_seg_0040',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0096 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0096',
    segment_id='hongloumeng_seg_0096',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0127 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0127',
    segment_id='hongloumeng_seg_0127',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0085 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0085',
    segment_id='hongloumeng_seg_0085',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0030 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0030',
    segment_id='hongloumeng_seg_0030',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0114 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0114',
    segment_id='hongloumeng_seg_0114',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0031 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0031',
    segment_id='hongloumeng_seg_0031',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0024 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0024',
    segment_id='hongloumeng_seg_0024',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0016 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0016',
    segment_id='hongloumeng_seg_0016',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0079 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0079',
    segment_id='hongloumeng_seg_0079',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0115 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0115',
    segment_id='hongloumeng_seg_0115',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0092 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0092',
    segment_id='hongloumeng_seg_0092',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0006 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0006',
    segment_id='hongloumeng_seg_0006',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0049 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0049',
    segment_id='hongloumeng_seg_0049',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0066 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0066',
    segment_id='hongloumeng_seg_0066',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0132 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0132',
    segment_id='hongloumeng_seg_0132',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0012 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0012',
    segment_id='hongloumeng_seg_0012',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0068 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0068',
    segment_id='hongloumeng_seg_0068',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0113 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0113',
    segment_id='hongloumeng_seg_0113',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0091 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0091',
    segment_id='hongloumeng_seg_0091',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0123 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0123',
    segment_id='hongloumeng_seg_0123',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

res_seg_0017 = Residual(
    id='hongloumeng_res_raw_hongloumeng_seg_0017',
    segment_id='hongloumeng_seg_0017',
    category='structural',
    importance='medium',
    reason='Segment has no semantic object, no Residual, no Ignore — silent loss marker',
    evidence_refs=[]
)  # structural: Segment has no semantic object, no Resid

ign_seg_0040 = IgnoreSegment(id='hongloumeng_ign_0001', segment_id='hongloumeng_seg_0040', reason='短对白无可结构化信息', evidence_refs=[])  # 短对白无可结构化信息

ign_seg_0042 = IgnoreSegment(id='hongloumeng_ign_0002', segment_id='hongloumeng_seg_0042', reason='短对白无可结构化信息', evidence_refs=[])  # 短对白无可结构化信息

ign_seg_0044 = IgnoreSegment(id='hongloumeng_ign_0003', segment_id='hongloumeng_seg_0044', reason='短对白无可结构化信息', evidence_refs=[])  # 短对白无可结构化信息

ign_seg_0050 = IgnoreSegment(id='hongloumeng_ign_0004', segment_id='hongloumeng_seg_0050', reason='短对白无可结构化信息', evidence_refs=[])  # 短对白无可结构化信息

