# Auto-generated by t2c v4.1 — DO NOT EDIT
from t2c.ontology import Document, Block, Segment

doc_hongloumeng = Document(
    id='hongloumeng',
    source_path='data/rawtxt/红楼梦.txt',
    raw_text_hash='sha256:d60a7fcd43e7b994eadb5fc22e6f6a15f0d87bf77fa7f244e2a10ba0305fe969',
    total_length=5116,
    block_count=0,
    created_at='2026-06-08T06:55:04.099819+00:00'
)  # data/rawtxt/红楼梦.txt

seg_0001 = Segment(
    id='hongloumeng_seg_0001',
    doc_id='hongloumeng',
    block_index=0,
    segment_type='heading',
    start_offset=0,
    end_offset=22,
    text_slice='第十回  金寡妇贪利权受辱\u3000张太医论病细穷源',
    hash='sha256:518bdeadbfd018fc30604689a2e3b17b03fe33502757a40d9ea845a20b110887'
)  # 第十回  金寡妇贪利权受辱　张太医论病细穷源

seg_0002 = Segment(
    id='hongloumeng_seg_0002',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=24,
    end_offset=62,
    text_slice='话说金荣因人多势众，又兼贾瑞勒令，赔了不是，给秦钟磕了头，宝玉方才不吵闹了。',
    hash='sha256:f7da51e50c4907ee8c8f1347f3ce6d6ce22ba2985750461185413a22908ac8e1'
)  # 话说金荣因人多势众，又兼贾瑞勒令，赔了不是，给秦钟磕了头，宝玉方才不吵闹了。

seg_0003 = Segment(
    id='hongloumeng_seg_0003',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=62,
    end_offset=117,
    text_slice='大家散了学，金荣回到家中，越想越气，说：“秦钟不过是贾蓉的小舅子，又不是贾家的子孙，附学读书，也不过和我一样。',
    hash='sha256:7542441aee65e1358f9a0e4b7daeb9453082e5731afb5cc5357c02bfbbc381a7'
)  # 大家散了学，金荣回到家中，越想越气，说：“秦钟不过是贾蓉的小舅子，又不是贾家的子...

seg_0004 = Segment(
    id='hongloumeng_seg_0004',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=117,
    end_offset=134,
    text_slice='他因仗着宝玉和他好，他就目中无人。',
    hash='sha256:7ed6970108aca3c8df8c549214b424cf5ceb908b573d85906897d02a272c667b'
)  # 他因仗着宝玉和他好，他就目中无人。

seg_0005 = Segment(
    id='hongloumeng_seg_0005',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=134,
    end_offset=154,
    text_slice='他既是这样，就该行些正经事，人也没的说。',
    hash='sha256:436087dd698b8da1dac1408406eeb99fc2201fc0bc459fe7c3e32b2ee20f75a6'
)  # 他既是这样，就该行些正经事，人也没的说。

seg_0006 = Segment(
    id='hongloumeng_seg_0006',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=154,
    end_offset=179,
    text_slice='他素日又和宝玉鬼鬼祟祟的，只当人都是瞎子，看不见。',
    hash='sha256:c74de8970649ecc9a9ad06b731b3fe02aefc45ca2a3fcd7f350dc1de80f30978'
)  # 他素日又和宝玉鬼鬼祟祟的，只当人都是瞎子，看不见。

seg_0007 = Segment(
    id='hongloumeng_seg_0007',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=179,
    end_offset=198,
    text_slice='今日他又去勾搭人，偏偏的撞在我眼睛里。',
    hash='sha256:a9bf03133de8d95a7a6e284df178092ed8576ec14aec2343e0e65812ec0f5a16'
)  # 今日他又去勾搭人，偏偏的撞在我眼睛里。

seg_0008 = Segment(
    id='hongloumeng_seg_0008',
    doc_id='hongloumeng',
    block_index=1,
    segment_type='sentence',
    start_offset=198,
    end_offset=213,
    text_slice='就是闹出事来，我还怕什么不成？',
    hash='sha256:09480e0ec67fb9af37e7dc3af818ebe66172875fe5f533b6c0e5760e876fc84f'
)  # 就是闹出事来，我还怕什么不成？

seg_0009 = Segment(
    id='hongloumeng_seg_0009',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=216,
    end_offset=245,
    text_slice='他母亲胡氏听见他咕咕嘟嘟的说，因问道：“你又要争什么闲气？',
    hash='sha256:27d6bae188ada452178f94713827d7f0964dea231bba263c226f70cd2e704573'
)  # 他母亲胡氏听见他咕咕嘟嘟的说，因问道：“你又要争什么闲气？

seg_0010 = Segment(
    id='hongloumeng_seg_0010',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=245,
    end_offset=293,
    text_slice='好容易我望你姑妈说了，你姑妈又千方百计的问他们西府里的琏二奶奶跟前说了，你才得了这个念书的地方。',
    hash='sha256:49079de719ac6d78a9a82923e3da50d2aa8414e64bfeaf3c316cdae4e27e7d55'
)  # 好容易我望你姑妈说了，你姑妈又千方百计的问他们西府里的琏二奶奶跟前说了，你才得了...

seg_0011 = Segment(
    id='hongloumeng_seg_0011',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=293,
    end_offset=315,
    text_slice='若不是仗着人家，咱们家里还有力量请得起先生？',
    hash='sha256:a5cd414fe84673b8d9a4ac95091662d35409186a27899108cba0ecdb33dcd6ac'
)  # 若不是仗着人家，咱们家里还有力量请得起先生？

seg_0012 = Segment(
    id='hongloumeng_seg_0012',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=315,
    end_offset=336,
    text_slice='况且人家学里，茶也是现成的，饭也是现成的。',
    hash='sha256:ebabaf58e15053ce92651d01bed600b74b736213d9579158c2b9f1ddd0cce811'
)  # 况且人家学里，茶也是现成的，饭也是现成的。

seg_0013 = Segment(
    id='hongloumeng_seg_0013',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=336,
    end_offset=357,
    text_slice='你这二年在那里念书，家里也省好大的嚼用呢。',
    hash='sha256:1b5b22946189f033e6ed2dbab79e367926bae4f308763feb284e885a43abc28f'
)  # 你这二年在那里念书，家里也省好大的嚼用呢。

seg_0014 = Segment(
    id='hongloumeng_seg_0014',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=357,
    end_offset=372,
    text_slice='省出来的，你又爱穿件鲜明衣服。',
    hash='sha256:627384af3d91e57434de0ab640ad9f2036b74435a98d1261d63545c4304b98f5'
)  # 省出来的，你又爱穿件鲜明衣服。

seg_0015 = Segment(
    id='hongloumeng_seg_0015',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=372,
    end_offset=396,
    text_slice='再者，不是因你在那里念书，你就认得什么薛大爷了？',
    hash='sha256:57aff9c5d229697262817a52e9d24f8a5b657528034793afc3485a2b8ec2a1b1'
)  # 再者，不是因你在那里念书，你就认得什么薛大爷了？

seg_0016 = Segment(
    id='hongloumeng_seg_0016',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=396,
    end_offset=423,
    text_slice='那薛大爷一年不给不给，这二年也帮了咱们有七八十两银子。',
    hash='sha256:9bc56107907177a332f67da64abc6180edad46f3612372c0fb56dc35f74c24df'
)  # 那薛大爷一年不给不给，这二年也帮了咱们有七八十两银子。

seg_0017 = Segment(
    id='hongloumeng_seg_0017',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=423,
    end_offset=458,
    text_slice='你如今要闹出了这个学房，再要找这么个地方，我告诉你说罢，比登天还难呢！',
    hash='sha256:db3711cfbfc73d67d698c57e8cbbe5489c643c4f9ea073db00843d784f1ad67c'
)  # 你如今要闹出了这个学房，再要找这么个地方，我告诉你说罢，比登天还难呢！

seg_0018 = Segment(
    id='hongloumeng_seg_0018',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=458,
    end_offset=482,
    text_slice='你给我老老实实的，玩一会子睡你的觉去，好多着呢。',
    hash='sha256:52d2a719782d35af45db0e93538655567b1010012de3171224036013bf3504e3'
)  # 你给我老老实实的，玩一会子睡你的觉去，好多着呢。

seg_0019 = Segment(
    id='hongloumeng_seg_0019',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=482,
    end_offset=503,
    text_slice='”于是金荣忍气吞声，不多一时，他自去睡了。',
    hash='sha256:e91689f2f493265edf93a078dafcf7e212ea8cbe40b6d05d60a37335b979841b'
)  # ”于是金荣忍气吞声，不多一时，他自去睡了。

seg_0020 = Segment(
    id='hongloumeng_seg_0020',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=503,
    end_offset=512,
    text_slice='次日仍旧上学去了。',
    hash='sha256:b54baf877782f0261d01efaf1adb5d98b2f0e7388b6d789dcf08e350ab952076'
)  # 次日仍旧上学去了。

seg_0021 = Segment(
    id='hongloumeng_seg_0021',
    doc_id='hongloumeng',
    block_index=2,
    segment_type='sentence',
    start_offset=512,
    end_offset=517,
    text_slice='不在话下。',
    hash='sha256:d6924045c03a7abb9192b67f99836b2b60d6a8226f1a7795692af7265875d4c7'
)  # 不在话下。

seg_0022 = Segment(
    id='hongloumeng_seg_0022',
    doc_id='hongloumeng',
    block_index=3,
    segment_type='sentence',
    start_offset=519,
    end_offset=546,
    text_slice='且说他姑娘，原聘给的是贾家‘玉’字辈的嫡派，名唤贾璜。',
    hash='sha256:768e423d768db4c5fe81318837c865ec877e1a7f87dcbc06e004c16904cb764c'
)  # 且说他姑娘，原聘给的是贾家‘玉’字辈的嫡派，名唤贾璜。

seg_0023 = Segment(
    id='hongloumeng_seg_0023',
    doc_id='hongloumeng',
    block_index=3,
    segment_type='sentence',
    start_offset=546,
    end_offset=570,
    text_slice='但其族人那里皆能像宁、荣二府的富势，原不用细说。',
    hash='sha256:94fd047602eeda50f20810c5a3729043428a7726381db262d9af5cc675408958'
)  # 但其族人那里皆能像宁、荣二府的富势，原不用细说。

seg_0024 = Segment(
    id='hongloumeng_seg_0024',
    doc_id='hongloumeng',
    block_index=3,
    segment_type='sentence',
    start_offset=570,
    end_offset=633,
    text_slice='这贾璜夫妻，守着些小的产业，又时常到宁、荣二府里去请请安，又会奉承凤姐儿并尤氏，所以凤姐、尤氏也时常资助资助他，方能如此度日。',
    hash='sha256:61c67c4b15cefcda4755cd7bb0f4eb640d125f78299fbdf44eb3db639b3d3d70'
)  # 这贾璜夫妻，守着些小的产业，又时常到宁、荣二府里去请请安，又会奉承凤姐儿并尤氏，...

seg_0025 = Segment(
    id='hongloumeng_seg_0025',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='sentence',
    start_offset=635,
    end_offset=685,
    text_slice='却说这日贾璜之妻金氏因遇天气晴明，又值家中无事，遂带了一个婆子，坐上车，来家里走走，瞧瞧寡嫂并侄儿。',
    hash='sha256:61ebbac4a91b6ec4430ec62430fad084ec6dfbad2da290355263b10d37b3973f'
)  # 却说这日贾璜之妻金氏因遇天气晴明，又值家中无事，遂带了一个婆子，坐上车，来家里走...

seg_0026 = Segment(
    id='hongloumeng_seg_0026',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='sentence',
    start_offset=685,
    end_offset=727,
    text_slice='闲话之间，金荣的母亲偏提起昨日贾家学房里的那事，从头至尾，一五一十都向他小姑子说了。',
    hash='sha256:6525791c9b0210419d6f236bb48087ad9d36bef45d1ea5f85d4f79fa50bfa8bd'
)  # 闲话之间，金荣的母亲偏提起昨日贾家学房里的那事，从头至尾，一五一十都向他小姑子说...

seg_0027 = Segment(
    id='hongloumeng_seg_0027',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='dialogue',
    start_offset=751,
    end_offset=850,
    text_slice='“这秦钟小崽子是贾门的亲戚，难道荣儿不是贾门的亲戚？人都别忒势利了，况且都做的是什么有脸的好事！就是宝玉，也犯不上向着他到这个地。等我去到东府瞧瞧我们珍大奶奶，再向秦钟他姐姐说说，叫她评评这个理。”',
    hash='sha256:01390ecb6f9036b6c7079cc5b39723fda9cf76f6fa4ede3fed8e812e5256d550'
)  # “这秦钟小崽子是贾门的亲戚，难道荣儿不是贾门的亲戚？人都别忒势利了，况且都做的是...

seg_0028 = Segment(
    id='hongloumeng_seg_0028',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='sentence',
    start_offset=850,
    end_offset=871,
    text_slice='这金荣的母亲听了这话，急得了不得，忙说道：',
    hash='sha256:d349b26f7ea2d9ea157e3f3b2ca6caceae310205e7e82561de76ba3f615a79ff'
)  # 这金荣的母亲听了这话，急得了不得，忙说道：

seg_0029 = Segment(
    id='hongloumeng_seg_0029',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='dialogue',
    start_offset=871,
    end_offset=953,
    text_slice='“这都是我的嘴快，告诉了姑奶奶，求姑奶奶快别说去去，别管他们谁是谁非。倘或闹起来，怎么在那里站得住？若是站不住，家里不但不能请先生，反倒在他身上添出许多嚼用来呢。”',
    hash='sha256:2f46914d7558617d59359173971545133ed08cbdc1759657d26521f189a8d24a'
)  # “这都是我的嘴快，告诉了姑奶奶，求姑奶奶快别说去去，别管他们谁是谁非。倘或闹起来...

seg_0030 = Segment(
    id='hongloumeng_seg_0030',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='sentence',
    start_offset=953,
    end_offset=963,
    text_slice='璜大奶奶听了，说道：',
    hash='sha256:33d8a1254085d5892041e7874df1ea2f400b05bed9ab7560ef974e0051d3628a'
)  # 璜大奶奶听了，说道：

seg_0031 = Segment(
    id='hongloumeng_seg_0031',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='dialogue',
    start_offset=963,
    end_offset=984,
    text_slice='“那里管得许多！你等我说了，看是怎么样。”',
    hash='sha256:6e7c357a2a9d003104d4de9086a85c650d7e763b00fbaa9aa63034fc94ad8240'
)  # “那里管得许多！你等我说了，看是怎么样。”

seg_0032 = Segment(
    id='hongloumeng_seg_0032',
    doc_id='hongloumeng',
    block_index=4,
    segment_type='sentence',
    start_offset=984,
    end_offset=1011,
    text_slice='也不容她嫂子劝，一面叫老婆子瞧了车，就坐上往宁府里来。',
    hash='sha256:4990729bee9468458e575dd729c0b18562f99463a0a1519804fa8a23a8170e95'
)  # 也不容她嫂子劝，一面叫老婆子瞧了车，就坐上往宁府里来。

seg_0033 = Segment(
    id='hongloumeng_seg_0033',
    doc_id='hongloumeng',
    block_index=5,
    segment_type='sentence',
    start_offset=1013,
    end_offset=1046,
    text_slice='到了宁府，进了车门，到了东边小角门前下了车，进去见了贾珍之妻尤氏。',
    hash='sha256:3ceba19833b171216270d889f200c7f9ec187b897f29c5b73d109265a46ad758'
)  # 到了宁府，进了车门，到了东边小角门前下了车，进去见了贾珍之妻尤氏。

seg_0034 = Segment(
    id='hongloumeng_seg_0034',
    doc_id='hongloumeng',
    block_index=5,
    segment_type='dialogue',
    start_offset=1071,
    end_offset=1084,
    text_slice='“今日怎么没见蓉大奶奶？”',
    hash='sha256:ec94d4915fa97253c166d01402cf225fb7eff299d98aa47c3e44a69a7cdeb7cc'
)  # “今日怎么没见蓉大奶奶？”

seg_0035 = Segment(
    id='hongloumeng_seg_0035',
    doc_id='hongloumeng',
    block_index=5,
    segment_type='sentence',
    start_offset=1084,
    end_offset=1089,
    text_slice='尤氏说道：',
    hash='sha256:948c68618582760ae88e0622ea5a6cd996a015227f98f0f2d43c60967b173e69'
)  # 尤氏说道：

seg_0036 = Segment(
    id='hongloumeng_seg_0036',
    doc_id='hongloumeng',
    block_index=5,
    segment_type='dialogue',
    start_offset=1089,
    end_offset=1786,
    text_slice='“她这些日子不知怎么着，经期有两个多月没来。叫大夫瞧了，又说并不是喜。那两日，到了下半天就懒待动，话也懒待说，眼神也发眩。我说她：‘你且不必拘礼，早晚不必照例上来，你竟好生养养罢。就是有亲戚一家儿来，有我呢。就有长辈们怪你，等我替你告诉。’连蓉哥我都嘱咐了，我说：‘你不许累掯她，不许招她生气，叫她静静的养养就好了。她要想什么吃，只管到我这里取来。倘或我这里没有，只管望你琏二婶子那里要去。倘或她有个好歹，你再要娶这么一个媳妇，这么个模样儿，这么个性情的人儿，打着灯笼也没地方找去。’她这为人行事，哪个亲戚、哪个一家的长辈不喜欢她？所以我这两日好不烦心，焦得我了不得。偏偏今儿早晨她兄弟来瞧他，谁知那小孩子家不知好歹，看见他姐姐身上不大爽快，就有事也不当告诉她，别说是这么一点子小事，就是你受了一万分的委曲，也不该向她说才是。谁知他们昨儿学房里打架，不知是那里附学来的一个人欺侮了他了。里头还有些不干不净的话，都告诉了他姐姐。婶子，你是知道那媳妇的，虽则见了人有说有笑，会行事儿，她可心细，心又重，不拘听见个什么话儿，都要度量个三日五夜才罢。这病就是打这个秉性上头思虑出来的。今儿听见有人欺负了她兄弟，又是恼，又是气。恼的是那群混帐狐朋狗友的扯是搬非、调三惑四的那些个；气的是她兄弟不学好，不上心读书，以致如此学里吵闹。她听了这事，今日索性连早饭也没吃。我听见了，我方到她那边安慰了她一会子，又劝解了她兄弟一会子。我叫她兄弟到那边府里找宝玉去了。我才看着她吃了半盏燕窝汤，我才过来了。婶子，你说我心焦不心焦？况且如今又没个好大夫，我想到他这病上，我心里倒像针扎似的。你们知道有什么好大夫没有？”',
    hash='sha256:1fb5e4d666f52c374d8e7eacf44a2ef6da75e3863bf554798e8bde54cb9b05ce'
)  # “她这些日子不知怎么着，经期有两个多月没来。叫大夫瞧了，又说并不是喜。那两日，到...

seg_0037 = Segment(
    id='hongloumeng_seg_0037',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=1788,
    end_offset=1831,
    text_slice='金氏听了这半日话，把方才在她嫂子家的那一团要向秦氏论理的盛气，早吓得都丢在爪洼国去了。',
    hash='sha256:e5f1812f114e2c28fb39c9cf9bda323c62bd1e67f2ceaa5e2b836deaa8cee6e4'
)  # 金氏听了这半日话，把方才在她嫂子家的那一团要向秦氏论理的盛气，早吓得都丢在爪洼国...

seg_0038 = Segment(
    id='hongloumeng_seg_0038',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='dialogue',
    start_offset=1851,
    end_offset=1916,
    text_slice='“我们这么听着，实在也没听见人说有个好大夫。如今听起大奶奶这个来，定不得还是喜呢。嫂子倒别教人混治。倘或认错了，这可是了不得的！”',
    hash='sha256:ca300d8a3f7bdf7ec23e4556932d2e74d58313417d2f206294675f8fec3af988'
)  # “我们这么听着，实在也没听见人说有个好大夫。如今听起大奶奶这个来，定不得还是喜呢...

seg_0039 = Segment(
    id='hongloumeng_seg_0039',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=1916,
    end_offset=1920,
    text_slice='尤氏道：',
    hash='sha256:a770cb189e69039a617afc79b3f86391dc741bed11673a456877bf606c7c1dd3'
)  # 尤氏道：

seg_0040 = Segment(
    id='hongloumeng_seg_0040',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='dialogue',
    start_offset=1920,
    end_offset=1927,
    text_slice='“可不是呢。”',
    hash='sha256:49522f70ca910a1c104be9a03524e1068d7ec1c8c465e01d8f3027e79661f7ba'
)  # “可不是呢。”

seg_0041 = Segment(
    id='hongloumeng_seg_0041',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=1927,
    end_offset=1952,
    text_slice='正说话之间，贾珍从外进来，见了金氏，便向尤氏问道：',
    hash='sha256:6af6218631b78ef8c464d5e8b525e2adaa0579eafe57b8bc38c22bccd36fdf18'
)  # 正说话之间，贾珍从外进来，见了金氏，便向尤氏问道：

seg_0042 = Segment(
    id='hongloumeng_seg_0042',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='dialogue',
    start_offset=1952,
    end_offset=1963,
    text_slice='“这不是璜大奶奶么？”',
    hash='sha256:7a913b688c605bd3b774591736378caa1f0798cb33bff1f7a618ea11732ac0d6'
)  # “这不是璜大奶奶么？”

seg_0043 = Segment(
    id='hongloumeng_seg_0043',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=1963,
    end_offset=1974,
    text_slice='金氏向前给贾珍请了安。',
    hash='sha256:18ea4589e86ac1f128c5b901e5ab3f88123abae64cea9fd36255baeb46127f9c'
)  # 金氏向前给贾珍请了安。

seg_0044 = Segment(
    id='hongloumeng_seg_0044',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='dialogue',
    start_offset=1982,
    end_offset=1994,
    text_slice='“让这大妹妹吃了饭去。”',
    hash='sha256:52eee91be567618474dae4ca089e6cac331c4d92ddf459868906e83a75bfe16e'
)  # “让这大妹妹吃了饭去。”

seg_0045 = Segment(
    id='hongloumeng_seg_0045',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=1994,
    end_offset=2007,
    text_slice='贾珍说着话，就过那屋里了。',
    hash='sha256:675cc191a2dfffb51e51bed5b477aea2c2339d54a4c852458e09fa5c01797ba2'
)  # 贾珍说着话，就过那屋里了。

seg_0046 = Segment(
    id='hongloumeng_seg_0046',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=2007,
    end_offset=2050,
    text_slice='金氏此来，原要向秦氏说说秦钟欺负了她侄儿的事，听见秦氏有病，不但不能说，亦且不敢提了。',
    hash='sha256:c2af25ed4797154345c3ef6cfd8cfc59a542375fa8835a6d15cdc2c4ef903e8c'
)  # 金氏此来，原要向秦氏说说秦钟欺负了她侄儿的事，听见秦氏有病，不但不能说，亦且不敢...

seg_0047 = Segment(
    id='hongloumeng_seg_0047',
    doc_id='hongloumeng',
    block_index=6,
    segment_type='sentence',
    start_offset=2050,
    end_offset=2084,
    text_slice='况且贾珍、尤氏又待得很好，反转怒为喜的，又说了一会子话儿，方家去了。',
    hash='sha256:00e2c78e7282baeb1f0b8795af28c6eafa470a4423e413413dca47570c56ab31'
)  # 况且贾珍、尤氏又待得很好，反转怒为喜的，又说了一会子话儿，方家去了。

seg_0048 = Segment(
    id='hongloumeng_seg_0048',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='sentence',
    start_offset=2086,
    end_offset=2104,
    text_slice='金氏去后，贾珍方过来坐下，问尤氏道：',
    hash='sha256:9a44e75ff5ff8a1594efb2303ceca312b28f9edd6500b6d9c867a394c24121f4'
)  # 金氏去后，贾珍方过来坐下，问尤氏道：

seg_0049 = Segment(
    id='hongloumeng_seg_0049',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='dialogue',
    start_offset=2104,
    end_offset=2120,
    text_slice='“今日她来，有什么说的事情么？”',
    hash='sha256:af492ed95fdf1b148f309eef383ff6092a289638a9c70ea61f083c5714ba86ad'
)  # “今日她来，有什么说的事情么？”

seg_0050 = Segment(
    id='hongloumeng_seg_0050',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='sentence',
    start_offset=2120,
    end_offset=2125,
    text_slice='尤氏答道：',
    hash='sha256:84c0770173cd6bd5e9d087dd8413f0a41183f3bab1a0106126f5d7c33ae6c876'
)  # 尤氏答道：

seg_0051 = Segment(
    id='hongloumeng_seg_0051',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='dialogue',
    start_offset=2125,
    end_offset=2379,
    text_slice='“倒没说什么。一进来的时候，脸上倒像有些着了恼的气色似的，及说了半天话，又提起媳妇这病，她倒渐渐的气色平定了。你又叫让她吃饭，她听见媳妇这么病，也不好意思只管坐着，又说了几句闲话儿就去了，倒没有求什么事。如今且说媳妇这病，你到哪里寻个好大夫来给她瞧瞧要紧，可别耽误了！现今咱们家走的这群大夫，那里要得，一个个都是听着人的口气儿，人怎么说，他也添几句文话儿说一遍。可倒殷勤得很，三四个人一日轮流着，倒有四五遍来看脉。他们大家商量着立个方子，吃了也不见效，倒弄得一日换四五遍衣裳，坐起来见大夫，其实于病人无益。”',
    hash='sha256:e0e769c1a03742890a0787d79703f39003b39838256003bd15a283e6b41cccf6'
)  # “倒没说什么。一进来的时候，脸上倒像有些着了恼的气色似的，及说了半天话，又提起媳...

seg_0052 = Segment(
    id='hongloumeng_seg_0052',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='sentence',
    start_offset=2379,
    end_offset=2384,
    text_slice='贾珍说道：',
    hash='sha256:23a345d19efbb6393c6cb411d091b1002fe72377b8854373a2016389d0955967'
)  # 贾珍说道：

seg_0053 = Segment(
    id='hongloumeng_seg_0053',
    doc_id='hongloumeng',
    block_index=7,
    segment_type='dialogue',
    start_offset=2384,
    end_offset=2719,
    text_slice='“可是。这孩子也胡涂，何必脱脱换换的，倘或了凉，更添一层病，那还了得！衣裳任凭是什么好的，可又值什么！孩子的身子要紧，就是一天穿一套新的，也不值什么。我正进来要告诉你：方才冯紫英来看我，他见我有些抑郁之色，问我是怎么了。我才告诉他说，媳妇忽然身子有好大的不爽快，因为不得个好太医，断不透是喜是病，又不知有妨碍无妨碍，所以我这两日心里着实着急。冯紫英因说起他有一个幼时从学的先生，姓张名友士，学问最渊博的，更兼医理极深，且能断人的生死。今年是上京给他儿子来捐官，现在他家住着呢。这么看来，竟是合该媳妇的病在他手里除灾，亦未可知。我即刻差人拿我的名帖请去了。今日倘或天晚了不能来，明日想必一定来。况且冯紫英又即刻回家，亲自去求他，务必叫他来瞧瞧。等这个张先生来瞧了再说罢。”',
    hash='sha256:859d627f4790c0d5fe5410c6514d3c21f6684f267c44a720edcb23b0a0c39f6e'
)  # “可是。这孩子也胡涂，何必脱脱换换的，倘或了凉，更添一层病，那还了得！衣裳任凭是...

seg_0054 = Segment(
    id='hongloumeng_seg_0054',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='sentence',
    start_offset=2721,
    end_offset=2735,
    text_slice='尤氏听了，心中甚喜，因说道：',
    hash='sha256:45aff7cbb0373edfeb89cf51284f61f20e20bfc6193599d7d78870bf8afb55a0'
)  # 尤氏听了，心中甚喜，因说道：

seg_0055 = Segment(
    id='hongloumeng_seg_0055',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='dialogue',
    start_offset=2735,
    end_offset=2752,
    text_slice='“后日是太爷的寿日，到底怎么办？”',
    hash='sha256:d6e3cd46655f772a0792134dbb1df7e11d6da2da397dc9a95fe3da390cf0d2a5'
)  # “后日是太爷的寿日，到底怎么办？”

seg_0056 = Segment(
    id='hongloumeng_seg_0056',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='sentence',
    start_offset=2752,
    end_offset=2757,
    text_slice='贾珍说道：',
    hash='sha256:23a345d19efbb6393c6cb411d091b1002fe72377b8854373a2016389d0955967'
)  # 贾珍说道：

seg_0057 = Segment(
    id='hongloumeng_seg_0057',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='dialogue',
    start_offset=2757,
    end_offset=3013,
    text_slice='“我方才到了太爷那里去请安，兼请太爷来家来受一受一家子的礼。太爷因说道：‘我是清净惯了的，我不愿意往你们那样是非场中去闹去。你们必定说是我的生日，要叫我去受众人些头，莫过你把我从前注的《阴骘文》给我叫人好好的写出来刻了，比叫我无故受众人的头还强百倍呢。倘或后日这两日一家子要来，你就在家里好好的款待他们就是了。也不必给我送什么东西来，连你后日也不必来，你要心中不安，你今日就给我磕了头去。倘或后日你要来，又跟随多少人来闹我，我必和你不依。’如此说了又说，后日我是再不敢去的了。且叫来升来，吩咐他预备两日的筵席。”',
    hash='sha256:575e3d31ce1ce5a022ef7e9ad52288b5aa7e5686083855a371d4ee34bd17ab77'
)  # “我方才到了太爷那里去请安，兼请太爷来家来受一受一家子的礼。太爷因说道：‘我是清...

seg_0058 = Segment(
    id='hongloumeng_seg_0058',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='sentence',
    start_offset=3013,
    end_offset=3024,
    text_slice='尤氏因叫人叫了贾蓉来：',
    hash='sha256:d6a8d0abb35224ec9bc61363420a8860be28e723055e9bc8d1fb913247ea453e'
)  # 尤氏因叫人叫了贾蓉来：

seg_0059 = Segment(
    id='hongloumeng_seg_0059',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='dialogue',
    start_offset=3024,
    end_offset=3127,
    text_slice='“吩咐来升照旧例预备两日的筵席，要丰丰富富的。你再亲自到西府里去请老太太，大太太，二太太和你琏二婶子来逛逛。你父亲今日又听见一个好大夫，业已打发人请去了，想必明日必来。你可将他这些日子的病症细细的告诉他。”',
    hash='sha256:5dd060f940eb64c75c05828377d4c6e89e7933b25e166c3061db4b4966501534'
)  # “吩咐来升照旧例预备两日的筵席，要丰丰富富的。你再亲自到西府里去请老太太，大太太...

seg_0060 = Segment(
    id='hongloumeng_seg_0060',
    doc_id='hongloumeng',
    block_index=8,
    segment_type='sentence',
    start_offset=3127,
    end_offset=3138,
    text_slice='贾蓉一一的答应出去了。',
    hash='sha256:44e010d798f190faab4ec5040ab158cdc1dc5835030252912e9bde8428ad248a'
)  # 贾蓉一一的答应出去了。

seg_0061 = Segment(
    id='hongloumeng_seg_0061',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3140,
    end_offset=3190,
    text_slice='正遇着方才去冯紫英家请那先生的小子回来了，因回道：“奴才方才到了冯大爷家，拿了老爷的名帖请那先生去。',
    hash='sha256:ac7715b777cb5a7b147988c915413709565f78ae29699cafe2d33d7dda0ca372'
)  # 正遇着方才去冯紫英家请那先生的小子回来了，因回道：“奴才方才到了冯大爷家，拿了老...

seg_0062 = Segment(
    id='hongloumeng_seg_0062',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3190,
    end_offset=3209,
    text_slice='那先生说道：‘方才这里大爷也向我说了。',
    hash='sha256:e9bf6c5ca1dd593886d4b188e878fe3b11dcff277e426ac1586718a24b296f3b'
)  # 那先生说道：‘方才这里大爷也向我说了。

seg_0063 = Segment(
    id='hongloumeng_seg_0063',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3209,
    end_offset=3249,
    text_slice='但是今日拜了一天的客，才回到家，此时精神实在不能支持，就是去到府上，也不能看脉。',
    hash='sha256:c694fa4fc85a5b795a2fa8743a3e5869b2418f46be31a7e5422781ad96ca72ff'
)  # 但是今日拜了一天的客，才回到家，此时精神实在不能支持，就是去到府上，也不能看脉。

seg_0064 = Segment(
    id='hongloumeng_seg_0064',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3249,
    end_offset=3265,
    text_slice='’他说等调息一夜，明日务必到府。',
    hash='sha256:2a30d68c57462763b188d38c354fd41c08ead107f9199d832a5171cc4598d088'
)  # ’他说等调息一夜，明日务必到府。

seg_0065 = Segment(
    id='hongloumeng_seg_0065',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3265,
    end_offset=3321,
    text_slice='他又说，他‘医学浅薄，本不敢当此重荐，因我们冯大爷和府上的大人既已如此说了，又不得不去，你先代我回明大人就是了。',
    hash='sha256:31bd1446b2198f3b9d914e602df12fb91eec381459f1597f6a11bdfd2eac9f50'
)  # 他又说，他‘医学浅薄，本不敢当此重荐，因我们冯大爷和府上的大人既已如此说了，又不...

seg_0066 = Segment(
    id='hongloumeng_seg_0066',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3321,
    end_offset=3331,
    text_slice='大人的名帖实不敢当。',
    hash='sha256:52933e92332f363b6988629e19c2eeec487b12a26edb00800116e6031c51f69c'
)  # 大人的名帖实不敢当。

seg_0067 = Segment(
    id='hongloumeng_seg_0067',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3331,
    end_offset=3341,
    text_slice='’仍叫奴才拿回来了。',
    hash='sha256:a641a6364ffda72040b8e7d68524cf3543e9ad4c4722dbfcb7249a0c85ddcd14'
)  # ’仍叫奴才拿回来了。

seg_0068 = Segment(
    id='hongloumeng_seg_0068',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3341,
    end_offset=3352,
    text_slice='哥儿替奴才回一声儿罢。',
    hash='sha256:7ffaa95fa5844f9513f214f5cb9a0085111244159ed04649749810769eef6129'
)  # 哥儿替奴才回一声儿罢。

seg_0069 = Segment(
    id='hongloumeng_seg_0069',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3352,
    end_offset=3393,
    text_slice='”贾蓉复转身进去，回了贾珍、尤氏的话，方出来叫了来升来，吩咐他预备两日的筵席的话。',
    hash='sha256:a2f37298a3939b4f3bdd71b1d7b34f0417dd53700c1ec2c187ff1a238df3f097'
)  # ”贾蓉复转身进去，回了贾珍、尤氏的话，方出来叫了来升来，吩咐他预备两日的筵席的话...

seg_0070 = Segment(
    id='hongloumeng_seg_0070',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3393,
    end_offset=3405,
    text_slice='来升听毕，自去照例料理。',
    hash='sha256:77966a7205d73a0def088c620ed5bdbff16d209ec8ff811611e9025eeae30b42'
)  # 来升听毕，自去照例料理。

seg_0071 = Segment(
    id='hongloumeng_seg_0071',
    doc_id='hongloumeng',
    block_index=9,
    segment_type='sentence',
    start_offset=3405,
    end_offset=3410,
    text_slice='不在话下。',
    hash='sha256:d6924045c03a7abb9192b67f99836b2b60d6a8226f1a7795692af7265875d4c7'
)  # 不在话下。

seg_0072 = Segment(
    id='hongloumeng_seg_0072',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='sentence',
    start_offset=3412,
    end_offset=3423,
    text_slice='且说次日午间，人回道：',
    hash='sha256:4d2f5dca8f5371f8f7e32f29f01eba80b55b84c0e3b0ec2df11e0a7e28250b38'
)  # 且说次日午间，人回道：

seg_0073 = Segment(
    id='hongloumeng_seg_0073',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='dialogue',
    start_offset=3423,
    end_offset=3434,
    text_slice='“请的那张先生来了。”',
    hash='sha256:0ccfa3285a360a5722a69000d9df67b3bc5b73944b49df59e803b47e4d50b040'
)  # “请的那张先生来了。”

seg_0074 = Segment(
    id='hongloumeng_seg_0074',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='sentence',
    start_offset=3434,
    end_offset=3444,
    text_slice='贾珍遂延入大厅坐下。',
    hash='sha256:d902514d84dc7386c82a0a386955a1e9615e820c7f93a406566a6f1a6043d088'
)  # 贾珍遂延入大厅坐下。

seg_0075 = Segment(
    id='hongloumeng_seg_0075',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='dialogue',
    start_offset=3452,
    end_offset=3485,
    text_slice='“昨承冯大爷示知老先生人品学问，又兼深通医学之至，小弟不胜钦仰！”',
    hash='sha256:5458f6f9f503d668d8f2c4729219f6a2975bd0ddc2c83c7a8e3ea87e78d15431'
)  # “昨承冯大爷示知老先生人品学问，又兼深通医学之至，小弟不胜钦仰！”

seg_0076 = Segment(
    id='hongloumeng_seg_0076',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='sentence',
    start_offset=3485,
    end_offset=3490,
    text_slice='张先生道：',
    hash='sha256:2c12be820d0152cca057ab37228bf3b34b42551c6c0033627d5eaa191b6fa779'
)  # 张先生道：

seg_0077 = Segment(
    id='hongloumeng_seg_0077',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='dialogue',
    start_offset=3490,
    end_offset=3543,
    text_slice='“晚生粗鄙下士，本知见浅陋。昨因冯大爷示知，大人家第谦恭下士，又承呼唤，敢不奉命。但毫无实学，倍增颜汗。”',
    hash='sha256:0115118839ef749d9adee3e0855449db399624bb2b608a07578e630ba68a01ea'
)  # “晚生粗鄙下士，本知见浅陋。昨因冯大爷示知，大人家第谦恭下士，又承呼唤，敢不奉命...

seg_0078 = Segment(
    id='hongloumeng_seg_0078',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='sentence',
    start_offset=3543,
    end_offset=3547,
    text_slice='贾珍道：',
    hash='sha256:f8a8aedd2ce9740ac4855922a831abf328af70a340beca97664f0fbd7e28f010'
)  # 贾珍道：

seg_0079 = Segment(
    id='hongloumeng_seg_0079',
    doc_id='hongloumeng',
    block_index=10,
    segment_type='dialogue',
    start_offset=3547,
    end_offset=3577,
    text_slice='“先生何必过谦。就请先生进去看看儿妇，仰仗高明，以释下怀。”',
    hash='sha256:ea7f5c226e71039d5bd89a45f89584a1857dc06f3b0651f271ed3de2923b6491'
)  # “先生何必过谦。就请先生进去看看儿妇，仰仗高明，以释下怀。”

seg_0080 = Segment(
    id='hongloumeng_seg_0080',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3579,
    end_offset=3589,
    text_slice='于是，贾蓉同了进去。',
    hash='sha256:b7a0a2f1b07e477bff318cffc80317b52527fc6cd5b7652c33fabe1b5e5ba55b'
)  # 于是，贾蓉同了进去。

seg_0081 = Segment(
    id='hongloumeng_seg_0081',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='dialogue',
    start_offset=3607,
    end_offset=3617,
    text_slice='“这就是尊夫人了？”',
    hash='sha256:a81ff5c7059f2d1073a935bd418e0756e3e7bb4905400b875b3cd29cc015c6ac'
)  # “这就是尊夫人了？”

seg_0082 = Segment(
    id='hongloumeng_seg_0082',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3617,
    end_offset=3621,
    text_slice='贾蓉道：',
    hash='sha256:9d929f43885abe4aff1a05b3791ed0df40e139d8351539fc7a58d2639d3f2a17'
)  # 贾蓉道：

seg_0083 = Segment(
    id='hongloumeng_seg_0083',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='dialogue',
    start_offset=3621,
    end_offset=3648,
    text_slice='“正是。请先生坐下，让我把贱内的病说一说再看脉如何？”',
    hash='sha256:30713c76e8f3f4d3ac1ce733b7b6e7e1e0a6bae94e3273a80d6f8487d3182806'
)  # “正是。请先生坐下，让我把贱内的病说一说再看脉如何？”

seg_0084 = Segment(
    id='hongloumeng_seg_0084',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3648,
    end_offset=3653,
    text_slice='那先生道：',
    hash='sha256:2b20f35c9b0714ae400d19a7ed9f707c0ea186c6066662537cd8ac6cafbba378'
)  # 那先生道：

seg_0085 = Segment(
    id='hongloumeng_seg_0085',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='dialogue',
    start_offset=3653,
    end_offset=3768,
    text_slice='“依小弟的意思，竟先看过脉，再说的为是。我是初造尊府的，本也不晓得什么，但是我们冯大爷务必叫小弟过来看看，小弟所以不得不来。如今看了脉息，看小弟说得是不是，再将这些日子的病势讲一讲，大家斟酌一个方儿，可用不可用，那时大爷再定夺。”',
    hash='sha256:4e0956be8fb458c2dbad2fe5d798ced2b39c8a611fefc265e7ae1c52c134dd49'
)  # “依小弟的意思，竟先看过脉，再说的为是。我是初造尊府的，本也不晓得什么，但是我们...

seg_0086 = Segment(
    id='hongloumeng_seg_0086',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3768,
    end_offset=3772,
    text_slice='贾蓉道：',
    hash='sha256:9d929f43885abe4aff1a05b3791ed0df40e139d8351539fc7a58d2639d3f2a17'
)  # 贾蓉道：

seg_0087 = Segment(
    id='hongloumeng_seg_0087',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='dialogue',
    start_offset=3772,
    end_offset=3814,
    text_slice='“先生实在高明，如今恨相见之晚。就请先生看一看脉息，可治不可治，以便使家父母放心。”',
    hash='sha256:18d1efda1affcc367b16e4941ba168cea43ae3ab2c760b8cb71ed1a981bb4b86'
)  # “先生实在高明，如今恨相见之晚。就请先生看一看脉息，可治不可治，以便使家父母放心...

seg_0088 = Segment(
    id='hongloumeng_seg_0088',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3814,
    end_offset=3849,
    text_slice='于是家下媳妇们捧过大迎枕来，一面给秦氏靠着，一面拉着袖口，露出手腕来。',
    hash='sha256:8205c6195bd93e1d8ea28e07d8f54b4dd95d7b989cb81f9c75f168051649c181'
)  # 于是家下媳妇们捧过大迎枕来，一面给秦氏靠着，一面拉着袖口，露出手腕来。

seg_0089 = Segment(
    id='hongloumeng_seg_0089',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='sentence',
    start_offset=3849,
    end_offset=3889,
    text_slice='先生方伸手按在右手脉上，调息了至数，宁神细诊了半刻的工夫；方换过左手，亦复如是。',
    hash='sha256:3e9cdd9a3378e57b3dcf39fa3164569c434150c9d2da11b637aa6e44141ece9c'
)  # 先生方伸手按在右手脉上，调息了至数，宁神细诊了半刻的工夫；方换过左手，亦复如是。

seg_0090 = Segment(
    id='hongloumeng_seg_0090',
    doc_id='hongloumeng',
    block_index=11,
    segment_type='dialogue',
    start_offset=3897,
    end_offset=3906,
    text_slice='“我们外边坐罢。”',
    hash='sha256:d2c413c433433db28ff11fee440b9ab3b53cd4db3a252765afb4e10df42cb3da'
)  # “我们外边坐罢。”

seg_0091 = Segment(
    id='hongloumeng_seg_0091',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='sentence',
    start_offset=3908,
    end_offset=3934,
    text_slice='贾蓉于是同先生到外边屋里炕上坐了，一个婆子端了茶来。',
    hash='sha256:188da091df28f96274940beefd336d4110cf14f76a5652b2664c665fd7dde9b7'
)  # 贾蓉于是同先生到外边屋里炕上坐了，一个婆子端了茶来。

seg_0092 = Segment(
    id='hongloumeng_seg_0092',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='dialogue',
    start_offset=3938,
    end_offset=3945,
    text_slice='“先生请茶。”',
    hash='sha256:c73127d299cf5adf5b8140fbc5d79cd27181a612d3adb92413c2c3240f819db6'
)  # “先生请茶。”

seg_0093 = Segment(
    id='hongloumeng_seg_0093',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='sentence',
    start_offset=3945,
    end_offset=3958,
    text_slice='于是陪先生吃了茶，遂问道：',
    hash='sha256:dd18dcf190647369efddf767e3bedb9b2a2659e3e67090846247e74e67483aea'
)  # 于是陪先生吃了茶，遂问道：

seg_0094 = Segment(
    id='hongloumeng_seg_0094',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='dialogue',
    start_offset=3958,
    end_offset=3974,
    text_slice='“先生看这脉息，还治得治不得？”',
    hash='sha256:e43149b31df02aa0e29d127fcfdd502874ee6e20d120c9e8c956c71c32e1c381'
)  # “先生看这脉息，还治得治不得？”

seg_0095 = Segment(
    id='hongloumeng_seg_0095',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='sentence',
    start_offset=3974,
    end_offset=3978,
    text_slice='先生道：',
    hash='sha256:e87de64b9f5922de4d71b4744048de96c47215642619c8399764dc6aa3e7606a'
)  # 先生道：

seg_0096 = Segment(
    id='hongloumeng_seg_0096',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='dialogue',
    start_offset=3978,
    end_offset=4209,
    text_slice='“看得尊夫人这脉息：左寸沉数，左关沉伏；右寸细而无力，右关需而无神。其左寸沉数者，乃心气虚而生火；左关沉伏者，乃肝家气滞血亏。右寸细而无力者，乃肺经气分太虚；右关需而无神者，乃脾土被肝木克制。心气虚而生火者，应现经期不调，夜间不寐。肝家血亏气滞者，必然肋下疼胀，月信过期，心中发热。肺经气分太虚者，头目不时眩晕，寅卯间必然自汗，如坐舟中。脾土被肝木克制者，必然不思饮食，精神倦怠，四肢酸软。据我看，这脉息应当有这些症候才对。或以这个脉为喜脉，则小弟不敢闻命矣。”',
    hash='sha256:601db612c1242f7afb718405789babbb0e0c2bab74ebee864bb799bd2eb12255'
)  # “看得尊夫人这脉息：左寸沉数，左关沉伏；右寸细而无力，右关需而无神。其左寸沉数者...

seg_0097 = Segment(
    id='hongloumeng_seg_0097',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='sentence',
    start_offset=4209,
    end_offset=4222,
    text_slice='旁边一个贴身伏侍的婆子道：',
    hash='sha256:0193778117f4ab1075f8056ac27e7a7256deacc180bf74dee2b53781ee38a532'
)  # 旁边一个贴身伏侍的婆子道：

seg_0098 = Segment(
    id='hongloumeng_seg_0098',
    doc_id='hongloumeng',
    block_index=12,
    segment_type='dialogue',
    start_offset=4222,
    end_offset=4326,
    text_slice='“何尝不是这样呢。真正先生说的如神，倒不用我们告诉了。如今我们家里现有好几位太医老爷瞧着呢，都不能说得这么当真切。有一位说是喜，有一位说是病；这位说不相干，那位说怕冬至，总没有个准话儿。求老爷明白指示指示。”',
    hash='sha256:2acfe55a0b6fc6a71e1a1741bc45171003ee93a74fef0d1806beff16884df7d5'
)  # “何尝不是这样呢。真正先生说的如神，倒不用我们告诉了。如今我们家里现有好几位太医...

seg_0099 = Segment(
    id='hongloumeng_seg_0099',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='sentence',
    start_offset=4328,
    end_offset=4334,
    text_slice='那先生笑道：',
    hash='sha256:15c3916e68a8fcaff9a7199d9f4e45222a351d199d23c3940ef81b6879096dfd'
)  # 那先生笑道：

seg_0100 = Segment(
    id='hongloumeng_seg_0100',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='dialogue',
    start_offset=4334,
    end_offset=4555,
    text_slice='“大奶奶这个症候，可是那几位耽搁了。要在初次行经的时后就用药治起来，不但断无今日之患，而且此时已全愈了。如今既是把病耽误到这个地位，也是应有此灾。依我看来，这病尚有三分治得。吃了我这药看，若是夜间睡得着觉，那时又添了二分拿手了。据我看这脉息：大奶奶是个心性高强，聪明不过的人；但聪明太过，则不如意事常有；不如意事常有，则思虑太过。此病是忧虑伤脾，肝木忒旺，经血所以不能按时而至。大奶奶从前的行经的日子问一问，断不是常缩，必是常长的。是不是？”',
    hash='sha256:8d4ed589b2ad2be0cb73f9b380bc3f51c742d159039dc749f1cc91b6008e036b'
)  # “大奶奶这个症候，可是那几位耽搁了。要在初次行经的时后就用药治起来，不但断无今日...

seg_0101 = Segment(
    id='hongloumeng_seg_0101',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='sentence',
    start_offset=4555,
    end_offset=4561,
    text_slice='这婆子答道：',
    hash='sha256:4a9ef4d6c433f03e3ba5194f7eb3bcbd44b5f42837cbb3c71a3fa427fc2be082'
)  # 这婆子答道：

seg_0102 = Segment(
    id='hongloumeng_seg_0102',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='dialogue',
    start_offset=4561,
    end_offset=4589,
    text_slice='“可不是，从没有缩过，或是长两日三日，以至十日都长过。”',
    hash='sha256:2c12a2cb04be3b848124ece87272a2489558c402fcac589f91b857461fa870a9'
)  # “可不是，从没有缩过，或是长两日三日，以至十日都长过。”

seg_0103 = Segment(
    id='hongloumeng_seg_0103',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='sentence',
    start_offset=4589,
    end_offset=4595,
    text_slice='先生听了道：',
    hash='sha256:6f7fa725c9d1a20dea089825ac35588fe4827fb540e8911cd7edce617e85603c'
)  # 先生听了道：

seg_0104 = Segment(
    id='hongloumeng_seg_0104',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='dialogue',
    start_offset=4595,
    end_offset=4650,
    text_slice='“妙啊！这就是病源了。从前若能够以养心调经之药服之，何至于此！这如今明显出一个水亏木旺的症候来。待用药看看。”',
    hash='sha256:29e9bf06cc405165c02492a425b211c03ccd8b73b5ac145e7f6372dfb4cc0d1b'
)  # “妙啊！这就是病源了。从前若能够以养心调经之药服之，何至于此！这如今明显出一个水...

seg_0105 = Segment(
    id='hongloumeng_seg_0105',
    doc_id='hongloumeng',
    block_index=13,
    segment_type='sentence',
    start_offset=4650,
    end_offset=4667,
    text_slice='于是写了方子，递与贾蓉，上写的是：',
    hash='sha256:3e9f21c7b296f451e90e27753563236f12a88e28e0fa7b862b9f503a2205054c'
)  # 于是写了方子，递与贾蓉，上写的是：

seg_0106 = Segment(
    id='hongloumeng_seg_0106',
    doc_id='hongloumeng',
    block_index=14,
    segment_type='sentence',
    start_offset=4669,
    end_offset=4678,
    text_slice='益气养荣补脾和肝汤',
    hash='sha256:5ea829f012e1a48143d91902d1fa5aaa07afed93415f27db55d56593c8514c60'
)  # 益气养荣补脾和肝汤

seg_0107 = Segment(
    id='hongloumeng_seg_0107',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4680,
    end_offset=4685,
    text_slice='人参二钱。',
    hash='sha256:b06aedb150c47a3cfd528dcea239f85a7851e6cae6f91f4789d865e1e6c27874'
)  # 人参二钱。

seg_0108 = Segment(
    id='hongloumeng_seg_0108',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4685,
    end_offset=4693,
    text_slice='白朮二钱，土炒。',
    hash='sha256:857e71fb708833fbb841bf783285e43f996695de01035f843efa5e03b8ee1293'
)  # 白朮二钱，土炒。

seg_0109 = Segment(
    id='hongloumeng_seg_0109',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4693,
    end_offset=4698,
    text_slice='云苓三钱。',
    hash='sha256:afb1bff3029f818b5e684c64714537cfde7e60afb6bf41eded59a9fabb9f9e83'
)  # 云苓三钱。

seg_0110 = Segment(
    id='hongloumeng_seg_0110',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4698,
    end_offset=4703,
    text_slice='熟地四钱。',
    hash='sha256:26346f158ce30547831f1510320cbda2b29b9c98f924d8a17d5b27da9b15f26c'
)  # 熟地四钱。

seg_0111 = Segment(
    id='hongloumeng_seg_0111',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4703,
    end_offset=4711,
    text_slice='归身二钱，酒洗。',
    hash='sha256:33a8822a78d80f1162f945249931b16d3486c938a47340e62daa82bb49841507'
)  # 归身二钱，酒洗。

seg_0112 = Segment(
    id='hongloumeng_seg_0112',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4711,
    end_offset=4718,
    text_slice='白芍二钱，炒。',
    hash='sha256:a87df0a100eb422cb68d68b7947ddcb966fbed25a10c759aa8936f8a21a9b8a5'
)  # 白芍二钱，炒。

seg_0113 = Segment(
    id='hongloumeng_seg_0113',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4718,
    end_offset=4723,
    text_slice='川芎钱半。',
    hash='sha256:0ca499ddcbe3ebc27d0e30e000eebdea26dc5d8a8198b9bed66bb5338bd50fbc'
)  # 川芎钱半。

seg_0114 = Segment(
    id='hongloumeng_seg_0114',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4723,
    end_offset=4725,
    text_slice='黄?',
    hash='sha256:bc67128ebad91b97aaadbab807b4d02b8129d880bc06ee35e3a03bec186a3070'
)  # 黄?

seg_0115 = Segment(
    id='hongloumeng_seg_0115',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4725,
    end_offset=4728,
    text_slice='三钱。',
    hash='sha256:c45899b2882dc2eb76f3f51da978a6637016f59796284bbf5a66cc4c8acba792'
)  # 三钱。

seg_0116 = Segment(
    id='hongloumeng_seg_0116',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4728,
    end_offset=4741,
    text_slice='香附米二钱，制醋柴胡八分。',
    hash='sha256:8f143f3d1750887a5e2765999388758741778efa5556957e247df98d40423854'
)  # 香附米二钱，制醋柴胡八分。

seg_0117 = Segment(
    id='hongloumeng_seg_0117',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4741,
    end_offset=4749,
    text_slice='怀山药二钱，炒。',
    hash='sha256:85a1709bda0396d58bfc57ce61a1ac497fe1b7f6fe7d1a1e109c63f8d2c2606a'
)  # 怀山药二钱，炒。

seg_0118 = Segment(
    id='hongloumeng_seg_0118',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4749,
    end_offset=4759,
    text_slice='真阿胶二钱，蛤粉炒。',
    hash='sha256:9186f5b6d40b77fe415b5eb4d9a17b611d30b9359f0c07bfe991c0064772c772'
)  # 真阿胶二钱，蛤粉炒。

seg_0119 = Segment(
    id='hongloumeng_seg_0119',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4759,
    end_offset=4768,
    text_slice='延胡索钱半，酒炒。',
    hash='sha256:825d8cf3a646c8c6e95383f98c15214da86affb5cc8998daa80cceeccd69410e'
)  # 延胡索钱半，酒炒。

seg_0120 = Segment(
    id='hongloumeng_seg_0120',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4768,
    end_offset=4774,
    text_slice='炙甘草八分。',
    hash='sha256:0ebb05c92f936cbeffc949916d7968825294efe784b2602e6e6d526e0da04e8a'
)  # 炙甘草八分。

seg_0121 = Segment(
    id='hongloumeng_seg_0121',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4774,
    end_offset=4785,
    text_slice='引用建莲子七粒，去心。',
    hash='sha256:ec862e435fbe9d1ad5f04773eae154eae719000317f7b59a352d2c159ff37bbe'
)  # 引用建莲子七粒，去心。

seg_0122 = Segment(
    id='hongloumeng_seg_0122',
    doc_id='hongloumeng',
    block_index=15,
    segment_type='sentence',
    start_offset=4785,
    end_offset=4790,
    text_slice='红枣二枚。',
    hash='sha256:7c03bdbd6949484532530066b424276c0a1e0b89f05cb7d227b4b8b6ec3f3799'
)  # 红枣二枚。

seg_0123 = Segment(
    id='hongloumeng_seg_0123',
    doc_id='hongloumeng',
    block_index=16,
    segment_type='sentence',
    start_offset=4792,
    end_offset=4799,
    text_slice='贾蓉看了，说：',
    hash='sha256:3f3b2bf6408aeca08ca6cb216f283b8f7e8e65341a3a0fc465908d90848d245b'
)  # 贾蓉看了，说：

seg_0124 = Segment(
    id='hongloumeng_seg_0124',
    doc_id='hongloumeng',
    block_index=16,
    segment_type='dialogue',
    start_offset=4799,
    end_offset=4825,
    text_slice='“高明得很。还要请教先生，这病与性命终久有妨无妨？”',
    hash='sha256:a06a99caf4a63ec652f4fcac09fdf95dcf4427d4224a2ff595c41b5ca9ee364e'
)  # “高明得很。还要请教先生，这病与性命终久有妨无妨？”

seg_0125 = Segment(
    id='hongloumeng_seg_0125',
    doc_id='hongloumeng',
    block_index=16,
    segment_type='sentence',
    start_offset=4825,
    end_offset=4830,
    text_slice='先生笑道：',
    hash='sha256:7a9a3d0a3aba065ee468f66e567411cd17b78299fb8321db7ca775a1f1c0690f'
)  # 先生笑道：

seg_0126 = Segment(
    id='hongloumeng_seg_0126',
    doc_id='hongloumeng',
    block_index=16,
    segment_type='dialogue',
    start_offset=4830,
    end_offset=4900,
    text_slice='“大爷是最高明的人。人病到这个地位，非一朝一夕的症候，吃了这药，也要看医缘了。依小弟看来，今年一冬是不相干的。总是过了春分，就可望全愈了。”',
    hash='sha256:2c8eb7b7cc418100dbfd23c45a69d205ffc188c753bd6b5d297f7a86d860bc44'
)  # “大爷是最高明的人。人病到这个地位，非一朝一夕的症候，吃了这药，也要看医缘了。依...

seg_0127 = Segment(
    id='hongloumeng_seg_0127',
    doc_id='hongloumeng',
    block_index=16,
    segment_type='sentence',
    start_offset=4900,
    end_offset=4917,
    text_slice='贾蓉也是个聪明人，也不往下细问了。',
    hash='sha256:2dacdf65bedc3be06248a5716710778e74170d4af962d7b631e0d7c72051d367'
)  # 贾蓉也是个聪明人，也不往下细问了。

seg_0128 = Segment(
    id='hongloumeng_seg_0128',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='sentence',
    start_offset=4919,
    end_offset=4960,
    text_slice='于是贾蓉送了先生去了，方将这药方子并脉案都给贾珍看了，说的话也都回了贾珍并尤氏了。',
    hash='sha256:03457b0cb4d8eb42b86da7a17567c9d4a01d97d1830e04d3bca99c2bf9463115'
)  # 于是贾蓉送了先生去了，方将这药方子并脉案都给贾珍看了，说的话也都回了贾珍并尤氏了...

seg_0129 = Segment(
    id='hongloumeng_seg_0129',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='dialogue',
    start_offset=4968,
    end_offset=4992,
    text_slice='“从来大夫不像他说的这么痛快，想必用药也不错。”',
    hash='sha256:d10d126b958d1aaa87ed3c2a33b8b163e4ec46fa4e1356327d3a9075b3d04522'
)  # “从来大夫不像他说的这么痛快，想必用药也不错。”

seg_0130 = Segment(
    id='hongloumeng_seg_0130',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='sentence',
    start_offset=4992,
    end_offset=4996,
    text_slice='贾珍道：',
    hash='sha256:f8a8aedd2ce9740ac4855922a831abf328af70a340beca97664f0fbd7e28f010'
)  # 贾珍道：

seg_0131 = Segment(
    id='hongloumeng_seg_0131',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='dialogue',
    start_offset=4996,
    end_offset=5074,
    text_slice='“人家原不是混饭吃的久惯行医的人。因为冯紫英与我们相好，他好容易求了他来的。既有这个人，媳妇的病或者就能好了。他那方子上有人参，就用前日买的那一斤好的罢。”',
    hash='sha256:61af17d10492014eee94c0eb5f6377826849d81bb8623048817ce9422de56af4'
)  # “人家原不是混饭吃的久惯行医的人。因为冯紫英与我们相好，他好容易求了他来的。既有...

seg_0132 = Segment(
    id='hongloumeng_seg_0132',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='sentence',
    start_offset=5074,
    end_offset=5094,
    text_slice='贾蓉听毕话，方出来叫人打药去煎给秦氏吃。',
    hash='sha256:67b9d183ede8cf7d0f40a4c552bc35d5766cdcaf0b0927459fb11dd6e4875d0f'
)  # 贾蓉听毕话，方出来叫人打药去煎给秦氏吃。

seg_0133 = Segment(
    id='hongloumeng_seg_0133',
    doc_id='hongloumeng',
    block_index=17,
    segment_type='sentence',
    start_offset=5094,
    end_offset=5114,
    text_slice='不知秦氏服了此药病势如何，且听下回分解。',
    hash='sha256:98340420f0bebbcb6917e44a1f839537242023910ee647ebce6b9631aca60abf'
)  # 不知秦氏服了此药病势如何，且听下回分解。

