# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import Claim, EvidenceRef
from .entities import ent_zh_5f3b8c, ent_zh_62b1f4, ent_zh_6b57a8, ent_zh_89350e, ent_zh_949cdf, ent_zh_a5a5a9, ent_zh_d14574, ent_zh_e26e50
from .text import seg_0063, seg_0071, seg_0175, seg_0184, seg_0187, seg_0197

claim_zh_68f43c = Claim(
    id='hongloumeng_clm_0009',
    subject='hongloumeng_ent_0006',
    predicate='plans_to_descend',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

claim_zh_445842 = Claim(
    id='hongloumeng_clm_0010',
    subject='hongloumeng_ent_0005',
    predicate='plans_to_descend',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0063']
)

claim_zh_0d0d5f = Claim(
    id='hongloumeng_clm_0011',
    subject='hongloumeng_ent_0005',
    predicate='intends_to_repay',
    modality='claimed_by_source',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0063', start=262, end=273, quote_hash='sha256:c6f3d8160e3b080adba9ea2f28fdb0437eef86a27db376120c3d464748bfae82')],
    source_segment_ids=['hongloumeng_seg_0063']
)

claim_zh_d63beb = Claim(
    id='hongloumeng_clm_0012',
    subject='hongloumeng_ent_0007',
    predicate='lives_in',
    object='hongloumeng_ent_0014',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0071', start=10, end=17, quote_hash='sha256:775d8d6c17218b9593c6b1dc4adfff4c2f3bb52b66c88b3911496e76e2596d9e')],
    source_segment_ids=['hongloumeng_seg_0071']
)

claim_zh_336f85 = Claim(
    id='hongloumeng_clm_0013',
    subject='hongloumeng_ent_0002',
    predicate='plans_to_visit',
    object='hongloumeng_ent_0014',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0071', start=8, end=17, quote_hash='sha256:cb7048ccde1fac060a1a904b5d47b0fc70866b208c75f272bfadf1a66057d849')],
    source_segment_ids=['hongloumeng_seg_0071']
)

claim_zh_68f23d = Claim(
    id='hongloumeng_clm_0014',
    subject='hongloumeng_ent_0002',
    predicate='enters',
    object='hongloumeng_ent_0013',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[],
    source_segment_ids=['hongloumeng_seg_0090', 'hongloumeng_seg_0093']
)

claim_hongloumeng_ent_0004 = Claim(
    id='hongloumeng_clm_0005',
    subject='hongloumeng_ent_0004',
    predicate='仅生英莲一女',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0184', start=0, end=10, quote_hash='sha256:0ce32e27b9f43a9bd5c7ece950df268390fbda9449c13911632ff43354f7d61a')],
    source_segment_ids=['hongloumeng_seg_0184']
)

claim_hongloumeng_ent_0005 = Claim(
    id='hongloumeng_clm_0007',
    subject='hongloumeng_ent_0005',
    predicate='因思女构疾',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0187', start=3, end=13, quote_hash='sha256:25bf1cc928b04786bfa1298f7b37842cba177aebd55f03d7456fa9c214997be6')],
    source_segment_ids=['hongloumeng_seg_0187']
)

claim_hongloumeng_ent_0004_1 = Claim(
    id='hongloumeng_clm_0008',
    subject='hongloumeng_ent_0004',
    predicate='拟写荐书未及',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0175', start=7, end=15, quote_hash='sha256:b3979971acb5f700c22dd014e1e80ea43a40566f9e2e6e9696734813a0138b01')],
    source_segment_ids=['hongloumeng_seg_0175', 'hongloumeng_seg_0176', 'hongloumeng_seg_0177']
)

claim_zh_368159 = Claim(
    id='hongloumeng_clm_0001',
    subject='hongloumeng_ent_0001',
    predicate='is_father_in_law_of',
    object='hongloumeng_ent_0004',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0197', start=0, end=7, quote_hash='sha256:86f2c17f97f36b8e6f15890ba4855f335f4e3c776c2078054ccfa21f031bb72f')],
    source_segment_ids=['hongloumeng_seg_0197']
)

claim_zh_16152e = Claim(
    id='hongloumeng_clm_0002',
    subject='hongloumeng_ent_0001',
    predicate='from',
    object='hongloumeng_ent_0002',
    modality='asserted',
    polarity='positive',
    confidence=1.0,
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0197', start=8, end=15, quote_hash='sha256:376e2ab9d5af9dfc7bb13e04d9dc597aed223691e607102e419a765a15aad6e0')],
    source_segment_ids=['hongloumeng_seg_0197']
)

