# Auto-generated by t2c v4.0-flash — DO NOT EDIT
from t2c.ontology import Event, EvidenceRef
from .text import seg_0182, seg_0188, seg_0204, seg_0222, seg_0240, seg_0241, seg_0243, seg_0247, seg_0252, seg_0253

evt_zh_b526e2 = Event(
    id='hongloumeng_evt_0008',
    name='霍启畏责逃往他乡',
    kind='occurrence',
    participants=['hongloumeng_ent_0002'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0182', start=13, end=20, quote_hash='sha256:c4e202cb307e44a89ddfd366464d48eb8ba851d6ac5c8c228bef252db36c1de2')],
    source_segment_ids=['hongloumeng_seg_0182']
)

evt_zh_de110a = Event(
    id='hongloumeng_evt_0009',
    name='葫芦庙炸供失火延烧整条街',
    kind='occurrence',
    participants=['hongloumeng_ent_0013'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0188', start=9, end=15, quote_hash='sha256:7421729e831e7dea328ed172c3523aee1d06836ac2fe908f0afd8e36bb41f08b')],
    source_segment_ids=['hongloumeng_seg_0188', 'hongloumeng_seg_0189', 'hongloumeng_seg_0190', 'hongloumeng_seg_0191']
)

evt_zh_fd85e0 = Event(
    id='hongloumeng_evt_0003',
    name='跛足道人唱好了歌',
    kind='occurrence',
    participants=['hongloumeng_ent_0003', 'hongloumeng_ent_0004'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0204', start=41, end=49, quote_hash='sha256:c5e3d52a61a0d00f7b166e6090ce2b4e7cc3756aaafae923388d0bdbdb4e9cb0')],
    source_segment_ids=['hongloumeng_seg_0204', 'hongloumeng_seg_0205', 'hongloumeng_seg_0208', 'hongloumeng_seg_0210', 'hongloumeng_seg_0212']
)

evt_zh_e3c4a6 = Event(
    id='hongloumeng_evt_0004',
    name='士隐解注好了歌',
    kind='occurrence',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0003', 'hongloumeng_ent_0003'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0222', start=10, end=14, quote_hash='sha256:33c4687c97d6a8e927f00115bedfc37af5a28ba2f36fb167941132756aabff5f')],
    source_segment_ids=['hongloumeng_seg_0222', 'hongloumeng_seg_0225', 'hongloumeng_seg_0236']
)

evt_zh_8a3296 = Event(
    id='hongloumeng_evt_0005',
    name='士隐随疯道人出家',
    kind='occurrence',
    participants=['hongloumeng_ent_0004', 'hongloumeng_ent_0003'],
    evidence_refs=[
        EvidenceRef(segment_id='hongloumeng_seg_0240', start=1, end=3, quote_hash='sha256:18e06db4b1b6147e4f5fc08c23795099f3125c8af8884142ed6c463d84b7f210'),
        EvidenceRef(segment_id='hongloumeng_seg_0241', start=24, end=28, quote_hash='sha256:c8be12e46813fe6f3ecdc1d2f4ae6bc3852be16a62f6b27c4e4f65f440c525fd')
    ],
    source_segment_ids=['hongloumeng_seg_0240', 'hongloumeng_seg_0241']
)

evt_zh_4c0312 = Event(
    id='hongloumeng_evt_0006',
    name='封氏遣人访寻士隐',
    kind='occurrence',
    participants=['hongloumeng_ent_0005', 'hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0243', start=22, end=28, quote_hash='sha256:9acb01c43460b08d14b843f39eac700470dd08b3db36a1188eeac98696035084')],
    source_segment_ids=['hongloumeng_seg_0243']
)

evt_zh_f43681 = Event(
    id='hongloumeng_evt_0007',
    name='新太爷到任',
    kind='occurrence',
    participants=[],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0247', start=28, end=33, quote_hash='sha256:e4fd58965a143c121b6853d1e8584d4afe13129c528253fd91e927b3aa0f1d7f')],
    source_segment_ids=['hongloumeng_seg_0247', 'hongloumeng_seg_0248', 'hongloumeng_seg_0249']
)

evt_zh_9605d1 = Event(
    id='hongloumeng_evt_0001',
    name='差人来传本府太爷的话',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0252', start=1, end=12, quote_hash='sha256:e0cb859a42d85f23de4d94b759574ffa8c5ded61077b69d0fe4419ad484a1763')],
    source_segment_ids=['hongloumeng_seg_0252']
)

evt_zh_27765a = Event(
    id='hongloumeng_evt_0002',
    name='封肃受惊',
    kind='occurrence',
    participants=['hongloumeng_ent_0001'],
    evidence_refs=[EvidenceRef(segment_id='hongloumeng_seg_0253', start=5, end=11, quote_hash='sha256:c9323ef9c3bbc13d8614a5078ad05018e54c4fef6d79bfcbcc06aaedfb28319e')],
    source_segment_ids=['hongloumeng_seg_0253']
)

