"""Command line interface for the Text2Code compiler."""
from __future__ import annotations

import argparse
import importlib
import json
import py_compile
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

from t2c.compile_target import compile_to_knowledge_code
from t2c.corpus import CorpusManager
from t2c.coverage import CoverageGenerator
from t2c.extractor import LLMExtractor
from t2c.llm_config import LLMConfig
from t2c.object_store import ObjectStore
from t2c.pipeline import Pipeline
from t2c.segmenter import Segmenter


KNOWN_OUTPUT_FILES = {
    "__init__.py",
    "text.py",
    "entities.py",
    "events.py",
    "claims.py",
    "residuals.py",
    "derived.py",
    "coverage.py",
}


def _safe_doc_id(raw_path: Path) -> str:
    """Generate a stable object ID prefix from the input filename."""
    stem = raw_path.stem.strip() or "document"
    doc_id = re.sub(r"\W+", "_", stem, flags=re.UNICODE).strip("_")
    if not doc_id:
        doc_id = "document"
    if doc_id[0].isdigit():
        doc_id = f"doc_{doc_id}"
    return doc_id


def _is_t2c_generated_file(path: Path) -> bool:
    try:
        first_line = path.read_text(encoding="utf-8", errors="ignore").splitlines()[0]
    except (IndexError, OSError):
        return False
    return first_line.startswith("# Auto-generated by t2c")


def _ingest_without_llm(raw_text: str, raw_path: Path, doc_id: str) -> ObjectStore:
    """Build Document/Block/Segment store without any model call."""
    store = ObjectStore()
    corpus = CorpusManager()
    doc, stored_text = corpus.ingest_text(raw_text, doc_id, str(raw_path))
    blocks = corpus.create_blocks(doc, stored_text)
    doc.block_count = len(blocks)

    segmenter = Segmenter()
    segments = []
    for block in blocks:
        block_text = corpus.get_block_text(doc, block, stored_text)
        segments.extend(segmenter.segment_block(doc.id, block, block_text))

    store.set_raw_text(doc.id, stored_text)
    store.save(doc)
    for block in blocks:
        store.save(block)
    for segment in segments:
        store.save(segment)
    return store


def _sorted_query(store: ObjectStore, type_name: str, **filters: Any) -> list[Any]:
    objects = list(store.query(type_name, **filters))
    if type_name == "Block":
        return sorted(objects, key=lambda o: (o.index, o.start_offset, o.id))
    if type_name == "Segment":
        return sorted(objects, key=lambda o: (o.block_index, o.start_offset, o.id))
    return sorted(objects, key=lambda o: getattr(o, "id", ""))


def _compile_store_to_disk(store: ObjectStore, doc_id: str, output_dir: Path) -> dict[str, Path]:
    docs = _sorted_query(store, "Document", id=doc_id)
    if not docs:
        raise RuntimeError(f"Document {doc_id!r} was not produced")
    doc = docs[0]
    blocks = _sorted_query(store, "Block", doc_id=doc_id)
    segments = _sorted_query(store, "Segment", doc_id=doc_id)
    coverage_report = CoverageGenerator(store).generate_coverage(doc_id)

    return compile_to_knowledge_code(
        doc=doc,
        blocks=blocks,
        segments=segments,
        entities=_sorted_query(store, "Entity"),
        events=_sorted_query(store, "Event"),
        claims=_sorted_query(store, "Claim"),
        residuals=_sorted_query(store, "Residual"),
        ignores=_sorted_query(store, "IgnoreSegment"),
        relations=_sorted_query(store, "Relation"),
        coverage_report=coverage_report,
        output_dir=output_dir,
    )


def _commit_generated_files(staging_dir: Path, output_dir: Path, written: dict[str, Path]) -> dict[str, Path]:
    """Commit verified generated files while preserving non-T2C user files."""
    output_dir.mkdir(parents=True, exist_ok=True)
    backup_dir = staging_dir.parent / "__backup__"
    backup_dir.mkdir()

    final_written: dict[str, Path] = {}
    backups: dict[str, Path | None] = {}
    committed: list[Path] = []

    try:
        for filename in sorted(KNOWN_OUTPUT_FILES):
            target = output_dir / filename
            if not target.exists():
                backups[filename] = None
                continue
            if not target.is_file():
                raise RuntimeError(f"Refusing to overwrite non-file output path: {target}")
            if not _is_t2c_generated_file(target):
                raise RuntimeError(f"Refusing to overwrite non-T2C file: {target}")
            backup = backup_dir / filename
            target.replace(backup)
            backups[filename] = backup

        for filename, staged_path in sorted(written.items()):
            final_path = output_dir / filename
            staged_path.replace(final_path)
            committed.append(final_path)
            final_written[filename] = final_path

    except Exception:
        for path in committed:
            if path.exists() and path.is_file():
                path.unlink()
        for filename, backup in backups.items():
            if backup is not None and backup.exists():
                backup.replace(output_dir / filename)
        raise

    return final_written


def _compile_store_transactionally(
    store: ObjectStore,
    doc_id: str,
    output_dir: Path,
    *,
    verify: bool,
) -> tuple[dict[str, Path], list[str]]:
    """Generate and verify in a temp package, then commit to output_dir."""
    output_dir = output_dir.resolve()
    package_name = output_dir.name or "t2c_output"
    with tempfile.TemporaryDirectory(prefix="t2c_compile_") as tmp:
        staging_dir = Path(tmp) / package_name
        staged_written = _compile_store_to_disk(store, doc_id, staging_dir)
        warnings = [] if not verify else _verify_package(staging_dir, staged_written)
        final_written = _commit_generated_files(staging_dir, output_dir, staged_written)
    return final_written, warnings


def _verify_package(output_dir: Path, written: dict[str, Path]) -> list[str]:
    """Verify syntax and, when possible, runtime imports for generated modules."""
    warnings: list[str] = []
    for path in written.values():
        py_compile.compile(str(path), doraise=True)

    package = output_dir.name
    if not package.isidentifier():
        warnings.append(f"Skipped import verification: output directory {package!r} is not a Python package name")
        return warnings

    parent = str(output_dir.parent.resolve())
    imported: list[str] = []
    sys.path.insert(0, parent)
    try:
        importlib.invalidate_caches()
        # Drop stale modules before import verification. Otherwise a second
        # compile to the same package name could validate against sys.modules
        # entries from the previous run.
        for key in list(sys.modules):
            if key == package or key.startswith(f"{package}."):
                sys.modules.pop(key, None)
        for filename in sorted(written):
            module_name = "__init__" if filename == "__init__.py" else Path(filename).stem
            qualified = package if module_name == "__init__" else f"{package}.{module_name}"
            imported.append(qualified)
            importlib.import_module(qualified)
    finally:
        sys.path.pop(0)
        for qualified in imported:
            sys.modules.pop(qualified, None)
    return warnings


def _raise_if_pipeline_failed(result: Any) -> None:
    """Enforce v4 compile semantics: no partial Knowledge Code output."""
    failed = (not result.valid) or bool(result.errors) or result.rejected_count > 0
    if not failed:
        return
    details: list[str] = []
    if not result.valid:
        details.append("validation did not pass")
    if result.rejected_count > 0:
        details.append(f"{result.rejected_count} object(s) rejected by validation gate")
    if result.errors:
        details.append("; ".join(result.errors[:3]))
    message = "Validation failed; no Knowledge Code package was written"
    if details:
        message += ": " + " | ".join(details)
    raise RuntimeError(message)


def _build_llm_config(args: argparse.Namespace) -> LLMConfig:
    cfg = LLMConfig.from_env(
        provider=args.provider,
        model=args.model,
        base_url=args.base_url,
        api_key=args.api_key,
        max_tokens=args.max_tokens,
        thinking_budget=args.thinking_budget,
        cache_mode=args.cache_mode,
        cache_dir=args.cache_dir,
        extractor_protocol=args.protocol,
    )
    if args.llm and cfg.cache_mode != "read_only" and not cfg.api_key:
        raise RuntimeError(
            f"Missing API key for provider {cfg.provider!r}. "
            "Set T2C_LLM_API_KEY or the provider-specific key."
        )
    if args.llm and cfg.cache_mode == "read_only" and not cfg.api_key:
        cfg.api_key = "t2c-read-only-cache"
    return cfg


def compile_command(args: argparse.Namespace) -> int:
    raw_path = args.raw_path.resolve()
    if not raw_path.exists():
        raise FileNotFoundError(raw_path)
    raw_text = raw_path.read_text(encoding="utf-8")
    doc_id = args.doc_id or _safe_doc_id(raw_path)
    store: ObjectStore | None = None

    try:
        if args.llm and args.text_only:
            raise RuntimeError("--llm and --text-only are mutually exclusive")
        if not args.llm and not args.text_only:
            raise RuntimeError(
                "Semantic Knowledge Code compilation requires --llm. "
                "Use --text-only for a low-cost text map preflight."
            )

        if args.llm:
            cfg = _build_llm_config(args)
            store = ObjectStore()
            extractor = LLMExtractor(config=cfg)
            pipeline = Pipeline(store=store, extractor=extractor, max_repair_attempts=args.max_repair_attempts)
            result = pipeline.process_text(
                raw_text=raw_text,
                doc_id=doc_id,
                source_path=str(raw_path),
                chapter_num=args.chapter_num,
                chapter_title=args.chapter_title or raw_path.stem,
            )
            _raise_if_pipeline_failed(result)
        else:
            cfg = None
            store = _ingest_without_llm(raw_text, raw_path, doc_id)
            result = None

        written, warnings = _compile_store_transactionally(
            store,
            doc_id,
            args.output.resolve(),
            verify=not args.no_verify,
        )

        coverage = CoverageGenerator(store).generate_coverage(doc_id)
        summary = {
            "status": "ok",
            "mode": "semantic_compile" if args.llm else "text_only",
            "semantic_compile": bool(args.llm),
            "doc_id": doc_id,
            "llm": bool(args.llm),
            "provider": cfg.provider if cfg else None,
            "model": cfg.model if cfg else None,
            "cache_mode": cfg.cache_mode if cfg else None,
            "output_dir": str(args.output.resolve()),
            "files": {name: str(path) for name, path in sorted(written.items())},
            "counts": {
                "blocks": len(_sorted_query(store, "Block", doc_id=doc_id)),
                "segments": len(_sorted_query(store, "Segment", doc_id=doc_id)),
                "entities": len(_sorted_query(store, "Entity")),
                "events": len(_sorted_query(store, "Event")),
                "claims": len(_sorted_query(store, "Claim")),
                "relations": len(_sorted_query(store, "Relation")),
                "residuals": len(_sorted_query(store, "Residual")),
            },
            "coverage": coverage.model_dump(),
            "warnings": warnings,
        }
        if result is not None:
            summary["pipeline"] = {
                "valid": result.valid,
                "errors": len(result.errors),
                "warnings": len(result.warnings),
                "saved_count": result.saved_count,
                "rejected_count": result.rejected_count,
                "raw_fallback_segments": len(result.raw_fallback_segment_ids),
                "total_input_tokens": result.total_input_tokens,
                "total_output_tokens": result.total_output_tokens,
                "api_elapsed_sec": round(result.api_elapsed_sec, 2),
                "cache_hits": getattr(extractor, "_cache_hits", 0),
                "cache_misses": getattr(extractor, "_cache_misses", 0),
            }

        if args.json:
            print(json.dumps(summary, ensure_ascii=False, indent=2))
        else:
            if args.llm:
                print(f"Compiled {doc_id} -> {args.output.resolve()}")
            else:
                print(f"Text-only preflight {doc_id} -> {args.output.resolve()}")
            print(f"Files: {', '.join(sorted(written))}")
            print(
                "Counts: "
                f"{summary['counts']['segments']} segments, "
                f"{summary['counts']['entities']} entities, "
                f"{summary['counts']['claims']} claims, "
                f"{summary['counts']['residuals']} residuals"
            )
            if cfg:
                print(f"LLM: {cfg.provider}/{cfg.model} cache={cfg.cache_mode}")
            for warning in warnings:
                print(f"Warning: {warning}", file=sys.stderr)
        return 0
    finally:
        if store is not None:
            store.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="t2c", description="Text2Code compiler")
    sub = parser.add_subparsers(dest="command", required=True)

    compile_p = sub.add_parser("compile", help="Compile raw text into a .t2c.py knowledge package")
    compile_p.add_argument("raw_path", type=Path, help="UTF-8 raw text file")
    compile_p.add_argument("--output", "-o", type=Path, required=True, help="Output package directory")
    compile_p.add_argument("--profile", default="default", help="Genre profile placeholder; currently informational")
    compile_p.add_argument("--doc-id", default=None, help="Override generated document ID")
    compile_p.add_argument("--chapter-num", type=int, default=1, help="Chapter number passed to the extractor")
    compile_p.add_argument("--chapter-title", default="", help="Chapter title passed to the extractor")
    compile_p.add_argument("--llm", action="store_true", help="Run LLM candidate extraction for semantic compile")
    compile_p.add_argument(
        "--text-only",
        action="store_true",
        help="Generate only the replayable text map package; not a semantic compile",
    )
    compile_p.add_argument(
        "--cache-mode",
        choices=["off", "read_write", "read_only", "refresh"],
        default=None,
        help="LLM cache mode; defaults to read_write",
    )
    compile_p.add_argument("--cache-dir", default=None, help="LLM cache directory; defaults to .t2c_cache")
    compile_p.add_argument("--provider", default=None, help="LLM provider; defaults to deepseek")
    compile_p.add_argument("--model", default=None, help="LLM model; defaults to deepseek-v4-flash")
    compile_p.add_argument("--base-url", default=None, help="LLM API base URL")
    compile_p.add_argument("--api-key", default=None, help="LLM API key; env vars are preferred")
    compile_p.add_argument("--max-tokens", type=int, default=None, help="LLM max output tokens")
    compile_p.add_argument("--thinking-budget", type=int, default=None, help="LLM thinking budget")
    compile_p.add_argument("--protocol", default=None, help="Extractor protocol; defaults to compact-v1")
    compile_p.add_argument("--max-repair-attempts", type=int, default=2)
    compile_p.add_argument("--no-verify", action="store_true", help="Skip py_compile/import verification")
    compile_p.add_argument("--json", action="store_true", help="Print machine-readable summary")
    compile_p.set_defaults(func=compile_command)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except Exception as exc:
        if getattr(args, "json", False):
            print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False, indent=2))
        else:
            print(f"t2c: error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
