"""Code Generator — deterministic .t2c.py generation from ontology objects."""
from __future__ import annotations

import ast
from typing import Any

from pydantic import BaseModel

from t2c.ontology import (
    Block,
    CoverageReport,
    Document,
    Entity,
    Event,
    EvidenceRef,
    IgnoreSegment,
    Relation,
    Residual,
    Segment,
)


# Module-level helpers used by v4.0 multi-file generation.
# They scan generated .t2c.py source for symbol names + segment_id mappings
# so we can wire cross-file imports without re-running the model side.
def _scan_symbols(source: str) -> list[tuple[str, str]]:
    """Return [(symbol_name, constructor_type), ...] from generated source."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    out = []
    for node in tree.body:
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            target = node.targets[0]
            if isinstance(target, ast.Name):
                ctor = node.value.func
                if isinstance(ctor, ast.Name):
                    out.append((target.id, ctor.id))
    return out


def _scan_top_level_symbols(source: str) -> list[str]:
    """Return [symbol_name, ...] from generated source (assignments only)."""
    return [name for name, _ in _scan_symbols(source)]


def _extract_segment_id_symbol_map(source: str) -> dict[str, str]:
    """Return {segment_id: symbol_name} for Segment assignments.

    Walks the AST and pairs `seg_NNNN = Segment(id='hongloumeng_seg_0009', ...)`
    so the caller can build the `external_symbols` index for semantic code.
    """
    out: dict[str, str] = {}
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return out
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not isinstance(node.value, ast.Call):
            continue
        ctor = node.value.func
        if not isinstance(ctor, ast.Name) or ctor.id != "Segment":
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        for kw in node.value.keywords:
            if kw.arg == "id" and isinstance(kw.value, ast.Constant):
                out[str(kw.value.value)] = target.id
    return out


# Field order for deterministic output per type
FIELD_ORDER: dict[str, list[str]] = {
    "EvidenceRef": ["segment_id", "segment_symbol", "start", "end", "quote_hash"],
    "Document": ["id", "source_path", "raw_text_hash", "total_length", "block_count", "created_at"],
    "Block": ["id", "doc_id", "index", "block_type", "start_offset", "end_offset", "text_slice", "hash"],
    "Segment": ["id", "doc_id", "block_index", "segment_type", "start_offset", "end_offset",
                "text_slice", "hash"],
    "Entity": ["id", "name", "kind", "aliases", "evidence_refs", "source_segment_ids"],
    "Event": ["id", "name", "kind", "participants", "participant_symbols", "time", "location",
              "evidence_refs", "source_segment_ids"],
    "Claim": ["id", "subject", "subject_symbol", "predicate", "object", "object_symbol",
              "modality", "polarity", "confidence",
              "source", "derived_from", "evidence_refs", "source_segment_ids"],
    "Relation": ["id", "subject", "subject_symbol", "predicate", "object", "object_symbol",
                 "claim_id", "claim_symbol", "evidence_refs"],
    "Residual": ["id", "segment_id", "category", "importance", "reason", "evidence_refs"],
    "IgnoreSegment": ["id", "segment_id", "reason", "evidence_refs"],
    "CoverageReport": ["id", "doc_id", "total_segments", "status_counts", "requires_raw_fallback", "generated_at"],
}

# v4.1: bump version tag for codegraph-native default.
_DEFAULT_VERSION = "v4.1"


class CodeGenerator:
    """Deterministically generate .t2c.py from ontology objects."""

    def __init__(self, version: str | None = None, emit_symbol_refs: bool = True) -> None:
        # Override the default version tag (used in file headers).
        # None → use _DEFAULT_VERSION; pass e.g. "v3.5-flash" to future-proof tests.
        self._version = version or _DEFAULT_VERSION
        # v4.1 default: emit symbol refs for all reference fields so
        # generated .t2c.py is codegraph-native. Pass emit_symbol_refs=False
        # to revert to string-literal-only mode for legacy pipelines.
        self._emit_symbol_refs = emit_symbol_refs

    def generate_document_code(
        self,
        doc: Document,
        blocks: list[Block],
    ) -> str:
        """Generate case_xxx.document.t2c.py."""
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import Document, Block",
            "",
        ]
        lines.append(self._format_object(doc))
        for block in blocks:
            lines.append("")
            lines.append(self._format_object(block))
        return "\n".join(lines) + "\n"

    def generate_segments_code(
        self,
        segments: list[Segment],
    ) -> str:
        """Generate case_xxx.segments.t2c.py."""
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import Segment",
            "",
        ]
        for seg in segments:
            lines.append(self._format_object(seg))
            lines.append("")
        return "\n".join(lines) + "\n"

    def generate_knowledge_code(
        self,
        objects: list[BaseModel],
    ) -> str:
        """Generate case_xxx.knowledge.t2c.py from semantic objects."""
        type_names = sorted(set(obj.__class__.__name__ for obj in objects))
        # Add EvidenceRef if any object has evidence_refs
        if any(hasattr(obj, "evidence_refs") and obj.evidence_refs for obj in objects):
            if "EvidenceRef" not in type_names:
                type_names.append("EvidenceRef")
                type_names.sort()

        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            f"from t2c.ontology import {', '.join(type_names)}",
            "",
        ]
        for obj in objects:
            lines.append(self._format_object(obj))
            lines.append("")
        return "\n".join(lines) + "\n"

    # -- Formatting helpers ----------------------------------------------

    def _format_object(self, obj: BaseModel) -> str:
        """Format a Pydantic object as a constructor call string."""
        type_name = obj.__class__.__name__
        fields = FIELD_ORDER.get(type_name, list(obj.__class__.model_fields.keys()))
        kwargs: list[str] = []
        for field_name in fields:
            value = getattr(obj, field_name, None)
            # Skip None optional fields
            if value is None:
                continue
            # Skip empty defaults
            if isinstance(value, list) and not value and field_name not in ("participants", "evidence_refs"):
                continue
            formatted = self._format_value(value)
            kwargs.append(f"{field_name}={formatted}")

        if not kwargs:
            return f"{type_name}()"

        if len(kwargs) <= 4:
            return f"{type_name}({', '.join(kwargs)})"

        inner = ",\n    ".join(kwargs)
        return f"{type_name}(\n    {inner}\n)"

    # -- v3.3: codegraph-native assignment code generation ------------------

    @staticmethod
    def _symbol_hash(text: str, prefix: str) -> str:
        """Generate a stable Python-safe symbol from arbitrary text.

        Uses sha256 first 6 hex chars for Chinese/unstable names.
        """
        import hashlib
        h = hashlib.sha256(text.encode("utf-8")).hexdigest()[:6]
        return f"{prefix}_zh_{h}"

    @staticmethod
    def _normalize_name(name: str) -> str:
        """Try to produce a Python-safe identifier from a name.

        v4.0: prefer the ASCII prefix of the name when available so
        symbols stay human-readable. E.g. "爱丽丝 (Alice)" → "alice",
        "甄士隐" → "" (no ASCII) → None (caller falls back to hash).
        """
        if not name:
            return None
        # Pure ASCII path
        if name.isascii() and name.replace("_", "").isalnum():
            return name.lower().replace(" ", "_").replace("-", "_")
        # Mixed: try to extract a Python-safe slug from the ASCII parts.
        import re
        # Take any contiguous run of ASCII letters/digits and join with _
        parts = re.findall(r"[A-Za-z0-9]+", name)
        if parts:
            slug = "_".join(parts).lower()
            if slug:
                return slug
        # Pure non-ASCII → caller falls back to hash
        return None

    @staticmethod
    def _format_comment(obj: BaseModel) -> str:
        """Generate an inline comment for FTS5 searchability.

        Returns a human-readable summary appended after the assignment line
        so CodeGraph's tree-sitter captures it as part of the node's context,
        making the symbol findable via full-text search on Chinese names.
        """
        type_name = obj.__class__.__name__
        if type_name == "Entity":
            name = getattr(obj, "name", "")
            kind = getattr(obj, "kind", "")
            return f"# {name} ({kind})"
        if type_name == "Event":
            name = getattr(obj, "name", "")
            return f"# {name}"
        if type_name == "Claim":
            subj = getattr(obj, "subject", "")
            pred = getattr(obj, "predicate", "")
            obj_val = getattr(obj, "object", "") or ""
            parts = f"{subj} {pred} {obj_val}".rstrip()
            return f"# {parts}"
        if type_name == "Segment":
            text = getattr(obj, "text_slice", "")
            preview = text[:40]
            suffix = "..." if len(text) > 40 else ""
            return f"# {preview}{suffix}"
        if type_name == "Document":
            return f"# {getattr(obj, 'source_path', '')}"
        if type_name == "Block":
            return f"# block {getattr(obj, 'index', 0)}"
        if type_name == "Relation":
            subj = getattr(obj, "subject", "")
            pred = getattr(obj, "predicate", "")
            obj_val = getattr(obj, "object", "")
            return f"# {subj} {pred} {obj_val}"
        if type_name == "Residual":
            cat = getattr(obj, "category", "")
            reason = getattr(obj, "reason", "")[:40]
            return f"# {cat}: {reason}"
        if type_name == "IgnoreSegment":
            reason = getattr(obj, "reason", "")[:40]
            return f"# {reason}"
        if type_name == "CoverageReport":
            return f"# coverage: {getattr(obj, 'doc_id', '')}"
        return ""

    def _compute_symbol_names(
        self,
        objects: list[BaseModel],
        seg_symbols: dict[str, str] | None = None,
        ent_symbols: dict[str, str] | None = None,
    ) -> dict[str, str]:
        """Compute stable symbol names for a list of objects.

        Returns {object_id: symbol_name}.
        seg_symbols and ent_symbols are pre-computed mappings used for
        residual/ignore symbol derivation.
        """
        symbols: dict[str, str] = {}
        seg_map = seg_symbols or {}
        ent_map = ent_symbols or {}
        used: set[str] = set()

        for i, obj in enumerate(objects):
            type_name = obj.__class__.__name__
            obj_id = getattr(obj, "id", None) or str(i)

            if type_name == "Segment":
                # seg_0000, seg_0001, ... — strictly sequential, not block_index
                base = f"seg_{i:04d}"
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "Entity":
                ent_name = getattr(obj, "name", "")
                norm = self._normalize_name(ent_name)
                if norm:
                    base = f"ent_{norm}"
                else:
                    base = self._symbol_hash(ent_name + obj_id, "ent")
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "Claim":
                subject = getattr(obj, "subject", "")
                predicate = getattr(obj, "predicate", "")
                obj_val = getattr(obj, "object", "") or ""
                key = f"{subject}_{predicate}_{obj_val}"
                norm = self._normalize_name(key)
                # Use text-based name only if short enough (< 30 chars);
                # otherwise fall back to stable hash for readability
                if norm and len(norm) <= 30:
                    base = f"claim_{norm}"
                else:
                    base = self._symbol_hash(key, "claim")
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "Event":
                evt_name = getattr(obj, "name", "")
                norm = self._normalize_name(evt_name)
                if norm:
                    base = f"evt_{norm}"
                else:
                    base = self._symbol_hash(evt_name + obj_id, "evt")
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "Residual":
                seg_id = getattr(obj, "segment_id", "")
                seg_sym = seg_map.get(seg_id, f"seg_{i:04d}")
                base = f"res_{seg_sym}"
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "IgnoreSegment":
                seg_id = getattr(obj, "segment_id", "")
                seg_sym = seg_map.get(seg_id, f"seg_{i:04d}")
                base = f"ign_{seg_sym}"
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            elif type_name == "Document":
                doc_id = getattr(obj, "id", "doc")
                base = f"doc_{doc_id.replace('.', '_').replace('-', '_')}"
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

            else:
                # Block, Relation, CoverageReport — use type prefix + index
                tn = type_name[:4].lower()
                base = f"{tn}_{i:04d}"
                name = base
                suffix = 0
                while name in used:
                    suffix += 1
                    name = f"{base}_{suffix}"
                symbols[obj_id] = name
                used.add(name)

        return symbols

    def generate_text_code_v33(
        self,
        doc: Document,
        blocks: list[Block],
        segments: list[Segment],
    ) -> dict[str, str]:
        """Generate v3.3 text code layer with assignment symbols.

        Returns dict with single key 'text.py' mapping to code string.
        Each Segment/Block/Document gets a Python symbol.
        """
        # Compute symbols
        all_objects: list[BaseModel] = [doc] + list(blocks) + list(segments)
        symbols = self._compute_symbol_names(all_objects)

        # Build code
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import Document, Block, Segment",
            "",
        ]

        # Document
        doc_sym = symbols.get(doc.id, "doc_0000")
        doc_formatted = self._format_object_v33(doc, symbols)
        doc_comment = self._format_comment(doc)
        if doc_comment:
            lines.append(f"{doc_sym} = {doc_formatted}  {doc_comment}")
        else:
            lines.append(f"{doc_sym} = {doc_formatted}")
        lines.append("")

        # Blocks
        for block in blocks:
            blk_sym = symbols.get(block.id, f"blk_{block.index:04d}")
            blk_formatted = self._format_object_v33(block, symbols)
            blk_comment = self._format_comment(block)
            if blk_comment:
                lines.append(f"{blk_sym} = {blk_formatted}  {blk_comment}")
            else:
                lines.append(f"{blk_sym} = {blk_formatted}")
            lines.append("")

        # Segments
        for seg in segments:
            seg_sym = symbols.get(seg.id, f"seg_{len(lines):04d}")
            seg_formatted = self._format_object_v33(seg, symbols)
            seg_comment = self._format_comment(seg)
            if seg_comment:
                lines.append(f"{seg_sym} = {seg_formatted}  {seg_comment}")
            else:
                lines.append(f"{seg_sym} = {seg_formatted}")
            lines.append("")

        return {"text.py": "\n".join(lines) + "\n"}

    def generate_semantic_code_v33(
        self,
        objects: list[BaseModel],
        external_symbols: dict[str, str] | None = None,
        external_file: str | None = None,
    ) -> dict[str, str]:
        """Generate v3.3 semantic code with assignment + symbol refs.

        Returns dict mapping filename → code string.
        Objects are partitioned by type into separate files.

        external_symbols: {object_id: symbol_name} for objects defined in
            other files (e.g., segments from text.py).
        external_file: the module name to import external symbols from
            (e.g., '.text').
        """
        ext_syms = external_symbols or {}
        ext_module = external_file or ".text"

        # Partition objects by type
        entities = [o for o in objects if o.__class__.__name__ == "Entity"]
        claims = [o for o in objects if o.__class__.__name__ == "Claim"]
        events = [o for o in objects if o.__class__.__name__ == "Event"]
        residuals = [o for o in objects if o.__class__.__name__ == "Residual"]
        ignores = [o for o in objects if o.__class__.__name__ == "IgnoreSegment"]
        relations = [o for o in objects if o.__class__.__name__ == "Relation"]

        # Compute symbols for each group
        ent_symbols = self._compute_symbol_names(entities)
        clm_symbols = self._compute_symbol_names(claims)
        evt_symbols = self._compute_symbol_names(events)
        res_symbols = self._compute_symbol_names(residuals, seg_symbols=ext_syms)
        ign_symbols = self._compute_symbol_names(ignores, seg_symbols=ext_syms)
        rel_symbols = self._compute_symbol_names(relations)

        result: dict[str, str] = {}

        # entities.py
        if entities:
            result["entities.py"] = self._generate_type_file_v33(
                entities, ent_symbols, ["Entity", "EvidenceRef"],
                external_symbols=ext_syms, external_module=ext_module,
            )

        # claims.py
        if claims:
            # Claims may reference entity symbols
            all_ext = dict(ext_syms)
            all_ext.update(ent_symbols)
            result["claims.py"] = self._generate_type_file_v33(
                claims, clm_symbols, ["Claim", "EvidenceRef"],
                external_symbols=all_ext,
                external_modules={ext_module, ".entities"},
            )

        # events.py
        if events:
            all_ext = dict(ext_syms)
            all_ext.update(ent_symbols)
            result["events.py"] = self._generate_type_file_v33(
                events, evt_symbols, ["Event", "EvidenceRef"],
                external_symbols=all_ext,
                external_modules={ext_module, ".entities"},
            )

        # residuals.py
        if residuals:
            result["residuals.py"] = self._generate_type_file_v33(
                residuals, res_symbols, ["Residual", "EvidenceRef"],
                external_symbols=ext_syms, external_module=ext_module,
            )

        # derived.py (relations + ignores)
        derived_objects: list[BaseModel] = list(relations) + list(ignores)
        if derived_objects:
            all_ext = dict(ext_syms)
            all_ext.update(ent_symbols)
            all_ext.update(clm_symbols)
            result["derived.py"] = self._generate_type_file_v33(
                derived_objects,
                {**rel_symbols, **ign_symbols},
                ["Relation", "IgnoreSegment", "EvidenceRef"],
                external_symbols=all_ext,
                external_modules={ext_module, ".entities", ".claims"},
            )

        return result

    def generate_derived_code_v33(
        self,
        relations: list[BaseModel] | None = None,
        ignores: list[BaseModel] | None = None,
        external_symbols: dict[str, str] | None = None,
    ) -> dict[str, str]:
        """Generate v3.3 derived code (relations + ignore segments).

        Returns dict with single key 'derived.py' or empty dict if no objects.
        """
        rels: list[BaseModel] = list(relations or [])
        igns: list[BaseModel] = list(ignores or [])
        derived_objects = rels + igns
        if not derived_objects:
            return {}

        ext_syms = external_symbols or {}

        rel_symbols = self._compute_symbol_names(rels)
        ign_symbols = self._compute_symbol_names(igns, seg_symbols=ext_syms)

        code = self._generate_type_file_v33(
            derived_objects,
            {**rel_symbols, **ign_symbols},
            ["Relation", "IgnoreSegment", "EvidenceRef"],
            external_symbols=ext_syms,
            external_modules={".text", ".entities", ".claims"},
        )
        return {"derived.py": code}

    def _generate_type_file_v33(
        self,
        objects: list[BaseModel],
        symbols: dict[str, str],
        type_names: list[str],
        external_symbols: dict[str, str] | None = None,
        external_module: str | None = None,
        external_modules: set[str] | None = None,
    ) -> str:
        """Generate a single type file with assignment + symbol refs + imports."""
        ext_syms = external_symbols or {}
        modules = external_modules or ({external_module} if external_module else set())

        # Build imports
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            f"from t2c.ontology import {', '.join(type_names)}",
        ]

        # External symbol imports — group by module
        mod_syms: dict[str, list[str]] = {}
        # Segment symbols always live in .text. Entity/Claim/Event/etc
        # symbols are looked up by their ID type below.
        for obj in objects:
            # Check evidence_refs for segment symbol refs
            erefs = getattr(obj, "evidence_refs", []) or []
            for eref in erefs:
                seg_id = getattr(eref, "segment_id", None)
                if seg_id and seg_id in ext_syms:
                    seg_sym = ext_syms[seg_id]
                    # Heuristic: if the symbol is in ext_syms under a segment
                    # ID, it's a segment → import from .text. (Other types
                    # aren't passed in ext_syms for the segment ID space.)
                    mod_syms.setdefault(".text", []).append(seg_sym)

            # Check Claim subject/object for entity symbol refs
            if obj.__class__.__name__ == "Claim":
                subject = getattr(obj, "subject", None)
                if subject and subject in ext_syms:
                    mod_syms.setdefault(".entities", []).append(ext_syms[subject])
                obj_val = getattr(obj, "object", None)
                if obj_val and obj_val in ext_syms:
                    mod_syms.setdefault(".entities", []).append(ext_syms[obj_val])

            # Check Event participants for entity symbol refs
            if obj.__class__.__name__ == "Event":
                for pid in (getattr(obj, "participants", []) or []):
                    if pid in ext_syms:
                        mod_syms.setdefault(".entities", []).append(ext_syms[pid])

            # Check Relation subject/object/claim for symbol refs
            if obj.__class__.__name__ == "Relation":
                for field, mod in [("subject", ".entities"), ("object", ".entities"), ("claim_id", ".claims")]:
                    val = getattr(obj, field, None)
                    if val and val in ext_syms:
                        mod_syms.setdefault(mod, []).append(ext_syms[val])

        for mod in sorted(mod_syms):
            unique_syms = sorted(set(mod_syms[mod]))
            if unique_syms:
                lines.append(f"from {mod} import {', '.join(unique_syms)}")

        lines.append("")

        # Format each object as assignment with FTS5 comment
        for obj in objects:
            obj_id = getattr(obj, "id", None)
            sym = symbols.get(obj_id, f"obj_{len(lines):04d}")
            formatted = self._format_object_v33(obj, {**symbols, **ext_syms})
            comment = self._format_comment(obj)
            if comment:
                lines.append(f"{sym} = {formatted}  {comment}")
            else:
                lines.append(f"{sym} = {formatted}")
            lines.append("")

        return "\n".join(lines) + "\n"

    def _format_object_v33(
        self,
        obj: BaseModel,
        all_symbols: dict[str, str],
    ) -> str:
        """Format a Pydantic object as a v3.3 constructor call.

        v4.0 policy: emit STRING LITERALS for all fields so the generated
        .t2c.py can be imported and validated by stock Pydantic. The
        cross-file symbol navigation is achieved via the explicit
        `from .text import seg_0012` import statements in each file —
        those are the only place symbol refs appear.

        Keyword names use ontology field names (e.g., 'segment_id', not
        the v3.3 alias 'segment') so Pydantic sees valid fields.
        """
        type_name = obj.__class__.__name__
        fields = FIELD_ORDER.get(type_name, list(obj.__class__.model_fields.keys()))

        # Skip internal/symbol fields in output
        SKIP_FIELDS = {
            "subject_symbol", "object_symbol", "segment_symbol",
            "participant_symbols", "claim_symbol",
        }

        kwargs: list[str] = []
        for field_name in fields:
            if field_name in SKIP_FIELDS:
                continue

            value = getattr(obj, field_name, None)
            if value is None:
                continue
            if isinstance(value, list) and not value and field_name not in ("participants", "evidence_refs"):
                continue

            # Use ontology field name + string literal value. v3.3 mode
            # (opt-in) still emits symbol refs + v3.3 keyword aliases for
            # fields like EvidenceRef.segment_id. v4.0 default is string
            # literals for Pydantic safety.
            if self._emit_symbol_refs:
                kw_name = self._v33_keyword_name(type_name, field_name)
                use_symbol = field_name in self._SYMBOL_REF_FIELDS_V33.get(type_name, set())
            else:
                kw_name = field_name
                use_symbol = False
            formatted = self._format_value_v33(value, all_symbols, type_name, field_name, use_symbol)
            kwargs.append(f"{kw_name}={formatted}")

        if not kwargs:
            return f"{type_name}()"

        if len(kwargs) <= 4:
            return f"{type_name}({', '.join(kwargs)})"

        inner = ",\n    ".join(kwargs)
        return f"{type_name}(\n    {inner}\n)"

    # Fields that should be emitted as symbol refs (not string literals)
    # v4.0 default: only top-level subject/object/participants/claim_id
    # fields use symbol refs. EvidenceRef.segment_id is NOT a symbol-ref
    # field by default (EvidenceRef is a nested value, not a top-level
    # symbol, so its segment_id must be a string literal that Pydantic
    # can validate).
    #
    # v3.3 mode (opt-in via emit_symbol_refs=True) restores the original
    # v3.3 behavior where EvidenceRef.segment_id is also a symbol ref.
    _SYMBOL_REF_FIELDS_DEFAULT: dict[str, set[str]] = {
        "Claim": {"subject", "object"},
        "Event": {"participants"},
        "Relation": {"subject", "object", "claim_id"},
        "Residual": {"segment_id"},
        "IgnoreSegment": {"segment_id"},
    }
    _SYMBOL_REF_FIELDS_V33: dict[str, set[str]] = {
        "EvidenceRef": {"segment_id"},
        "Claim": {"subject", "object"},
        "Event": {"participants"},
        "Relation": {"subject", "object", "claim_id"},
        "Residual": {"segment_id"},
        "IgnoreSegment": {"segment_id"},
    }

    @staticmethod
    def _v33_keyword_name(type_name: str, field_name: str) -> str:
        """Map ontology field name to v3.3 codegen keyword name.

        For symbol-ref-capable fields, emit shorter keyword names that
        match what codegraph tools see as symbol names.
        """
        # EvidenceRef.segment_id → segment (for symbol ref compat)
        if type_name == "EvidenceRef" and field_name == "segment_id":
            return "segment"
        # Relation.claim_id → claim (for symbol ref compat)
        if type_name == "Relation" and field_name == "claim_id":
            return "claim"
        return field_name

    @classmethod
    def _is_symbol_ref_field(cls, type_name: str, field_name: str) -> bool:
        """Check if a field should be emitted as a symbol ref.

        Uses v3.3 set (with EvidenceRef.segment_id) when called on a v3.3
        instance, otherwise the v4.0 default set.
        """
        # This is a static helper; the caller (in _format_object_v33) knows
        # whether we're in v3.3 mode. The caller passes use_symbol directly
        # in modern code, so this method is retained for compatibility with
        # tests that may still call it.
        return field_name in cls._SYMBOL_REF_FIELDS_V33.get(type_name, set())

    def _format_value_v33(
        self,
        value: Any,
        all_symbols: dict[str, str],
        parent_type: str = "",
        field_name: str = "",
        use_symbol: bool = False,
    ) -> str:
        """Format a value for v3.3 code, using symbol refs when available.

        Only substitutes symbol refs for fields marked as symbol-ref-capable
        (e.g., segment_id, subject, object, participants, claim_id).
        """
        if isinstance(value, str):
            # Only substitute symbol ref for specific reference fields
            if use_symbol and value in all_symbols:
                return all_symbols[value]
            return repr(value)
        if isinstance(value, bool):
            return "True" if value else "False"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return str(value)
        if value is None:
            return "None"
        if isinstance(value, BaseModel):
            return self._format_object_v33(value, all_symbols)
        if isinstance(value, list):
            if not value:
                return "[]"
            if all(isinstance(v, BaseModel) for v in value):
                items = [self._format_object_v33(v, all_symbols) for v in value]
                if len(items) == 1:
                    return f"[{items[0]}]"
                inner = ",\n        ".join(items)
                return f"[\n        {inner}\n    ]"
            # For string lists (e.g., participants), check symbol refs
            items = [self._format_value_v33(v, all_symbols, parent_type, field_name, use_symbol) for v in value]
            return f"[{', '.join(items)}]"
        if isinstance(value, dict):
            if not value:
                return "{}"
            pairs = [f"{repr(k)}: {self._format_value_v33(v, all_symbols)}" for k, v in value.items()]
            return "{" + ", ".join(pairs) + "}"
        if hasattr(value, "value"):
            return repr(value.value)
        return repr(value)

    def _format_value(self, value: Any) -> str:
        """Format a Python value as a .t2c.py literal."""
        if isinstance(value, str):
            return repr(value)
        if isinstance(value, bool):
            return "True" if value else "False"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return str(value)
        if value is None:
            return "None"
        if isinstance(value, BaseModel):
            return self._format_object(value)
        if isinstance(value, list):
            if not value:
                return "[]"
            # Check for nested BaseModel objects (e.g. EvidenceRef)
            if all(isinstance(v, BaseModel) for v in value):
                items = [self._format_object(v) for v in value]
                if len(items) == 1:
                    return f"[{items[0]}]"
                inner = ",\n        ".join(items)
                return f"[\n        {inner}\n    ]"
            items = [self._format_value(v) for v in value]
            return f"[{', '.join(items)}]"
        if isinstance(value, dict):
            if not value:
                return "{}"
            pairs = [f"{repr(k)}: {self._format_value(v)}" for k, v in value.items()]
            return "{" + ", ".join(pairs) + "}"
        # Enum-like with .value
        if hasattr(value, "value"):
            return repr(value.value)
        return repr(value)

    # -- v4.0 multi-file compilation ---------------------------------------

    def generate_init_py(
        self,
        symbols: dict[str, str],
    ) -> str:
        """Generate __init__.py marker file.

        v4.0 policy: do NOT auto-import the module-level symbols. Pydantic
        models validate at construction time, so importing them at package
        load can fail-fast on a missing type. Instead, the cross-file
        `from .text import seg_XXXX` imports inside each module are the
        codegraph-friendly navigation surface; `__init__.py` is just a
        package marker so the directory is importable as a namespace.
        """
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            f"# {len(symbols)} symbols across {len(set(symbols.values()))} modules.",
            f"# See individual files (text.py, entities.py, claims.py, ...).",
            "",
        ]
        return "\n".join(lines)

    def generate_coverage_code(
        self,
        report: CoverageReport,
    ) -> str:
        """Generate coverage.py from a CoverageReport Pydantic model.

        v4.1: uses assignment format so CodeGraph indexes the CoverageReport
        as a variable node (not an orphaned expression).
        """
        formatted = self._format_object(report)
        comment = self._format_comment(report)
        assignment = f"coverage_report = {formatted}"
        if comment:
            assignment = f"{assignment}  {comment}"
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import CoverageReport",
            "",
            assignment,
            "",
        ]
        return "\n".join(lines)

    def generate_multi_file_compilation(
        self,
        doc: Document,
        blocks: list[Block],
        segments: list[Segment],
        entities: list[Entity] | None = None,
        events: list[Event] | None = None,
        claims: list[Any] | None = None,
        residuals: list[Residual] | None = None,
        ignores: list[IgnoreSegment] | None = None,
        relations: list[Relation] | None = None,
        coverage_report: CoverageReport | None = None,
    ) -> dict[str, str]:
        """One-stop multi-file Knowledge Code generation.

        Returns dict mapping filename → code string:
          - text.py
          - entities.py (if entities)
          - events.py (if events)
          - claims.py (if claims)
          - residuals.py (if residuals or ignores)
          - derived.py (if relations)
          - coverage.py (if coverage_report)
          - __init__.py

        All cross-file references use real Python imports; all objects
        are symbol assignments — codegraph navigable.
        """
        files: dict[str, str] = {}

        # --- text.py ---
        text_files = self.generate_text_code_v33(doc, blocks, segments)
        files["text.py"] = text_files["text.py"]

        # Build the cross-file symbol index from text.py.
        # Parse text.py to extract Document/Block/Segment symbols.
        text_parser_symbols: dict[str, str] = {}  # {segment_id: symbol_name}
        for sym_name, type_name in _scan_symbols(files["text.py"]):
            if type_name == "Segment":
                # We need segment_id; pull it from the source.
                # _scan_symbols returns (symbol, type); we re-scan the source.
                pass
        # Re-parse text.py to get segment_id → symbol mapping
        text_source = files["text.py"]
        seg_id_to_sym = _extract_segment_id_symbol_map(text_source)

        # Collect semantic objects, each will get a symbol in its own file.
        all_symbols: dict[str, str] = {}  # symbol → relative module
        # External = segment symbols (defined in .text)
        for sid, sym in seg_id_to_sym.items():
            all_symbols[sym] = ".text"

        # Pre-declare symbol maps so they're accessible across blocks
        ent_syms: dict[str, str] = {}
        clm_syms: dict[str, str] = {}

        # --- entities.py ---
        if entities:
            ent_syms = self._compute_symbol_names(list(entities))
            files["entities.py"] = self._generate_type_file_v33(
                list(entities), ent_syms, ["Entity", "EvidenceRef"],
                external_symbols=seg_id_to_sym,
                external_modules={".text"},
            )
            for sym in _scan_top_level_symbols(files["entities.py"]):
                all_symbols[sym] = ".entities"

        # --- events.py ---
        if events:
            evt_syms = self._compute_symbol_names(list(events))
            # Events reference both segment symbols and entity symbols
            evt_ext_syms = dict(seg_id_to_sym)
            if ent_syms:
                evt_ext_syms.update(ent_syms)
            files["events.py"] = self._generate_type_file_v33(
                list(events), evt_syms, ["Event", "EvidenceRef"],
                external_symbols=evt_ext_syms,
                external_modules={".text", ".entities"} if ent_syms else {".text"},
            )
            for sym in _scan_top_level_symbols(files["events.py"]):
                all_symbols[sym] = ".events"

        # --- claims.py ---
        if claims:
            clm_syms = self._compute_symbol_names(list(claims))
            claim_ext_syms = dict(seg_id_to_sym)
            if entities:
                ent_syms_for_claims = self._compute_symbol_names(list(entities))
                claim_ext_syms.update(ent_syms_for_claims)
            files["claims.py"] = self._generate_type_file_v33(
                list(claims), clm_syms, ["Claim", "EvidenceRef"],
                external_symbols=claim_ext_syms,
                external_modules={".text", ".entities"},
            )
            for sym in _scan_top_level_symbols(files["claims.py"]):
                all_symbols[sym] = ".claims"

        # --- residuals.py (Residual + IgnoreSegment) ---
        if residuals or ignores:
            res_ign = list(residuals or []) + list(ignores or [])
            res_ign_syms = self._compute_symbol_names(res_ign, seg_symbols=seg_id_to_sym)
            files["residuals.py"] = self._generate_type_file_v33(
                res_ign, res_ign_syms, ["Residual", "EvidenceRef"],
                external_symbols=seg_id_to_sym,
                external_modules={".text"},
            )
            for sym in _scan_top_level_symbols(files["residuals.py"]):
                all_symbols[sym] = ".residuals"

        # --- derived.py (Relation) ---
        if relations:
            rel_syms = self._compute_symbol_names(list(relations))
            # Relations reference segments, entities, and claims
            derived_ext_syms = dict(seg_id_to_sym)
            if ent_syms:
                derived_ext_syms.update(ent_syms)
            if clm_syms:
                derived_ext_syms.update(clm_syms)
            files["derived.py"] = self._generate_type_file_v33(
                list(relations), rel_syms, ["Relation", "EvidenceRef"],
                external_symbols=derived_ext_syms,
                external_modules={".text", ".entities", ".claims"},
            )
            for sym in _scan_top_level_symbols(files["derived.py"]):
                all_symbols[sym] = ".derived"

        # --- coverage.py ---
        if coverage_report:
            files["coverage.py"] = self.generate_coverage_code(coverage_report)

        # --- __init__.py ---
        files["__init__.py"] = self.generate_init_py(all_symbols)

        return files