"""Code Generator — deterministic .t2c.py generation from ontology objects."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from t2c.ontology import (
    Block,
    Document,
    EvidenceRef,
    Segment,
)


# Field order for deterministic output per type
FIELD_ORDER: dict[str, list[str]] = {
    "EvidenceRef": ["segment_id", "start", "end", "quote_hash"],
    "Document": ["id", "source_path", "raw_text_hash", "total_length", "block_count", "created_at"],
    "Block": ["id", "doc_id", "index", "block_type", "start_offset", "end_offset", "text_slice", "hash"],
    "Segment": ["id", "doc_id", "block_index", "segment_type", "start_offset", "end_offset",
                "text_slice", "hash"],
    "Entity": ["id", "name", "kind", "aliases", "evidence_refs", "source_segment_ids"],
    "Event": ["id", "name", "kind", "participants", "time", "location",
              "evidence_refs", "source_segment_ids"],
    "Claim": ["id", "subject", "predicate", "object", "modality", "polarity", "confidence",
              "source", "derived_from", "evidence_refs", "source_segment_ids"],
    "Relation": ["id", "subject", "predicate", "object", "claim_id", "evidence_refs"],
    "Residual": ["id", "segment_id", "category", "importance", "reason", "evidence_refs"],
    "IgnoreSegment": ["id", "segment_id", "reason", "evidence_refs"],
    "CoverageReport": ["id", "doc_id", "total_segments", "status_counts", "requires_raw_fallback", "generated_at"],
}

# v3.4.1: bump version tag so generated .t2c.py headers reflect the engine that wrote them.
_DEFAULT_VERSION = "v3.4-flash"


class CodeGenerator:
    """Deterministically generate .t2c.py from ontology objects."""

    def __init__(self, version: str | None = None) -> None:
        # Override the default version tag (used in file headers).
        # None → use _DEFAULT_VERSION; pass e.g. "v3.5-flash" to future-proof tests.
        self._version = version or _DEFAULT_VERSION

    def generate_document_code(
        self,
        doc: Document,
        blocks: list[Block],
    ) -> str:
        """Generate case_xxx.document.t2c.py."""
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import Document, Block",
            "",
        ]
        lines.append(self._format_object(doc))
        for block in blocks:
            lines.append("")
            lines.append(self._format_object(block))
        return "\n".join(lines) + "\n"

    def generate_segments_code(
        self,
        segments: list[Segment],
    ) -> str:
        """Generate case_xxx.segments.t2c.py."""
        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            "from t2c.ontology import Segment",
            "",
        ]
        for seg in segments:
            lines.append(self._format_object(seg))
            lines.append("")
        return "\n".join(lines) + "\n"

    def generate_knowledge_code(
        self,
        objects: list[BaseModel],
    ) -> str:
        """Generate case_xxx.knowledge.t2c.py from semantic objects."""
        type_names = sorted(set(obj.__class__.__name__ for obj in objects))
        # Add EvidenceRef if any object has evidence_refs
        if any(hasattr(obj, "evidence_refs") and obj.evidence_refs for obj in objects):
            if "EvidenceRef" not in type_names:
                type_names.append("EvidenceRef")
                type_names.sort()

        lines = [
            f"# Auto-generated by t2c {self._version} — DO NOT EDIT",
            f"from t2c.ontology import {', '.join(type_names)}",
            "",
        ]
        for obj in objects:
            lines.append(self._format_object(obj))
            lines.append("")
        return "\n".join(lines) + "\n"

    # -- Formatting helpers ----------------------------------------------

    def _format_object(self, obj: BaseModel) -> str:
        """Format a Pydantic object as a constructor call string."""
        type_name = obj.__class__.__name__
        fields = FIELD_ORDER.get(type_name, list(obj.__class__.model_fields.keys()))
        kwargs: list[str] = []
        for field_name in fields:
            value = getattr(obj, field_name, None)
            # Skip None optional fields
            if value is None:
                continue
            # Skip empty defaults
            if isinstance(value, list) and not value and field_name not in ("participants", "evidence_refs"):
                continue
            formatted = self._format_value(value)
            kwargs.append(f"{field_name}={formatted}")

        if not kwargs:
            return f"{type_name}()"

        if len(kwargs) <= 4:
            return f"{type_name}({', '.join(kwargs)})"

        inner = ",\n    ".join(kwargs)
        return f"{type_name}(\n    {inner}\n)"

    def _format_value(self, value: Any) -> str:
        """Format a Python value as a .t2c.py literal."""
        if isinstance(value, str):
            return repr(value)
        if isinstance(value, bool):
            return "True" if value else "False"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return str(value)
        if value is None:
            return "None"
        if isinstance(value, BaseModel):
            return self._format_object(value)
        if isinstance(value, list):
            if not value:
                return "[]"
            # Check for nested BaseModel objects (e.g. EvidenceRef)
            if all(isinstance(v, BaseModel) for v in value):
                items = [self._format_object(v) for v in value]
                if len(items) == 1:
                    return f"[{items[0]}]"
                inner = ",\n        ".join(items)
                return f"[\n        {inner}\n    ]"
            items = [self._format_value(v) for v in value]
            return f"[{', '.join(items)}]"
        if isinstance(value, dict):
            if not value:
                return "{}"
            pairs = [f"{repr(k)}: {self._format_value(v)}" for k, v in value.items()]
            return "{" + ", ".join(pairs) + "}"
        # Enum-like with .value
        if hasattr(value, "value"):
            return repr(value.value)
        return repr(value)